### ISSUE TITLE
config request- Pump power configuration. 

### ISSUE THREAD

**Issue by KillerRamer** [rwtema/extrautilities_old_issues#10]
I'm currently working on a themed modpack and trying to keep the tech limited, however a way to obtain lava magically is one of the issue's, and the ender pump could pass for a magicical machine of mystery. However i'm trying to avoid generators or bringing in tech mods for it. Thus i'd like to set it so it's powerless, the hitch however comes in where only the ender quarry has a power configuration.

**Comment by wrincewind** [comment]
This isn't 100% related, but if you're looking for a magical way to make lava, you might want to look into Blood Magic. It has a ritual called 'Serenade of the Nether' that generates lava in exchange for the blood of players of monsters. This just might work for you! plus, you know, it's a fun mod.

**Comment by rwtema** [comment]
Not a significant issue.
