### ISSUE TITLE
incorrect recipe

### ISSUE THREAD

**Issue by idealjo** [rwtema/extrautilities_old_issues#100]
with extrautilities-1.1.0-rc1
NotEnoughItems-1.7.2-1.0.1

Recipe for magical wood show in NEI is for one block, but when you craft it you get 3.
moreover you  cannot use Shift-Left click in Nei to craft this block.

**Comment by rwtema** [comment]
The magical wood recipe gives extra if the enchanted books are made with better enchant (its not entirely accurate because there is a range of levels that produce each book) and is working as intended.

The shift-right-click is an NEI issue that is unlikely to be fixed.
