### ISSUE TITLE
[1.10.2] Magical Wood and Golden Lasso recipes are gone.

### ISSUE THREAD

**Issue by jawsawn** [rwtema/extrautilities_old_issues#1003]
The is no way to craft them. That is a major bug.

**Comment by Darkosto** [comment]
This is partially true, you CAN craft them. The recipes do not show up because of how JEI changed their recipe handling. Yes, this is a big bug, but they can be crafted.

**Comment by b0bst3r** [comment]
mezz Forestry & JEI Dev 
"ExtraUtils2 was using some JEI internal classes, which changed in the latest JEI version."

That was before RWTema updated but the recipes are still not showing in the new updated version.

Magical wood = bookshelf + gold ingot in crafting table (reqs 4 XP)
Golden Lassoo = gold nuggets in each corner - string in each side - middle empty (reqs 8 XP)

Can't see any others which require XP so maybe just those 2 are not showing.

**Comment by jawsawn** [comment]
I've tried crafting it. But it didn't do anything.

**Comment by b0bst3r** [comment]
You have the XP ?  It works here, also if you go look at the (u)ses for bookshelves you can see the recipe.

**Comment by davv1** [comment]
In 1.11.2 it's showing recipe in wrong manner. Look up screen.

![obraz](https://user-images.githubusercontent.com/13569795/28493628-336c4300-6f1a-11e7-9415-eba2b492e0e3.png)
