### ISSUE TITLE
[1.10.2] [OptiFine] Broken Textures

### ISSUE THREAD

**Issue by ChloeDawn** [rwtema/extrautilities_old_issues#1009]
I know it's not technically your problem, but I thought I should inform you that block and item textures appear to be missing on the latest 1.10.2 version of Extra Utilities 2 when the mod is loaded alongside the latest OptiFine preview (which I'm using because it supports a more recent Forge version). However I can confirm that this issue is still existent in [OptiFine C3](http://optifine.net/changelog?f=OptiFine_1.10.2_HD_U_C3.jar). I initially thought it was a conflict in the modpack I tested it with, but I also loaded it up on a client with just Extra Utilities, JEI, and OptiFine installed, and it still had the same issue. I see the errors in the game log where it failed to register the textures, but I'm not smart enough to understand it (line 181 to 236 I think).

Here is a log file from game start to loading a world and opening JEI to the screen below:

**[pastebin.com/QLC1HJcf](http://pastebin.com/QLC1HJcf)**

![2016-10-06_12 02 38](https://cloud.githubusercontent.com/assets/9869940/19150112/0f7deee4-8bbd-11e6-9b8a-5c78d8f2f590.png)

Minecraft version: **[1.10.2](https://mojang.com/2016/06/minecraft-1101/)**
Forge version: **[12.18.1.2095](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.1.2095/forge-1.10.2-12.18.1.2095-changelog.txt)**
Mod version: **[1.10.2 Alpha 1.1.0a](https://minecraft.curseforge.com/projects/extra-utilities/files/2334249)**
OptiFine version: **[1.10.2 HD U C4 Preview](http://optifine.net/changelog?f=preview_OptiFine_1.10.2_HD_U_C4_pre.jar)**

**Comment by DatrixTHLK** [comment]
You may want to back track to C3 of optifine because that still works and using preview builds are known to have issues.
