### ISSUE TITLE
Bad chat message when user die by Unstable Ingot

### ISSUE THREAD

**Issue by luchokoldo** [rwtema/extrautilities_old_issues#102]
Hi, first sorry for my english; When one of my friends die by Unstable Ingot i get this message in the chat

![msg](https://cloud.githubusercontent.com/assets/6044994/3109735/db2ddb9e-e69c-11e3-8bce-7198128195e7.jpg)

**Comment by rwtema** [comment]
That's intended. It's a reference to Javas name for the error of dividing by zero.
