### ISSUE TITLE
extra utilities not working

### ISSUE THREAD

**Issue by carlobonandrini** [rwtema/extrautilities_old_issues#1034]
I'm on Minecraft 1.7.10 and I'm using extra utilities 1.2.12.
when I load Minecraft with extra utilities, forge try to construct the mods but it fails and it remains on a screen with texture of dirt and won't load Minecraft.
sorry for my bad English. 
what can I do?
is there a core or a lib for extra utilities??

**Comment by DatrixTHLK** [comment]
Is there a message that pops up when stuck on the dirt loading screen? Put the FML log in your report from gist.github.com. and paste the link here, if there is no message poping up.
