### ISSUE TITLE
fragile ender marker 

### ISSUE THREAD

**Issue by idealjo** [rwtema/extrautilities_old_issues#104]
ender marker disappear when hiting it with the hand to get it back. like in creative mode

single usage only or bug ?

**Comment by idealjo** [comment]
with extrautilities-1.1.0a

**Comment by rwtema** [comment]
Not intended- what's happened is their material is marked as 'rock' and therefore Minecraft automatically requires you to use a pickaxe to mine them. I'll fix it in the next version.

**Comment by TherminatorX** [comment]
I like the explanation, please do this for other bug reports that come along.

**Comment by rwtema** [comment]
Fixed in 1.1.0b
