### ISSUE TITLE
Can't Extract from Ex Nihilo Omnia Crucible

### ISSUE THREAD

**Issue by DatrixTHLK** [rwtema/extrautilities_old_issues#1045]
I remember back in 1.7.2 transfer node (liquid), and pipes would transfer liquid from the side of a tank to the top or bottom of another tank. With Ex Nihilo Omnia no lava is getting transfered from the side of a crucible to the top of the iron drum. Has your mod changed to include some power source needed to move the liquids from place to place? Or do I need to ask this on the issues page of Ex Nihilo Omnia's page? Minecraft 1.10.2 Forge 2107 Extra Utilities: 1.1.0c

**Comment by Farronox** [comment]
Liquids will pass from top of Crucible, and I've found that the liquid transfer node doesn't block cobblestone from entering the crucible if it is being transferred through the same system.

**Comment by DatrixTHLK** [comment]
Well I'm using a item hopper to pull from the chest above it and moving the cobble stone to the crucible below the hopper. How am I suppose to pull from the top of the crucible if that is already in use? I can't really pull from the bottom of the crucible because then no heat source would be applied to the underside of the crucible.

**Comment by Farronox** [comment]
Don't ask me how or why, but this is a valid set up

[No Lava](http://imgur.com/TswD3FD)

[Melted](http://imgur.com/HwMV5On)

**Comment by DatrixTHLK** [comment]
Uh...ok. That's not valid from my perspective...but whatever floats the mod authors boat.
Issue is closed.
