### ISSUE TITLE
Diamond Spikes

### ISSUE THREAD

**Issue by MCTyler** [rwtema/extrautilities_old_issues#1049]
Please bring those back! Nothing can substitute those in a XP Grinder thats soooo fun!!!!

**Comment by xChitose** [comment]
Until they're implemented, try out Spikes Mod.

**Comment by MCTyler** [comment]
Only for MC Version 1.8 and below, Thanks anyway....I'm running 1.10.2.
For anyone else that may run across this, Draconic Evolution Has a Nice Mob Killer that just uses RF and the recipe is fairly cheap! (No constantly replacing swords...Bonus!)
