### ISSUE TITLE
Transfer node interaction with locked Jabba barrels

### ISSUE THREAD

**Issue by JohnFreemason** [rwtema/extrautilities_old_issues#105]
When the last item is extracted, it flickers in the nodes buffer spot repeatedly.  The last item is not transferred to the next available inventory.  This issue does not happen when the barrel is unlocked.

**Comment by TherminatorX** [comment]
The nodes are trying to pull out a ghost item, similar to #42 and #91.

**Comment by rwtema** [comment]
This issue was fixed in 1.1.0-Pre7. I've tested with 1.1.0a  and it doesn't happen - please update.
