### ISSUE TITLE
[extra utilities 1.1.0a] ender quarry percentage complete still being wierd

### ISSUE THREAD

**Issue by Acters** [rwtema/extrautilities_old_issues#106]
the ender quarries percentage is Way too small but it still finishes...(see screenshot)
![bug3](https://cloud.githubusercontent.com/assets/6981852/3129599/7b3c6ba6-e7e6-11e3-9f7b-e7d707868b10.PNG)

**Comment by rwtema** [comment]
Oh fuck it, I'm just removing the damn percentage indicator. Problem solved.

**Comment by Acters** [comment]
even though that the only way I measered how long it will take...
I agree with what ever you like! :D
