### ISSUE TITLE
Pipes indicators facing both sides

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#107]
I think this is a bug, almost sure.
The pipes, depending from what side you watching them, show a different path direction.
Here a photo:
![2](https://cloud.githubusercontent.com/assets/7746836/3130756/c65cb576-e7fc-11e3-8d7f-e4adfd1c9769.jpg)
Version: extrautilities-1.1.0-prerelease-4.jar and I think it's still present in extrautilities-1.1.0-prerelease-6.jar

**Comment by rwtema** [comment]
Ah yes, this is because Minecraft fixed its handling of textures where it arbitrarily flipped textures on certain sides. My code compensated for the vanilla bug so now I have to tell it to stop compensating. It's a common issue for mods updating, even vanilla beds suffer from it.

**Comment by ghost** [comment]
Oh ok ;)

Yes the beds also had the same issue...

Thanks on the feedback.

**Comment by rwtema** [comment]
Fixed in 1.1.0b. As well as other blocks such as the conveyors.
