### ISSUE TITLE
[XU2] Setting a dimension ID to 0 crashes outputting a "Dimension already created"

### ISSUE THREAD

**Issue by vladfrangu** [rwtema/extrautilities_old_issues#1077]
According to the code, if a dimension ID is set to 0, it should disable it. This doesn't work in the latest version.

https://gist.github.com/KingDGrizzle/577646c32822db8aa18e8de2341cbd92

It seems to be at line 48, which the code says if Id is 0, disable the dimension. I'm guessing the disabling toggle hasn't been implemented yet

**Comment by drexplosionpd** [comment]
change them to false if you want the dim disabled, dim IDs probably shouldnt be changed unless it conflicts with another mod

The disable toggle has been implemented under
enabled {
    B:"Deep Dark"=true
    B:ExtraUtils2_Quarry_Dim=true
