### ISSUE TITLE
Watering can not working on Cactus/Sugar Cane

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#108]
Watering can not working on Cactus/Sugar Cane

Version extrautilities-1.1.0-prerelease-6.jar

PS: Does Watering can also works on vines? If so, I think it's broke also.

**Comment by rwtema** [comment]
I made it so that it only works on plants that are bonemeal-able. In retrospect I don't particularly like the change and I'll change it back.

**Comment by ghost** [comment]
Thanks. One question, idea for the mod, can be placed also here? If that's the case, and as it's watering can related. It would be fun if the watering can if you use them in the range of torches, the torch turn off and then you need a flint and steel or a light torch to turn it back on :)

**Comment by TherminatorX** [comment]
Interesting idea, but how would this mess with other mods interacting with torches?

Other suggestion: make a designated XU suggestions GitHub thread, if you do take suggestions

**Comment by ghost** [comment]
TherminatorX Thanks, yes I also thought the same, in fact I think there is some mod that makes the torches to get unlit, but as always, you can config the mods to prevent this, like having a config option to turn it on and of.

+1 also on the "designated XU suggestions GitHub thread" ;)

**Comment by rwtema** [comment]
I'm afraid I don't take suggestions - I've far too many ideas of my own that I've got to implement first.

**Comment by TherminatorX** [comment]
I thought that, but no harm in asking, unless it's repeated and annoying, which I hope this is not.

**Comment by ghost** [comment]
Oh ok. Make perfect sense :)

**Comment by rwtema** [comment]
Fixed in 1.1.0b
