### ISSUE TITLE
Complete Distribution Upgrade not working properly

### ISSUE THREAD

**Issue by sherlockmatt** [rwtema/extrautilities_old_issues#109]
As I understand it, this upgrade should traverse the network like the Depth-First or Breadth-First upgrades, except that it moves on after each step, instead of after that inventory is full. I noticed this while using the new auto crafting to make Octuple Compressed Cobblestone, some of the chests would fill quite a bit, and inevitably one would be empty, severely impacting on the speed of the contraption overall. It is at least moving on sometimes, but I think it repeats some inventories before completing the network (not necessarily all the time). I will try and get an image of all the chests soon.

**Comment by sherlockmatt** [comment]
Ok, that was easier to make than expected. The transfer node is above the middle chest, and the image is spatially correct.
![cobblechests](https://cloud.githubusercontent.com/assets/5717750/3137824/71f7236a-e85e-11e3-93b1-c61384587b05.png)

**Comment by rwtema** [comment]
Just to clarify the distribution/pseudo-round-robin upgrade does not change the search method from the default 'random walk'. You will need a separate depth-first/breadth-first upgrade for that.

**Comment by sherlockmatt** [comment]
Ok, possibly needs documentation as such then. Thanks for the quick reply.
