### ISSUE TITLE
[1.10.2] Resonating Redstone crystal/ Redstone ore Issue

### ISSUE THREAD

**Issue by drexplosionpd** [rwtema/extrautilities_old_issues#1099]
You can break a redstone ore with a silk touch pickaxe, then place it down and break it again to effectively get infinite Crystals at the cost of pickaxe durability.

is this fixable without using some complicated logging system that would cause lag or removing the drop feature completely?

**Comment by ghost** [comment]
Fixed in yesterday's version.

**Comment by drexplosionpd** [comment]
Fixed in version 1.1.2
