### ISSUE TITLE
In certain situations, cannot open filter pipe GUI. EU v1.0.3c

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#11]
![2014-03-25_23 03 08](https://f.cloud.github.com/assets/4131470/2521556/53440c66-b4ac-11e3-9981-b207fb32de5b.png)
 The pipes on the edges can open fine, but the three middle ones will not open no matter what.

**Comment by ghost** [comment]
this however, can open. I think it might be an issue with FMP compatibility.
![2014-03-25_23 05 46](https://f.cloud.github.com/assets/4131470/2521583/ca75cf72-b4ac-11e3-815d-eacf67e1bcb6.png)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
