### ISSUE TITLE
java.lang.NoClassDefFoundError: com/rwtema/extrautils/tileentity/TileEntityEnderThermicLavaPump

### ISSUE THREAD

**Issue by kosakriszi** [rwtema/extrautilities_old_issues#110]
Seems to be a BuildCraft API thing.

Game versions 1.7.2-forge-10.12.1.1079
Buildcraft version 6.0.16
ExtraUtils version 1.1.0a

http://pastebin.com/GDNNyFWf

**Comment by TherminatorX** [comment]
This is when you tried to power the pump with BC power?

**Comment by kosakriszi** [comment]
Actually, this is when the game launches

**Comment by TherminatorX** [comment]
Sorry, I'm still not quite too good with these kind of things, is this a crash, or just an error you noticed?

**Comment by kosakriszi** [comment]
This was a crash which was only present on the clientside, the server did not have this problem

**Comment by ghost** [comment]
Same Error here, but without Buildcraft installed.

**Comment by rwtema** [comment]
I'm guessing something is including the Buildcraft API but not including the proper power classes. This may require some rethinking.

**Comment by rwtema** [comment]
Wait you're using buildcraft in this instance? Fuck me I don't know then.

**Comment by kosakriszi** [comment]
What version of the BuildCraft API did you build against?

**Comment by TherminatorX** [comment]
This seems to be an issue with and without BC, which makes it hard to track down. I haven't dabbled into 1.7 yet, still stuck in the past.

**Comment by Eneitilyn** [comment]
I have the exact same issue without buildcraft it crashes on Launch when i install OresPlus-0.6.33_Beta with extrautilities-1.1.0a . Ores Plus has buildcraft api inside( i also tried to be all genious about it and deleted the whole buildcraft named folder and it didn't worked still crashes it) http://pastebin.com/mWmuJESR

**Comment by ghost** [comment]
Pre 5a is the latest working for me, newer ones crashes with that error above.

**Comment by Eneitilyn** [comment]
confirmed it actually works with pre 5a it's so weird i tried to update ores plus to the most unstable beta alpha (and all other word letter thing versions) but it didn't work and i just downgraded to 5a and it works now

**Comment by kosakriszi** [comment]
Hey rwtema, would it be possible for you to build your mod with the Buildcraft 6 API? If it's too much hassle, I understand!

**Comment by Leftorius** [comment]
Any update yet? because with that error I can't use extra utilities :/

**Comment by rwtema** [comment]
Hopefully fixed in 1.1.0b. I'm now including the new BC API so it shouldn't bring up this particular error anymore.
