### ISSUE TITLE
Transfer Node dupe bug

### ISSUE THREAD

**Issue by the-creamster** [rwtema/extrautilities_old_issues#111]
I've found a way to duplicate transfer nodes quite by accident. Place a cover on a transfer node, remove it and u have another transfer node :)

**Comment by rwtema** [comment]
Unable to replicate. What version are you using?

**Comment by the-creamster** [comment]
Extra Utilities 1.1.0a,
MInecraft Forge 10.12.1.1110

Replication instructions:
1. place a cobblestone cover on a item transfer node without upgrades
2. break the cobblestone cover & u'll get another one

If you can't replicate it with the above info, the modpack is as following:
- Botania
- AE2
- Thaumcraft 4
- Forbidden Magic
- Extra Utilities
- Enchanting Plus
- Mystcraft
- Witchery
- Tinkers Construct
- Tinkers Mechworks
- Natura
- Remote IO
- Pneumaticraft
- Voxel Map
- Journey Map
- Open Computers
- JABBA
- WAILA
- EVOC(server side only)
- Iron Chests
- Forge Multipart
- Factorisation
- Ender IO
- Chisel
- Carpenters Blocks
- Blood Magic
- Open Eye
- NEI
- Inventory Tweaks

**Comment by Acters** [comment]
I actually replicated this :/
extra utilities 1.1.0a and FMP 1.1.0.282
I've been trying to get to my liquid node and poof, I got a free liquid node!
extra testing on my pickaxe and I found interesting results:
I found out tinkers picks reproduce this duplication glitch, not regular picks!!!

**Comment by the-creamster** [comment]
That's why, sorry about not giving that vital piece of info RWtema. Good someone else picked me up on it.

**Comment by TherminatorX** [comment]
You might want to also report this to the SlimeKnights, then.

**Comment by the-creamster** [comment]
There you go, just filed it with them incase its not extra utilities; https://github.com/SlimeKnights/TinkersConstruct/issues/685

**Comment by rwtema** [comment]
I've looked on my end and I can't see anything that would cause this so this is probably a TCon bug.
