### ISSUE TITLE
NEI Crash in deep Dark.

### ISSUE THREAD

**Issue by Newhill20** [rwtema/extrautilities_old_issues#112]
When I right click on the time setting's in NEI it saves and closes my world. I know that it's meant to be dark in the Deep Dark I just clicked the wrong button and it crashed. This crash can be replicated by going to the deep dark with NEI installed and right clicking the time settings. I am using the Recommended version of extra utilities And NEI.

**Comment by rwtema** [comment]
NEI issue. It happens in all non-overworld dimensions.

**Comment by Newhill20** [comment]
Ok My bad.
