### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by ThoBekMic** [rwtema/extrautilities_old_issues#113]
Hello rwtema

Here's a bug report for you:
http://pastebin.com/y5Emdquu

This is a major returning issue on our server. We had one of our devs analyze it, and he found out that the Ender Quarries are the cause:

Other than that, thanks for an awesome mod :)

Kind regards,
ShamblerDK, owner of Awesomesauce 1.2.5 - 1.7.2

**Comment by ghost** [comment]
It seems the quarry is trying to unload a chunk that is not loaded on server load. This is happening on my server too :/

**Comment by rwtema** [comment]
It's not the quarry, its the ender markers. There's a bug where it starts processing too early during world load. For now, just remove them to fix.

**Comment by ThoBekMic** [comment]
Thanks for the quick response. We'll await an update :-)

**Comment by rwtema** [comment]
Fixed in 1.1.0b
