### ISSUE TITLE
Dark Glass letting light through

### ISSUE THREAD

**Issue by Xerow** [rwtema/extrautilities_old_issues#114]
A room using dark glass keeps light out generally.  However there's an issue when using the Arcane Lamp from Thaumcraft 4.1.0 and Extra Utilities 1.0.3.  Specifically with the arcane lamps.  A room that is supposed to be pitch black lets light in from the arcane lamp.  I'm not sure if the issue is from Extra Utilities with how it blocks light, or with Thaumcraft 4's arcane lamps and how they generate light blocks not seeing dark glass as something that should block light.
![2014-06-08_12 28 55](https://cloud.githubusercontent.com/assets/4020820/3212221/593c5c74-ef4c-11e3-9c66-d6609f2e8b3e.png)

edit:  Minecraft 1.6.4

**Comment by Acters** [comment]
no its just that the arcane lamp puts a light source inside the building...
you can tell by going inside and punching randomly for the light sources

**Comment by Xerow** [comment]
I understand that it puts a light source in the building, however if the room was completely made of stone blocks this doesn't happen.  It stays dark inside.  Something about the dark glass lets the pathing for the light source think it should put one in there.

**Comment by Xerow** [comment]
I stand corrected.  I sealed the room completely and it still lit up from the lamp.  My apologies.

**Comment by Acters** [comment]
it's ok I went trough the same thing! xD
but I didn't complain openly... :P
