### ISSUE TITLE
Searching for fake players name

### ISSUE THREAD

**Issue by MrPatience** [rwtema/extrautilities_old_issues#1144]
I'm searching for your mechanical user and spikes fakeplayernames , because griefpreventionplus doesn't allow them to kill animals if i don't trust them , and the server admin where i'm playing probably removed the /autotrust command

**Comment by ghost** [comment]
You should copy this to the GriefPreventionPlus issues page.

**Comment by MrPatience** [comment]
Well , it's not Gpp issue since the plugin is working , it's just that my admin seems to have blocked the commands to players. I'm just asking here for the fake players names because he's not here for a few days and I can't have the same grinder for animals and mobs

**Comment by ghost** [comment]
Mod interaction is an issue for both mods. Unfortunately, Tema doesn't comment too often. I'll see if I can get something with GPP set up and check the logs to see if there's a name mentioned.

**Comment by MrPatience** [comment]
I found we have GriefPrevention andnot griefpreventionplus because of Sponge and 1.10.. It doesn't seems to allow fakeplayers ,sorry for that

**Comment by ghost** [comment]
No problem. Thank you for closing.
