### ISSUE TITLE
Item Transfer Node/QED Item creation

### ISSUE THREAD

**Issue by NthPortal** [rwtema/extrautilities_old_issues#115]
Transfer nodes pulling out of the bottom, side and top of the QED create items.
Specific conditions: Item transfer nodes with a stack each of stack upgrades and speed upgrades pulling Ender-Flux Crystals out of the QED. Ender-Flux Crystals are only created when the QED is finished crafting them, but they're not actually pulled out of the QED.
Using version 1.1.0b

**Comment by rwtema** [comment]
Should be fixed in the next version.
