### ISSUE TITLE
High-Temperature Generator donst work correctly

### ISSUE THREAD

**Issue by luchokoldo** [rwtema/extrautilities_old_issues#118]
Hi, first sorry for my english; I think its a bug.. idk how this generator work, its the first time I use this, this generator "destroy" my charcoal, I make a video; 

https://www.youtube.com/watch?v=gNkXu0ct1LI

Im using eu.1.1.0b

**Comment by ericBG** [comment]
This is intended behavior IIRC,

**Comment by inochi** [comment]
High temperature generators eat fuel. You're not going to get an extended amount of time just using a cheap "tier 1" fuel such as charcoal. You're better off using coal blocks.

**Comment by rwtema** [comment]
Generator has been reworked in next version - 1.1.0c.
