### ISSUE TITLE
Filling Cabinet bug

### ISSUE THREAD

**Issue by luchokoldo** [rwtema/extrautilities_old_issues#119]
Hi, first sorry for my english; I get this log when I try to open my filing cabinet; I think that happend when the golem(thaumcraft) pass the limit off the cabinet ( with mana beans )

client log
http://pastebin.com/V3iXk2Q6

server log
http://pastebin.com/w0THAXq8

**Comment by rwtema** [comment]
Looks to be a thaumcraft rendering bug

**Comment by luchokoldo** [comment]
when I see {Aspects:[0:{amount:1,key:"Erebus"}]} make me think its a Thaumcraft addon bug;

My bad
