### ISSUE TITLE
[1.1.0b] All nodes showing particles without Portable Scanners!

### ISSUE THREAD

**Issue by Shad0wB1ade** [rwtema/extrautilities_old_issues#121]
Had to roll back to Extra Utilities 1.1.0a because i had like 64 speed upgrades in many nodes :( 0FPS is not a good thing! 

BTW the particles are the ones that show when u have you have a Portable Scanner!

**Comment by rwtema** [comment]
Intended, check the changelog. There's a config to disable it.
