### ISSUE TITLE
"Grid is overloaded" error on RF-based machines

### ISSUE THREAD

**Issue by xenoflot** [rwtema/extrautilities_old_issues#1210]
Hi,

If a GP network is overloaded, xu2 RF-based machines (such as the grinder) halt with the message "Grid is overloaded". 

Also, looking at these machines (Furnace, Furnace Gen & Grinder) gives the gridpower usage display.

Since there is no Resonating Redstone Crystal in the recipes for these items, thus no link to the GP network, I am concluding that this is unintended behaviour.

I have a heavy modpack so if this isn't happening in isolation, let me know and I'll try to narrow down the conflict.

Cheers!

extrautils2-1.10.2-1.1.3c
forge 2185

**Comment by ghost** [comment]
This is known. You can use speed upgrades to increase the rate at which generators use fuel and produce power. The speed upgrades have a GP cost, so the furnaces have a 0 GP cost without them and an overloaded grid shuts them down. I agree that 0 GP machines should not shut down when the grid is overloaded, but that's Tema's call.

**Comment by xenoflot** [comment]
Indeed. It'd be ideal if the basic function worked w/o GP and just the upgrades stopped working in an overload case.

Thanks for letting me know! I'll leave this open. Perhaps Tema will see it.

**Comment by ghost** [comment]
I suggest you close it and make a new issue requesting that generators not shut down completely when the grid is overloaded, or at least that it be a config option. Others might send their support and it will be more visible.

**Comment by xenoflot** [comment]
Will do.
