### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by CruaverVoidDrake** [rwtema/extrautilities_old_issues#122]
The mod clearly has the textures but it isn't being recognized. How do I fix this?

**Comment by rwtema** [comment]
Which textures?

Are you using optifine?

**Comment by CruaverVoidDrake** [comment]
Yes I have optifine and most of the textures missing are on the generators, compressed items, and colored stone.

**Comment by rwtema** [comment]
Does it occur without optifine?

**Comment by CruaverVoidDrake** [comment]
Checking now…(five minutes later)…yes

**Comment by CruaverVoidDrake** [comment]
Ok I checked again apparently I hadn't removed optifine the first time properly, but yes I can see the missing textures. Why did optifine remove them in the first place?

**Comment by rwtema** [comment]
Presumably due to messing up the loading of custom texture classes. Sadly there's nothing I can do about it. This is an optifine issue.
