### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by cresenzi565** [rwtema/extrautilities_old_issues#124]
http://pastebin.com/c4X6S2wg

Ever since a certain house was made on the server it crashes with extra utilities enabled.

   It is currently running version 1.0.3C. (Through a modpack so updating wont help). Is there any way to resolve this issue? The chunk has been destroyed and regenned multiple times but it still continues to crash.

  Thanks in advance!

**Comment by rwtema** [comment]
This appears to be an EnderStorage crash.
