### ISSUE TITLE
Crash when doing ritual

### ISSUE THREAD

**Issue by mrp-v2** [rwtema/extrautilities_old_issues#1250]
I was doing a ritual to activate a division sigil, but when I got to the point where you kill a mob when it's on the "alter", the game crashed. Here is the crash report:

http://pastebin.com/YwJnUm9U

Any help would be appreciated!! Also, this crash report appears every time I try to get back on this world.

**Comment by InjuredWolf** [comment]
Just a tip: use Pastebin for logs and crash reports. Makes it easier to scroll through the conversation. Pastebin is free, too. :)
