### ISSUE TITLE
Crash after updating to 1.1.0b

### ISSUE THREAD

**Issue by zepanv** [rwtema/extrautilities_old_issues#126]
Let me know if you need the full log or if the openeye is enough.

http://openeye.openmods.info/crashes/03a6f295d0bc8ea64f7f0ce5f73ac604

**Comment by zepanv** [comment]
After further debugging this seems to be more related to the recent forge changes, specifically 1113.

Reverting to Forge 1112 and this issue does not appear.

**Comment by rwtema** [comment]
This appears to be a Jabba crash.
