### ISSUE TITLE
magicial wood uncraftable

### ISSUE THREAD

**Issue by meelock** [rwtema/extrautilities_old_issues#1265]
idk why i wasn't able to craft it, close this issue please.

**Comment by blueagledev** [comment]
Have you used a vanilla crafting table and also had 4 XP levels?

**Comment by meelock** [comment]
yes. Maybe I'll post a mod list and log.

edit: here's a modlist http://pastebin.com/LHE83nmf

**Comment by meelock** [comment]
This might have to do with the fact that I was using quark book shelves.

**Comment by meelock** [comment]
close this issue.

**Comment by InjuredWolf** [comment]
yes, quark bookshelves don't have compatibility with several mods (tinkers' moss ball, for one). A possible solution would be to use the oredictionary name for bookshelves in the recipe (if not in forge normally, then do a check for quark, and then use it).

**Comment by TheUnderTaker11** [comment]
Can you not close your own issue?

**Comment by meelock** [comment]
no.

**Comment by meelock** [comment]
nope, I'm probably a idiot. I can't find it.
