### ISSUE TITLE
Crash when opening trading post with villagers from mods (or with items from mods)

### ISSUE THREAD

**Issue by RuinTD** [rwtema/extrautilities_old_issues#127]
```
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/16/14 12:41 AM
Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: length(748) exceeds dst.writableBytes(256) where dst is: UnpooledHeapByteBuf(ridx: 0, widx: 0, cap: 256)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:689)
    at com.rwtema.extrautils.network.splitter.PacketSplitter.splitPacket(PacketSplitter.java:32)
    at com.rwtema.extrautils.network.NetworkHandler.sendSplitPacket(NetworkHandler.java:46)
    at com.rwtema.extrautils.block.BlockTradingPost.func_149727_a(BlockTradingPost.java:72)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:372)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:643)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:689)
    at com.rwtema.extrautils.network.splitter.PacketSplitter.splitPacket(PacketSplitter.java:32)
    at com.rwtema.extrautils.network.NetworkHandler.sendSplitPacket(NetworkHandler.java:46)
    at com.rwtema.extrautils.block.BlockTradingPost.func_149727_a(BlockTradingPost.java:72)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:372)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@95aad89
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:643)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 336750392 bytes (321 MB) / 826277888 bytes (788 MB) up to 954728448 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 4145 (232120 bytes; 0 MB) allocated, 3895 (218120 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.211.1121 Minecraft Forge 10.12.2.1121 35 mods loaded, 35 mods active
    mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FML{7.2.211.1121} [Forge Mod Loader] (forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Forge{10.12.2.1121} [Minecraft Forge] (forge-1.7.2-10.12.2.1121.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    malisiscore{1.7.2-0.7.2} [Malisis Core] (malisiscore-1.7.2-0.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FamiliarsAPI{1.7.2c} [Familiars API] (FamiliarsAPI-1.7.2c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    battlegear2{1.0.5.5} [Mine & Blade Battlegear 2 - Bullseye] (1.7.2-MB_Battlegear2-Bullseye-1.0.5.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    DamageIndicatorsMod{3.1.2} [Damage Indicators] ([1.7.2]DamageIndicatorsMod-3.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Baubles{1.0.0.16} [Baubles] (Baubles-1.7.2-1.0.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BiblioCraft{1.7.1} [BiblioCraft] (BiblioCraft[1.7.1][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Core{6.0.16} [BuildCraft] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Builders{6.0.16} [BC Builders] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Energy{6.0.16} [BC Energy] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Factory{6.0.16} [BC Factory] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Transport{6.0.16} [BC Transport] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    BuildCraft|Silicon{6.0.16} [BC Silicon] (buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    CarpentersBlocks{3.1.5} [Carpenter's Blocks] (Carpenter's Blocks v3.1.5 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    chisel{1.5.4f} [Chisel] (Chisel-1.7.2-1.5.4f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    craftguide{1.6.8.1} [CraftGuide] (CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    craftingpillars{1.5.1} [Crafting Pillars Mod] (craftingpillars-1.7.2-1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    ExtraUtilities{1.1.0b} [Extra Utilities] (extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FamiliarsDefaultMobPack{1.7.2b} [DefaultMobPack] (FamiliarsDefaultMobPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FamiliarsExtendedFamPack{1.7.2b} [ExtendedFamPack] (FamiliarsExtendedFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    FamiliarsHerobrineFamPack{1.7.2b} [HerobrineFamPack] (FamiliarsHerobrineFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IC2{2.1.478-experimental} [IndustrialCraft 2] (industrialcraft-2-2.1.478-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    IronChest{6.0.14.719} [Iron Chest] (ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    JABBA{1.1.3} [Jabba] (Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    SlimevoidLib{2.0.4.6} [Slimevoid Library] (SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    LittleBlocks{2.2.4.1} [Little Blocks] (LittleBlocks-2.2.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    malisisdoors{1.7.2-0.6.4} [Malisis' Doors] (malisisdoors-1.7.2-0.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    radixcore{1.2.0} [RadixCore] (RadixCore-1.2.0 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    mca{4.0.4} [Minecraft Comes Alive] (MCA-4.0.4 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    mythril{1.6} [Mythril mod] (mithril_mod-1.7.2-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Thaumcraft{4.1.1.14} [Thaumcraft] (Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    mysticaltrinkets{1.3.0} [Mystical Trinkets] (Mystical Trinkets-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    WirelessRedstoneCore{1.8.0.0} [Wireless Redstone] (WirelessRedstoneCore-1.8.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2185 (122360 bytes; 0 MB) allocated, 2007 (112392 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['MCGamer20000'/959508, l='New World', x=137.68, y=4.00, z=-1420.30]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Be-Cool-Man** [comment]
WARNING! Following text translated by Google-Translator:

I have the same problem. Through the experiments I found out that MC crashes when more than six trading options are available.

**Comment by RuinTD** [comment]
Actually, I did some more testing. The crash is either with:
1. Villagers added by mods
2. Villagers with items from mods

**Comment by AlleahSTAR** [comment]
Same issue. Using a different (newer) version of forge than the OP. Probably because of mods' npcs? I have a few different mods at add a villager and I think all of them trade that mod's items.

Placed the trading post in a fairly large village with at least a Thaumcraft and Witchery villager. Right clicked to use it and crashed immediately with this report:

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 27/06/14 12:14 AM
Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: length(517) exceeds dst.writableBytes(256) where dst is: UnpooledHeapByteBuf(ridx: 0, widx: 0, cap: 256)
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:689)
    at com.rwtema.extrautils.network.splitter.PacketSplitter.splitPacket(PacketSplitter.java:32)
    at com.rwtema.extrautils.network.NetworkHandler.sendSplitPacket(NetworkHandler.java:46)
    at com.rwtema.extrautils.block.BlockTradingPost.func_149727_a(BlockTradingPost.java:72)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:372)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:644)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:689)
    at com.rwtema.extrautils.network.splitter.PacketSplitter.splitPacket(PacketSplitter.java:32)
    at com.rwtema.extrautils.network.NetworkHandler.sendSplitPacket(NetworkHandler.java:46)
    at com.rwtema.extrautils.block.BlockTradingPost.func_149727_a(BlockTradingPost.java:72)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:372)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:551)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:197)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@5c1e4ff5
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:644)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Linux (amd64) version 3.13.0-24-generic
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2121798536 bytes (2023 MB) / 5718933504 bytes (5454 MB) up to 7635730432 bytes (7282 MB)
    JVM Flags: 2 total; -Xmx8G -Xms4G
    AABB Pool Size: 4320 (241920 bytes; 0 MB) allocated, 4109 (230104 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
    FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 50 mods loaded, 49 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.2.217.1147} [Forge Mod Loader](forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.12.2.1147} [Minecraft Forge](forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-stable-2} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.11} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv0-stable-2} [Applied Energistics 2](appliedenergistics2-rv0-stable-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.2 v1.7.0} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.0.1} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.1.892-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChestTransporter{1.1.9} [Chest Transporter](ChestTransporter-1.1.9-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{1.5.4f} [Chisel](Chisel-1.7.2-1.5.4f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ImmibisCore{58.0.3} [Immibis Core](ImmibisCore-1.7.2-58.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimensionalAnchors{58.0.0} [Dimensional Anchors](DimensionalAnchors-1.7.2-58.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    exnihilo{1.33} [Ex Nihilo](Ex-Nihilo-1.33.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.0.16} [Baubles](Baubles-1.7.2-1.0.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.0.283} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.2-0.8.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{1.7.2-0.8.80} [Factorization](Factorization-1.7.2-0.8.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{1.7.2-0.8.80} [Factorization Miscellaneous Nonsense](Factorization-1.7.2-0.8.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    gravestonemod{1.7.2} [GraveStone](GraveStones-1.7.2_1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wuppy29_harderpeaceful{1.7.2} [Harder Peaceful](Harder Peaceful 1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.32.724} [Iron Chest](ironchest-1.7.2-6.0.32.724-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{4.0.1} [JourneyMap Unlimited Edition](JourneyMap4.0.1_Unlimited_MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.4.1.39} [ProjectRed](ProjectRed-Base-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.4.1.39} [ProjectRed-Integration](ProjectRed-Integration-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.4.1.39} [ProjectRed-Transmission](ProjectRed-Integration-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.4.1.39} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.4.1.39} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.4.1.39} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.4.1.39} [ProjectRed-Exploration](ProjectRed-World-1.7.2-4.4.1.39.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{2.4-147} [Thaumic Tinkerer](ThaumicTinkerer-2.4-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.1.1} [The Twilight Forest](twilightforest-1.7.2-2.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.19.2} [Witchery](witchery-1.7.2-0.19.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    zoommod{1.2} [ZoomMod](ZoomMod[1.7.2][1.2][Forge].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.0.283} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.0.283} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DimensionalAnchorsCore{} [Dimensional Anchors Coremod](minecraft.jar) Unloaded->Disabled
    AE2 Version: stable rv0-stable-2 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:OFF, MJ5:ON, MJ6:ON, RF:ON, MFR:OFF, DSU:OFF, FZ:ON, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:ON
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 2619 (146664 bytes; 0 MB) allocated, 1665 (93240 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Lopsided_Gringle'/137, l='Who Knows', x=2079.49, y=65.00, z=1562.02]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by rwtema** [comment]
Will be fixed in the next version.
