### ISSUE TITLE
Extrautils2 v1.1.3d: Transfer node on a furnace is pulling the fuel...

### ISSUE THREAD

**Issue by dhvik** [rwtema/extrautilities_old_issues#1295]
Using Extrautils2 v1.10.2-1.1.3d (included in skyfactory v3.0.6 modpack).
When I place a transfer node on a furnace, it pulls out the fuel. I was expecting it to pull out the cooked stuff...

**Comment by Kzorith** [comment]
I believe vanilla furnaces are ISided.  I'm guessing you put the transfer node on the side of the furnace.  In vanilla furnaces, fuel goes in the side, stuff to be cooked goes in the top, processed stuff comes out the bottom.  Assuming I remember right.

**Comment by IamAlathe** [comment]
That's how it works with hoppers, I would assume it would be the same.

**Comment by dhvik** [comment]
Ah, sorry, my bad. Of course that what where happening.
