### ISSUE TITLE
Cursed Earth Not Producing mobs in 1.7.2 on Version 1.1.0b

### ISSUE THREAD

**Issue by xoption** [rwtema/extrautilities_old_issues#130]
Good afternoon, 
I've tested this version on several beta/alpha 1.7.2 mod packs our community has put together. In all instances the cursed earth is not producing mobs as expected. No crash report to paste. Just no mobs. Below is a list of all mods in our pack currently. So far all other items tested from your awesome mod have worked as expected! You are awesome! Let me know if we can get you any other information. - mwbennett - Tech Admin http://www.prospercraft.com/

[1.7.2]
1.7.2-MB_Battlegear2-Bullseye-1.0.5.5.jar
advancedgenetics-1.5.4-1.7.2.jar
AdvancedThaumaturgy-1.7.2-0.1.1.jar
AnimationAPI-1.7.2-1.2.1.jar
AOBD-2.0.2.jar
appliedenergistics2-rv0-beta-30.jar
Aroma1997Core-1.7.2-1.0.2.4.jar
AromaBackup-1.7.2-0.0.0.2.jar
ATV_1.7.2.jar
BiblioCraft[1.7.1][MC1.7.2].jar
BiomesOPlenty-1.7.2-2.0.1.887-universal.jar
Botania r1.0-57.jar
Carpenter's Blocks v3.1.6 - MC 1.7+.zip
Chisel-1.7.2-1.5.4f.jar
CodeChickenCore-1.7.2-1.0.0-universal.jar
ComputerCraft1.64pr2.jar
DecoCraft1.7.2V1.9b.zip
DungeonPack-1.7.2-2.0.jar
DynamicLights-1.7.2.jar
EnchantingPlus-1.7.2-2.0.3.1.jar
Enchiridion-1.7.2-1.1a.jar
enderio-1.1.0_alpha.110.jar
EnhancedPortals_1.7.2-universal-3.0.0b-final2.jar
ExtraCells-2.0.17.jar
extrautilities-1.1.0b.jar
FinderCompass-1.7.2.jar
forestry_1.7.2-2.4.1.25.jar
HardcoreEnderExpansion.jar
HQM-3.3.1 for 1.7.2 Alpha 3.jar
IguanaTweaks-1.7.2-Beta-12.jar
InfernalMobs-1.7.2.jar
InventoryTweaks-1.57-116.jar
Jabba_1.1.3_1.7.2.jar
Java7Checker.jar
JustAnotherSpawner-0.14.5.jar
Light Bridges and Doors V 2.0.zip
LunatriusCore-1.7.2-1.0.2.7-universal.jar
Mantle-1.7.2-0.2.8.jar
Mariculture-1.7.2-b11.omfg.wtfbbq.jar
MCA-4.0.4 MC-1.7.2.zip
meteors-1.7.2-2.12.jar
MobiusCore-1.2.2_1.7.2.jar
mods.txt
modular-furnace-3.0.jar
morpheus-1.7.2-1.4.3.jar
MultiPageChest-1.3.1-MC1.7.2.jar
MutantCreatures-1.7.2-1.4.5.jar
mystcraft-1.7.2-0.10.15.00.jar
natura-1.7.2-2.2.0a3.jar
neiaddons-mc172-1.11.0.3.jar
NetherDungeons-1.7.2-v-1.2.1.jar
NotEnoughItems-1.7.2-1.0.1-universal.jar
OpenComputers-MC1.7.2-1.2.12.144-universal.jar
OpenEye-0.5-1.7.2.jar
Opis-1.2.2_1.7.2.jar
OreDictionaryConverter-1.5.1.jar
Pam's HarvestCraft 1.7.2e.zip
ProgressiveAutomation-1.7.2-1.2.0.jar
RadixCore-1.2.0 MC-1.7.2.zip
Railcraft_1.7.2-9.0.0.0.jar
RandomThings-2.0.33.jar
Schematica-1.7.2-1.6.1.76-universal.jar
supercraftingframe-1.7.2.6.jar
TConstruct-1.7.2-1.6.0.a14.jar
Thaumcraft-1.7.2-4.1.1.14.jar
ThaumcraftMobAspects-1.7.2-Beta-2.jar
ThaumicTinkerer-2.4-147.jar
TiCTooltips-mc1.7.2-1.1.6.jar
TMechworks-1.7.2-0.2.7.jar
twilightforest-1.7.2-2.1.1.jar
UpdateCheckerMod-1.7.2.jar
VillageTaverns-2.2.1-0.23.jar
voxelmap-1.7.2-1.0.jar
Waila-1.5.2a_1.7.2.jar
warp-book-1.7.2-1.0.35.jar
ZZZZZCustomConfigs v1.3.0.jar
[1-7-2]_Lucky_Block_v5-0-0.jar
[1.7.2-10.12.1.1098][2.2.7] AIRI.jar
[1.7.2-10.12.1.1098][3.9.D] AliensVsPredator.jar
[1.7.2]ArmorStatusHUD-client-1.26.jar
[1.7.2]StatusEffectHUD-client-1.25.jar
[1.7.2]UltimateTools - Universal by Umbrere[1.12.1.0].jar

**Comment by rwtema** [comment]
Presumably some mod is overriding the way mobs spawn and replacing it with a custom method. Nothing I can do about it.
