### ISSUE TITLE
[1.10.2] Why does cursed earth not affect mob spawners anymore?

### ISSUE THREAD

**Issue by DrZed** [rwtema/extrautilities_old_issues#1301]
The main reason I liked and used cursed earth is gone now, any plans to bring it back? Placing it under spawners made them spawn mobs without player nearby in 1.7.10.

**Comment by Gajitz** [comment]
There is a new way of doing this in Extra Utilities now you right click a vanilla spawner with a drop of evil and you will get an awesome surprise.

**Comment by DrZed** [comment]
Well then, that's new.

**Comment by DrZed** [comment]
Love it, op af, but I love it. 20 speed upgrades and it kills my fps (with blazes) gonna take a guess on how to change the mob... Lasso.
