### ISSUE TITLE
Railcraft/Forestry machines do not use power out of generators

### ISSUE THREAD

**Issue by Cirrus0** [rwtema/extrautilities_old_issues#131]
When you place a generator next to a machine from the mentioned mods it does provide infinite power to the machines, because the power storage in the generator is never deminished.

Version 1.1.0b

**Comment by rwtema** [comment]
Does it happen with Buildcraft machines (like the quarry)?

**Comment by CruaverVoidDrake** [comment]
Did you put a creative upgrade on the energy transfer?

**Comment by Cirrus0** [comment]
@CruaverVoidDrake No energy transfer node involved, just the machines right besides the generator (tested to work/fail with survivalists generator->powering a Railcraft rockcrusher at full speed without losing power, even while not running)

@rwtema As far as i can see/evaluate the buildcraft machines are working und draining as intended.
The problem seems to be with Railcraft and Forestry machines.

**Comment by Kasran** [comment]
I can confirm this happens with me too. Here's my post on the subject: http://www.minecraftforum.net/topic/1776056-16417forge-extra-utilities-v110b/page__st__2200#entry32322851

There are no upgrades of any kind on any of the machines, conduits or generators.

**Comment by rwtema** [comment]
Probably an API incompatibility issue or something, which should be fixed when they're updated.
