### ISSUE TITLE
What's Opinium Core?

### ISSUE THREAD

**Issue by Polyana-Fontes** [rwtema/extrautilities_old_issues#1319]
I couldn't find any information about it, the manual also doesn't mentions it. What is it? What does it do and how do I make it work?

**Comment by ate0ate** [comment]
Whoops, I messed up that post. Opinium is used to make the Kikoku.

**Comment by ate0ate** [comment]
Its really really grindy to get the materials required to actually make the Kikoku with it.
Here's a good video about it too, shows it off somewhat...
https://www.youtube.com/watch?v=OtEKtWrqMfc

**Comment by Polyana-Fontes** [comment]
Yes, what does it does? Is there any information about it somewhere? That floating blocks looks so interesting xD

Edit:
Thank you, I'm going to watch the video.

**Comment by ate0ate** [comment]
The models are pretty cool indeed. Are you noticing the dupe bug with it that I had in issue #1309? I was wondering if anyone else was experiencing this at all or if I have some mod conflict issue causing it. Get a stack of 3 or more of any opinium variant, place one, break it, profit.

**Comment by Polyana-Fontes** [comment]
Lol, yeah, that happened.
