### ISSUE TITLE
Builder's Wand misplaces slabs

### ISSUE THREAD

**Issue by no-identd** [rwtema/extrautilities_old_issues#133]
If I place a slab it the upside of a block instead of at the downside and use the builders wand on it, the subsequently placed slabs are placed at the downside of the block anyway.

Repro: Place a row of slab that are on the upper half of the block outline, use the builders wand on it, the newly placed slabs are located at the lower half of the block outline.

**Comment by rwtema** [comment]
Fixed, now the block will place at the same sub-position as when you right clicked (in other words top-half of the block vs bottom half of the block). This enables bottom half-slabs to be placed.
