### ISSUE TITLE
Crash while looking through JEI

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [rwtema/extrautilities_old_issues#1348]
I'm not sure if this is on your end or not, but I see you pop up a lot in the crash log.

http://pastebin.com/38wrgJGp

**Comment by Hjaldar** [comment]
Another dupe of #1320

**Comment by awkwaRdcaRRot** [comment]
Oh sorry, I didn't have time to browse the issues before posting. I'll go ahead and close this one.
