### ISSUE TITLE
[1.7.2] Feather does not appear. (AnimatedPlayer Introduction)

### ISSUE THREAD

**Issue by BlackYamato** [rwtema/extrautilities_old_issues#135]
---- Client Environment ----
・Minecraft 1.7.2
・Minecraft Forge 10.12.2.1126
・Extra Utilities 1.1.0b
・AnimationAPI 1.2.1
・AnimatedPlayer 1.4.1

I can not see the feathers that appear when I was with the Angel Ring.
Can fix it?

**Comment by rwtema** [comment]
Not really. If it's overriding the default player renderer the wings will not render. It's is a safety feature to prevent crashes.
