### ISSUE TITLE
All GP is the same for all EU2 items

### ISSUE THREAD

**Issue by EBro912** [rwtema/extrautilities_old_issues#1356]
Issue: In singleplayer, all items from Extra Utilities 2 will share the same GP no matter what they are. For example, an angel ring will have the same GP as a Transfer Node. Breaking Extra Utils blocks reduces the GP, and placing them raises it by 1.
Speculation: The blocks and items do not register for some reason.

Versions:
Pack: FTB Presents SkyFactory 3 Version 3.0.8
Minecraft: 1.10.2
ExtraUtils2: 1.3.0

**Comment by xenxero1** [comment]
The way you describe it makes me think you didn't look at how GP works...

**Comment by EBro912** [comment]
No I know how it works, its just in the item tool tips it shows the wrong amount of GP and it acts that way too (Like how an angel ring should be amount/40 but it is listed as 0/0 even though I have water generators)

**Comment by xenxero1** [comment]
Ah I see, that is quite interesting... Well, the amount/amount displayed is supposed to be 'gp being used/gp available". As for the 0/0 I'm not really sure, Your water mills have flowing water next to them correct? Falling water and source blocks generate 0 gp.

**Comment by EBro912** [comment]
Yes they all have flowing water running into them. This all started when I shut down my computer by accident with the game running so I don't know if that means anything; but before that everything was working perfectly fine and the GP displayed correctly

**Comment by xenxero1** [comment]
Very odd. I'll leave this one to @rwtema

**Comment by EBro912** [comment]
I think I figured it out! I deleted the Extra Utils .dat file in the data folder and everything went back to normal! Thank you for the help.
