### ISSUE TITLE
[1.10.2-Beyond] Ender Pearl/Vial recipe

### ISSUE THREAD

**Issue by Ravix-** [rwtema/extrautilities_old_issues#1378]
If you craft two Ender Pearls with a vial according to one of the recipes shown on JEI and use it on a block it was crash your server and render it corrupt.

Not sure what the item ID is or what this item was supposed to be for, but it's no bueno. :(

**Comment by xenxero1** [comment]
It's supposed to be a Klein Flask, this issue has already been reported.
