### ISSUE TITLE
Quantum Quarry Crash

### ISSUE THREAD

**Issue by ukdyl94** [rwtema/extrautilities_old_issues#1379]
Crash 1 - [http://pastebin.com/mRq25M9M](url)
Crash 2 - [http://pastebin.com/ArAJLZSJ](url)

This crash happens any time I try and connect a power source to the quarry. I feel as if it originally happened when the chest that was connected the Quarry got full; when loading in the chunk it crashed the server.

**Comment by ukdyl94** [comment]
The issue was resolved by clearing out the player data? Idk. lol

**Comment by marvinwz** [comment]
I think I have fixed this issue by removing Mo creatures and CustomMobSpawner. I think CustomMobSpawner caused an error which lead to the silver fish spawning in the first place.
