### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by inochi** [rwtema/extrautilities_old_issues#138]
When generators fill their internal rf storage tanks, they cause massive framerate lag. with 12 generators i normally experience 2 fps from 60. Version 1.1.0b

**Comment by rwtema** [comment]
Unable to reproduce and I see no reason for their to be framerate lag. Is something spamming the console?

**Comment by inochi** [comment]
No,  nothing spams the console. I was using roughly 1200 rf/t at one point and the generators internal buffer remained empty. When I stopped using power and the buffers filled,  my frame rate steadily dropped from 60 to 2-3. Had a friend warp to me and his frames dropped to nothing as well. After ripping my base apart, we were able to reproduce it with lava gens and the Redstone gen. When I get off work I'll see what I can do about getting a video or something.

**Comment by rwtema** [comment]
Unable to replicate. Unless you have more info, I can't help you.
