### ISSUE TITLE
[1.11.2-1.3.3] drum duplicate glith/bucket bug

### ISSUE THREAD

**Issue by oOBoomberOo** [rwtema/extrautilities_old_issues#1395]
put liquid in every drum not consume liquid and when use bucket consume liquid but not get liquid

**Comment by falkreon** [comment]
Confirmed. ItemStacks are immutable in 1.11.2 - this was a big change from 1.10, and it's making a *lot* of fluid containers dupe liquids. As a side effect, you should also be able to rightclick on a full drum with an empty bucket and just keep erasing liquids.

**Comment by oOBoomberOo** [comment]
thank for answer, i might have to play 1.10 agian
