### ISSUE TITLE
Red Coal burn time inconsistent

### ISSUE THREAD

**Issue by Nahkranoth0** [rwtema/extrautilities_old_issues#1406]
Extra Utilities v1.33(DW20 modpack 1.8.1)

I'm using red coal to feed a botania mana farm with endoflames, In the tooltip it states 12800 ticks (640 seconds or 10m44s). The endoflames are out of mana after 6400 ticks, half the time it is on the tooltip.

Could you please check it out?

**Comment by xenxero1** [comment]
Its possible that the modpack author reduced the burn-time of red-coal on endoflames due to balance concerns. Direwolf20 said somewhat recently on his survival series that he feels red coal is overpowered with Endoflames. Just a possible explanation, might not be a bug.

**Comment by Nahkranoth0** [comment]
Ok, thanks a lot for pointing that out, Didn't think that would be deliberate from the mod author, but yes it's extremely plausible.
