### ISSUE TITLE
Request by FoolCraft DevTeam

### ISSUE THREAD

**Issue by Jo-Mamma75** [rwtema/extrautilities_old_issues#1417]
This would be considered a duplicate issue by several others posted on this Github but I am making the request on behalf of the Fools (Iskall85, BDoubleO100, GoodTimeWithScar, etc.) as I am part of the FoolCraft DevTeam.
As others have stated, if using the Mechanical User in Entity mode and it attempts to right-click a player with a bucket, the server crashes and cannot be recovered without moving the player's location by editing their player.dat file or editing the world to remove the Mechanical User.
As such, we have had to remove the block via the config file for the FoolCraft pack and have included another mod as an alternative for milking cows and harvesting crops from Agricraft.
My request is if you cannot resolve the issue very easily (due to focus on other projects) would it at least be possible to remove that particular mode from the Mechanical User in an update to help us and a lot of other people out?
Thank you for taking the time to read this and I hope to see an update soon.

Jo_Mamma75
Iskall85 Community Manager
FoolCraft DevTeam

**Comment by janf3** [comment]
I'm also playing the FoolCraft pack in SSP so I've been looking into this too.
Unfortunately this does not appear to be an XU2 issue. The crash doesn't happen in a clean instance or e.g. in the DW20 pack.

//update
caused by Minecraft Comes Alive (MCA-1.10.2-5.2.3-universal)

**Comment by Jo-Mamma75** [comment]
Yeah, just tested this in the latest dev version of FoolCraft.  Disabled MCA and the Mech User works just fine.  Thought it had to do with the way MCA handles right-clicking on a player and opens the GUI for marriage but changed that to require a shift-right-click via the config but no change.

    # True if you must hold shift then right click a player to open the marriage menu. Useful on PvP servers.
    B:"Shift-click for player marriage menu"=true

That particular mod has caused some issues on one of our Patron servers and we actually had to disable it due to it constantly crashing.  I will be contacting the mod author of MCA and see if he can address some of the issues with his mod.

Thank you janf3 for pointing me in that direction.
