### ISSUE TITLE
Ender Cores don't give extra ender-lily seeds?

### ISSUE THREAD

**Issue by ericBG** [rwtema/extrautilities_old_issues#144]
Someone on [reddit](http://www.reddit.com/r/feedthebeast/comments/29bjsb/as_extrautilities_enderlilies_explained/) has dug into the code, and found out that ender-lilies will NOT give extra seeds when planted on Ender Cores. I have also noticed this anecdotally.

This MAY be intended, in which case I apologize.

**Comment by rwtema** [comment]
In 1.6.4, they don't. They do in 1.7.
