### ISSUE TITLE
[1.7.2] [Forge 1147] Extra Utils 1.1.0b Cursed Earth

### ISSUE THREAD

**Issue by B4D2J0** [rwtema/extrautilities_old_issues#145]
Cursed earth seems to not work as expected. I am running a set of mods inspired mostly by what I see on forgecraft and have not added much if anything that is not also on that server.

Everything works as it should when the cursed earth is in a player loaded chunk but if a chunk is not player loaded then they stop spawning mobs. Railcraft anchors, enderthermic pumps, even chunks loaded by enderquarries do not seem to keep them spawning. Once the player loads a chunk though it begins to work as it should again. Not sure if this is an issue with the current chunk loading mechanics or if, as you said in an answered post, there is something overwriting the spawning code of yours. Maybe I am misunderstanding the intent of the block but it says it spawns regardless of player proximity, and does so as long as it is in a player loaded, not just force loaded chunk.

**Comment by inochi** [comment]
Cursed earth follows mob spawner rules. It has to be loaded by a player.

**Comment by B4D2J0** [comment]
Are you sure? I have been using cursed earth as a way to keep my blood magic LP network full on a sparsely populated server while i was offline. It was working before this latest version so something has changed. I can slide back a version and retest if you like though.

**Comment by rwtema** [comment]
inochi: Cursed earth does not have to be loaded by a player.

I can't replicate the issue you've been having and unless you have more info, I'm afraid I can't help.
