### ISSUE TITLE
Crash with Extra planets and Extra Utilies

### ISSUE THREAD

**Issue by McyD** [rwtema/extrautilities_old_issues#1457]
Extra Planets author blames this on you, but all I see is that extra planets is calling for client side rendering.  States that and ender quarry is trying to mine a Launch Pad, however we only have two quarries in a mining age, and no one on the server has built a launch pad, not that someone would build one in a mining age anyway.

https://pastebin.com/Sjtwa2Uh

**Comment by McyD** [comment]
Seems the author fixed his issue.

**Comment by mainrs** [comment]
@McyD I tested the fixed version of him and it still crashed on me.
