### ISSUE TITLE
redcoal from 2 separate resonators placed by 2 people won't go into same storage drawer

### ISSUE THREAD

**Issue by DoomSquirter** [rwtema/extrautilities_old_issues#1467]
does it perhaps store some NBT about who's resonator made it, thus they are not the same item?  Is this intended behavior and if so, why?

**Comment by DoomSquirter** [comment]
whoops:  extrautils2-1.10.2-1.3.3

**Comment by TeetoKaziim** [comment]
It's probably intended behaviour because the Red Coal uses the GP network size of the person who made it to determine the amount of bonus "burn time" it grants. It probably remembers this using NBT data, making it nonstacking with other players' stuff.

**Comment by DoomSquirter** [comment]
hey that's neat.  I didn't know you get bonus burn time from red coal.  That would actually explain the nbt then fully.  thx for the info.
