### ISSUE TITLE
Not an issue, more suggestion

### ISSUE THREAD

**Issue by goobdude** [rwtema/extrautilities_old_issues#147]
So I apologize if this isn't the place to do this, but I wanted to bring up a thought you may have already had.

Could there be a way to mix ethereal glass and dark glass into a new block? Both of these work tremendously well for mob farms, and a mixture of the two would be very useful. Perhaps something that is needed to combine with Ethereal Glass and tint it, from the Deep Dark, found only in Ziggurats? Just a thought.

And I apologize again if I'm in the wrong place/missed something regarding suggestions.

**Comment by rwtema** [comment]
Sorry but this place is really for issues and not suggestions. I generally do not take suggestions as a rule.
