### ISSUE TITLE
Quarry Mining Issue - Beyond

### ISSUE THREAD

**Issue by Keaton1188** [rwtema/extrautilities_old_issues#1478]
Hi all, recently quarries were fixed and all is working fine, except the main thing really.
The quarry only mines Cobblestone and Dirt.. and nothing else, if you put a filter upgrade on it, it just continues to mine blocks but not give anything but cobble or dirt.

This is happening on our Beyond server, not tested any other yet.

NOTE - Have tried removing the ExtraUtils2 folder in config/sponge - Didn't help
Deleted the DIM folder from 'worlds' and that did not help either.

Someone suggested that it was a Biome issue, on the Quarry it said it was in Jungle Biome..
![2017-05-11_23 41 34](https://cloud.githubusercontent.com/assets/24898745/26018583/9e3d0e2a-3767-11e7-837f-f93fe0b9d079.png)

**Comment by ktole1999** [comment]
update sponge. this was supposedly fixed.

**Comment by Keaton1188** [comment]
Nope, the sponge update fixed crashes and other issues.

Am on:
Minecraft: 1.10.2
SpongeAPI: 5.2.0-SNAPSHOT-a26c654
SpongeForge: 1.10.2-2281-5.2.0-BETA-2330

So its an issue with the mod.
