### ISSUE TITLE
Issues with Server install of Extra Utilities and EE3 on server boot up

### ISSUE THREAD

**Issue by Elasky** [rwtema/extrautilities_old_issues#149]
Hope you can help not sure what is happening here...
Good Day, Having an issue with a server build running both EE3 and extra utilities at the same time. When I do I end up getting this crash log http://pastebin.com/e0FQ21u8 but on a client startup it loads fine and can play an ssp world no problem. Now with either EE3 or extra utilities not loaded the server seems to come up fine. It looks like an EE3 error but not sure. Both the client and the server are on forge 1147 and tried with 230 to 233 ee3 versions to see if the error would stop.

**Comment by rwtema** [comment]
EE3 bug. EE3 is calling client-side exclusive code in their getUnlocalizedName() method.

https://github.com/pahimar/Equivalent-Exchange-3/blob/master/src/main/java/com/pahimar/ee3/block/BlockEE.java#L37
