### ISSUE TITLE
Generators are far, far, far too powerful

### ISSUE THREAD

**Issue by keenerb** [rwtema/extrautilities_old_issues#15]
I can smelt an entire stack of ore with three planks using a survivalist generator?  And an ender pearl is an absolutely absurd amount of power.  Also, the 500k RF storage is way too much, considering a leadstone energy cell only holds 400k and requires lead, redstone dust, etc. etc. etc.

You've done a great job on keeping a nice balanced mod with the etheric tools, it seems a shame that so many people are disabling generators because they're overpowered.

Please consider A) removing the internal power buffer and B) adding individual config options for each generator.

Thanks!

**Comment by ghost** [comment]
I'd very much like a lower internal buffer, was a bit of a surprise when I saw how high the cap was. Configurations for each generator would be nice too. I don't think there's actually a config option for disabling generator recipes, only their ID unlike most of the other items/blocks.

I'd also like to see a max size on ender quarries, not sure if you received my PM. But that's not related to this issue. ^^

**Comment by ate0ate** [comment]
Personally, I Like the generators just the way they are. I play using Mekanism and Thermal Expansion and for me they fit right in as starter level generators. Half a million RF is nothing when you move up to higher tiers and nerfing the generators would make them unnecessary. There needs to be an incentive to use them or there's no reason to use anything but vanilla TE dynamos. I think that the mix of mods you use makes a huge difference too. With certain modpacks there's really no need for anything over a half million RF, but for other packs that just isn't anywhere near enough. That being said, everyone has their own way of playing so more options sure couldn't hurt. I see no harm that could come from adding config options to tweak the generators. Just throwing my opinion out here.

**Comment by rwtema** [comment]
Not a bug. This tracker is for bugs only.

**Comment by ghost** [comment]
How would you like us to contact you? I've been unable to get a  response through attempts on IRC/MCF. ^^

**Comment by keenerb** [comment]
Sorry, the forum post said to report bugs and issues here, and I felt this was an issue.

I'll stick it in the forum thread I guess.
