### ISSUE TITLE
Ender Quarry dislike Charged Certus Quartz

### ISSUE THREAD

**Issue by idealjo** [rwtema/extrautilities_old_issues#150]
Ender quarry break the Charged Certus Quartz block but does not get the quartz, it is dropped on the floor.
only with the charged one not the regular.

appliedenergistics2-rv0-stable-7
extrautilities-1.1.0b
forge 1147

**Comment by rwtema** [comment]
Acknowledged. AE2 has a custom entity for its charged quartz drops. Luckily its a simple extension of the basic item entity, so I can easily check for it.

Will be fixed in the next version.

**Comment by rwtema** [comment]
Just as a quick clarification - this is not an AE2 issue.
