### ISSUE TITLE
1.7.2 Not compatible with optifine 

### ISSUE THREAD

**Issue by sudohacker** [rwtema/extrautilities_old_issues#151]
If I load the mod no matter the version of forge by itself everything is fine. Everything works fine with many other mods installed.  I made a fresh minecraft install and added latest forge and started a world everything is fine.  Added Optifine 1.7.2 hd d1 all colored blocks compact blocks and generators have missing textures.  Tried earliest version of optifine hd a6 tried the ultras for 1.7.2 and tried optifine for 1.7.4 which wouldn't run anything at all anyway.  So I have tired to use extra utilities all three stable versions and the generator, compact blocks, and colored blocks lose their textures if any working version of optifine is installed.  Thinking it has to do with mcpatcher not being able to find the blocks with metadata.  Not really sure though.  All other textures are fine.  All blocks function normaly

**Comment by CruaverVoidDrake** [comment]
Optifine at 1.7.2 is not compatible with Extrautilities.

**Comment by rwtema** [comment]
This is exclusively an optifine issue. Custom texture loading changed from 1.6.4 to 1.7 and they haven't updated it.

Also please check to see if an issue has been brought up before.
