### ISSUE TITLE
[1.11.2-1.4.2] Server Crash

### ISSUE THREAD

**Issue by Endmateria** [rwtema/extrautilities_old_issues#1515]
I just updated from EU 1.4.1 to 1.4.2 and it's now crashing the server... https://gist.github.com/Endmateria/a43cef540b75a9013fe11b074a1bbae6

MC 1.11.2
Forge 2313
EU 1.4.2

**Comment by MobiusMOAB** [comment]
Wanted to 1-Up this.
https://gist.github.com/MobiusMOAB/691a8b6d10d505bab2896f48b506e0a7#file-crash-2017-06-05_17-11-42-server-txt

MC Server 1.10.2
Forge 12.18.3.2297
EU 1.4.2 (via Curse/FTB Client)
