### ISSUE TITLE
magnum torch not working

### ISSUE THREAD

**Issue by bdudek** [rwtema/extrautilities_old_issues#152]
i placed a magnum torch down then started on the floor of my basement and mobs were still spawning. i beleave this is a bug unless the magnum torch was changed in the 1.7  version 1.1.0b

![2014-07-02_22 36 21](https://cloud.githubusercontent.com/assets/8053683/3465009/dbf047b2-025b-11e4-8811-dc6f43c32e22.png)

**Comment by bdudek** [comment]
after a server reboot the magnum torch started to work and no mobs are spawning now

**Comment by luchokoldo** [comment]
yep.. that happen to me... you need place, remove and place again
