### ISSUE TITLE
[1.10.2 - 1.4.4] - Unable to fly with angel ring

### ISSUE THREAD

**Issue by Protheus** [rwtema/extrautilities_old_issues#1529]
MC: 1.10.2
ExU2: 1.4.4

**Issues**: 
- After update i'm unable to fly with the angel ring. I have 320 GP.
- When downgrading to 1.4.3, the issue stays

I removed the XU2SaveData.dat in the save location and restarted MC with 1.4.4 and still unable to fly with an angel ring.

Attached screenshot:
![2017-06-12_18 40 11](https://user-images.githubusercontent.com/1455178/27045262-9e7aadc4-4fa0-11e7-917c-25c31727ff53.png)
![2017-06-12_18 54 11](https://user-images.githubusercontent.com/1455178/27045263-9e7d2e96-4fa0-11e7-9ccc-b42f890ea192.png)

**Comment by Protheus** [comment]
Started a new world:
- Still unable to fly, even with a dragon egg (see screenshot)
- But dropping from high, I do not get fall damage !... so the ring is working for fall damage but unable to let me fly

![capture](https://user-images.githubusercontent.com/1455178/27148283-f9d4b764-513f-11e7-88b8-3edbee38cb17.PNG)

**Comment by nathanswanson** [comment]
I'm on 1.4.1 and I'm having this issue as well

**Comment by Protheus** [comment]
The issue is caused bij: 

- Avaritia 2.2.4, go back to 2.1.2.1 and all is working again
