### ISSUE TITLE
Crash when opening trading post

### ISSUE THREAD

**Issue by ExpiredMinotaur** [rwtema/extrautilities_old_issues#153]
http://openeye.openmods.info/crashes/314fd5d530d5271604e390f047aab79b

**Comment by TheWhoAreYouPerson** [comment]
Also note, you get a 'Internal Server Error' when trying this on a server. Client doesn't log anything related to it. The server spits http://pastebin.com/6TwQK3MH to the log. Tell me if you need anything else from me.

**Comment by rwtema** [comment]
What version of Java are you using?

**Comment by ExpiredMinotaur** [comment]
I am using 1.7.0_60

**Comment by TheWhoAreYouPerson** [comment]
I am using Java 8, update 5

**Comment by rwtema** [comment]
Should be fixed in next version (1.1.0c).
