### ISSUE TITLE
[1.10.2] SkyFactory3 RF heating coil not working

### ISSUE THREAD

**Issue by samox73** [rwtema/extrautilities_old_issues#1533]
When put inside a valide machine, the wireless rf heating coil does nothing. When closing the gui it jumps back into the users inventory. I checked the config but can't see why it shouldn't work. When I played SF3 6 months ago it worked perfectly.

**Comment by xenxero1** [comment]
I believe you need to right-click to bind it to you first, like a Blood Magic Lava Crystal. Incase someone stumbles upon this.
