### ISSUE TITLE
Can't enter the deep dark? (1.10)

### ISSUE THREAD

**Issue by warplord** [rwtema/extrautilities_old_issues#1570]
I had a portal to the deep dark made before I updated to the latest version, then after I updated - I stand on the portal and nothing happens. Screen doesn't start shaking and I don't get teleported? Is there something different about the way you enter the deep dark ? 
Is anyone else experienceing similar problems?

**Comment by warplord** [comment]
Tested in a different pack - just updated only EU to 1.5 - still can't use it. Also the WAILA tooltip says "overworld" portal. don't know if that helps - but there seems to be some issue with it.

**Comment by DaniloNocete** [comment]
I have the same issue

**Comment by gaillA** [comment]
Same issue for me

**Comment by warplord** [comment]
Anything new for this issue? I saw a new release but there was no mention of the Deep Dark portal ? Let's try it and see.

::
I tried and it works now. Thanks for the fix!
::
