### ISSUE TITLE
[1.12] Angelring cannot fly

### ISSUE THREAD

**Issue by Symbai** [rwtema/extrautilities_old_issues#1573]
I've put an angelring into my inventory. Pressed jump key twice, I noticed a effect that doesn't appear without angel ring, feels like a small boost jump, but I'm still falling to the ground. However I am no longer taking fall damage.. its just that fly doesn't work.

Have I missed something? I'm playing survival singleplayer...

**Comment by xenxero1** [comment]
Do you have sufficient open GP to fuel it?

**Comment by Symbai** [comment]
No, all guides I found online says I don't need any GP/power just put it in my inventory... so I assume they are outdated? Is there any official wiki for Extra Utilities? The forum thread only shows what items exist but don't explain them.

**Comment by xenxero1** [comment]
You are likely looking at the old guides, If you mouse over the ring in the current version there is a tooltip that says it needs 32gp sustained to fly. Not hard to setup, just do some watermills and youl be set.

**Comment by Symbai** [comment]
A wiki would be a really great addition, especially for new users like me.
