### ISSUE TITLE
 crashed when right-clicking full-sized beacon with creative builder's wand

### ISSUE THREAD

**Issue by smb64** [rwtema/extrautilities_old_issues#158]
only seems to happen with full-sized (tier with regeneration) beacons, have yet to test in survival or with normal builder's wand
http://paste.ee/p/chmVx

**Comment by rwtema** [comment]
Unable to replicate.

Looking at the crash log this looks to be a reflection error, caused by some mod messing with the beacon GUI improperly.

Does this happen with other items?
Were you shift-right-clicking?

**Comment by smb64** [comment]
I was not shift-right-clicking, nor does it happen with other items...
it only happens with a full-sized beacon...

On 7/6/14, RWTema notifications@github.com wrote:

> Unable to replicate.
> 
> Looking at the crash log this looks to be a reflection error, caused by some
> mod messing with the beacon GUI improperly.
> 
> Does this happen with other items?
> Were you shift-right-clicking?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rwtema/extrautilities/issues/158#issuecomment-48125825

## 

If you have a 3DS, please send me your Friend Code. My Friend Code
is 1375-7724-1401
If you have a Wii, please send me your Friend Code. My Friend Code
is 5887-5627-9203-3869
If you have Skype, please send me your username. My username is smb64ds

**Comment by rwtema** [comment]
Still unable to replicate, Probably not an issue with Extra Utilities.
