### ISSUE TITLE
Request: Router Upgrade

### ISSUE THREAD

**Issue by TheWhoAreYouPerson** [rwtema/extrautilities_old_issues#159]
I think it would be awesome if there was an upgrade to Transfer Nodes to allow for a mechanic similar to Factorization's Router block. This would allow for easier automation of all the things.
Like for example, if placed in an Energy Transfer Node, it would allow for a whole row of machines to be powered as long as they are connected. Or in an Item Transfer Node it would allow for fuel to be placed in a row of furnaces if placed on the bottom of one.
To solve the eyesidedness issue, I would recommend to try to push/pull on the side that the side that the original pipe is on. (As in, if the pipe connected to one machine is on the top, it would act as if the pipe is connected to all the other machines on the top)

Of course this would have to be really expensive because of how useful this is >:D
I understand if this would be too complicated to implement though :(

**Comment by rwtema** [comment]
I've thought about this and while it would be fun, the system doesn't really support it naturally and would be too much of a hack to put in.
