### ISSUE TITLE
[1.12] solar panels not producing GP

### ISSUE THREAD

**Issue by mrtopf** [rwtema/extrautilities_old_issues#1592]
I tested it with extra utils alone and the blue solar panels seem not to produce any GP. All the other generators seem to work though.  (also the ones to use at night).

![image](https://user-images.githubusercontent.com/5818/28313099-da76b6e8-6bb5-11e7-8a93-cc07c0d208f7.png)

**Comment by tristanhollman** [comment]
We just updated our server (Resonant Rise 4) which now uses the new version of Extra Utilities (1.5 - 1.10.2).
I can confirm that solar panels no longer seem to generate GP, lunar panels still work tho...

But this is on the 1.10.2 version

**Comment by marikc0** [comment]
I'm experiencing the same issue with 1.5 in 1.12 MC.

**Comment by DV666** [comment]
Report by players on my server too (1.10.2 and XU last version so 1.5)

**Comment by xenxero1** [comment]
Question (Since i'm not having this issue); would this block all ExU2 progression if it hasnt already been started? Afaik solar panels are the first piece you need, to fuel a resonator, to get better GP sources ~(Lunar panels aside)~. If so, should probably tag this Critical and push a hotfix asap.

**Comment by mrtopf** [comment]
you can use a manual mill or whatever it's called or the lunar panels. And with that you should be able to craft better ones if I am not mistaken.

**Comment by mrtopf** [comment]
works now in 1.5.1, thanks for fixing! :-)
