### ISSUE TITLE
Energy transfer nodes and pipes do not work with RotaryCraft magnetostatic engines.

### ISSUE THREAD

**Issue by jlp1528** [rwtema/extrautilities_old_issues#16]
I told Reika about this, but he said it was on your end. Strangely enough, they do connect, but they don't give them any power. Please add support for them.

**Comment by rwtema** [comment]
I'm afraid I don't see any reason on my end why it wouldn't work and I'm not aware of any other RF compatible machines have this problem. My only thought would be to put a pipe between the node and the machine.
