### ISSUE TITLE
Dedicated server crash on launch

### ISSUE THREAD

**Issue by Igings** [rwtema/extrautilities_old_issues#161]
I am using Extra Utilities with a few other mods, and they loaded fine in singleplayer. After I loaded the mods onto my dedicated server, I got the following error from EU at server startup:
http://pastebin.com/MAXEB47r
I'm using EU version 1.1.0c with forge 10.13.0.1179

**Comment by rwtema** [comment]
Your server seem to be missing the scala library, which is a very serious installation error. Try reinstalling forge and If it doesn't include them, you may wish to report this to FML.
