### ISSUE TITLE
[1.11.2] potential filter bug

### ISSUE THREAD

**Issue by Diamond45123** [rwtema/extrautilities_old_issues#1625]
Hey, i have been trying all day to figure it out, but obviously failed.. I don't if this is a bug or im being dumb..
So im trying to hook my quarry up to my pulverizer so it pulverizes it and then smelts it and then get it into the refined storage system.
but for some reason, the filter isnt working. if i put it into whitelist it takes everything... and blacklist does opposite.
my set up
http://imgur.com/a/ZHfhY everything is explained in the description of each image

**Comment by meelock** [comment]
Huh, mine doesn't even work! Came here to report my issue.

**Comment by Diamond45123** [comment]
Hey, i figured it out,   if you have buildcraft. Use lists so you can use ore dictionary

**Comment by Diamond45123** [comment]
And then use diamond pipes to filter them out

**Comment by meelock** [comment]
It may have to do with the item pumps requiring grid power...

**Comment by Diamond45123** [comment]
No, i have wind mills and solar panels
