### ISSUE TITLE
Magnum torches not preventing mobspawns in Extrautilies for 1.7 Forge V[10.13.0.1179] Possibly older aswell.

### ISSUE THREAD

**Issue by KillerRamer** [rwtema/extrautilities_old_issues#164]
Now during my 1.7.2 play I had a little nudge of doubt on magnum torches working and filtering out mobs... However I merely gave it a pass over and just wrote it off as being crazy...

However after today's update and wanting to make full use of cursed earths new mechanics I placed down a magnum torch and began counting the blocks away inwhich I saw mobspawns...

Then I turned it on to normal difficulty, and what do you know mobs spawned within three to four blocks around the torch...  http://imgur.com/S83mW9T

**Comment by rwtema** [comment]
Acknowledged. Will be fixed in next version. In mean time, unload and load the chunk to fix.

**Comment by KillerRamer** [comment]
Thank yah kindly good sir.
