### ISSUE TITLE
Portal to the Deep Dark recipe is broken

### ISSUE THREAD

**Issue by brian91292** [rwtema/extrautilities_old_issues#165]
I am using version 1.1.0b for Minecraft 1.7.2, and when I attempt to craft the portal to the deep dark it simply doesn't work. It acts as if I have entered an improper recipe, even though I've crafted it the same exact way it says to in NEI.

The first time I attempted to craft it I was too slow, the second time I got the items onto the table in time but was unable to craft it. Just to confirm I wasn't too slow, I tried in creative mode and the recipe doesn't work there either.

Not sure if you are even supporting 1.7.2 anymore, but if so this is definitely a big, annoying bug.

**Comment by rwtema** [comment]
Unable to replicate. The recipe works fine. Unless you can give me some more info, I can't help you.

**Comment by brian91292** [comment]
Just for the record, I decided to spawn in the portal and found on the other side a world filled with 100% smooth stone in all directions. That's all the information I have, there is no crash, the recipe simply does nothing.

**Comment by TherminatorX** [comment]
As for the world, try digging down.
