### ISSUE TITLE
Minecraft 1.12 server crash

### ISSUE THREAD

**Issue by Realever** [rwtema/extrautilities_old_issues#1650]
Hi
i have updatet to your new version 1.5.2 but my server crash on startup.My Client doesn´t crash.Here is the crash report: https://pastebin.com/w7xithPg

**Comment by WhiskersWatson** [comment]
I am also having this error on just my server and not my client.
https://pastebin.com/htwSqaCu

**Comment by Necavi** [comment]
Throwing my hat in here too, I'm having the same issue with Tinker's Construct v2.7.2.19 and Extra Utilities 2 1.5.2.

**Comment by craiven** [comment]
if you have crash the world with mechanical crafter. Delete the world files and upload from backup.

**Comment by p-schneider** [comment]
This is a duplicate of #1645

**Comment by Realever** [comment]
i didn´t see that.i close then my report
