### ISSUE TITLE
Crash: placing a barrel on bc golden fluid pipe

### ISSUE THREAD

**Issue by zpowerup** [rwtema/extrautilities_old_issues#166]
Crash log from placing a barrel with 300 mb of lava in it on top of a bc pipe
using buildcraft 6.0.16 and extra utilities  1.1.0b 
would be on the 1.7.10 version but my favorite mods are not on that version yet.
http://pastebin.com/ZbCHsYcE

**Comment by rwtema** [comment]
This looks to be an issue with the sound system. Something is accessing the sound system at the same time the barrel is placed. I've never seen this before and I've no idea what could be caused it. My only comment is that this is highly unlikely to be an Extra Utilities issue, merely triggered by it.
