### ISSUE TITLE
Cursed Earth Crashes World

### ISSUE THREAD

**Issue by james9023** [rwtema/extrautilities_old_issues#167]
Anytime a mob spawns on cursed earth it will crash the game. However when in Peaceful mode the game is fine.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 7/11/14 2:24 PM
Description: Exception ticking world

java.lang.NoSuchMethodError: net.minecraft.util.AxisAlignedBB.func_72332_a()Lnet/minecraft/util/AABBPool;
    at com.rwtema.extrautils.block.BlockCursedEarth.func_149674_a(BlockCursedEarth.java:181)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:403)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.rwtema.extrautils.block.BlockCursedEarth.func_149674_a(BlockCursedEarth.java:181)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:403)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)

-- Affected level --
Details:
    Level name: Test
    All players: 1 total; [EntityPlayerMP['James9023'/189, l='Test', x=-232.96, y=5.38, z=759.87]]
    Chunk stats: ServerChunkCache: 784 Drop: 0
    Level seed: -1149262775
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-57,4,634), Chunk: (at 7,0,10 in -4,39; contains blocks -64,0,624 to -49,255,639), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 447699 game time, 13397 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 4598 (now: false), thunder time: 6530 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.6.0_30, Sun Microsystems Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Sun Microsystems Inc.
    Memory: 221974392 bytes (211 MB) / 486670336 bytes (464 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.11.1179 Minecraft Forge 10.13.0.1179 7 mods loaded, 7 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.11.1179} [Forge Mod Loader](forge-1.7.10-10.13.0.1179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1179} [Minecraft Forge](forge-1.7.10-10.13.0.1179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.1.8} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['James9023'/189, l='Test', x=-232.96, y=5.38, z=759.87]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by AlexandraIsabel** [comment]
Update Extra Utilities to 1.1.0c and see if that fixes it

**Comment by james9023** [comment]
That fixed it. Thanks! Actually I downloaded 1.1.0c but forgot to put it in the mods folder. Thanks though!
