### ISSUE TITLE
mechanical crafter crashing my game

### ISSUE THREAD

**Issue by LocoMinerDad** [rwtema/extrautilities_old_issues#1675]
minecraft 1.12
extra utilities 2 v 1.6, 1.5.2, 1.5.1,1.5
I made the crafter tried to get it to compress cobblestone and the game crashed. I have tried the the mod versions and the game crashes while loading terran etc.

**Comment by Tahakk** [comment]
and how about crashlog? forge one preferably, then maybe somebody can help you

**Comment by LocoMinerDad** [comment]
Someone with the same issue already posted one but ok. Deleting your mod fixed the issue. I hope you can help.

thank you

---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12-1.6.1.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.7.0.jar)
  HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.1.jar)
  weatherconfig_coremod (WeatherConfig-1.12-1.0.1.jar)
  BCModPlugin (backpacks 1.12 - 3.3.2.jar)
  SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/29/17 4:31 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 9
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)

-- Block entity being ticked --
Details:
	Name: xu2:tilecrafter // com.rwtema.extrautils2.tile.TileCrafter
	Block type: ID #449 (tile.extrautils2:crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (243,73,647), Chunk: (at 3,4,7 in 15,40; contains blocks 240,0,640 to 255,255,655), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #449 (tile.extrautils2:crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: New Worldv rare 2
	All players: 1 total; [EntityPlayerMP['LocoMinerDad'/366, l='New Worldv rare 2', x=244.07, y=72.00, z=650.38]]
	Chunk stats: ServerChunkCache: 1155 Drop: 274
	Level seed: -6405502031902563945
	Level generator: ID 10 - lostcities_bop, ver 0. Features enabled: true
	Level generator options: { "profile": "rarecities" }
	Level spawn location: World: (179,64,199), Chunk: (at 3,4,7 in 11,12; contains blocks 176,0,192 to 191,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2259012 game time, 2372388 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 26838 (now: false), thunder time: 6231 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1433781040 bytes (1367 MB) / 3696230400 bytes (3525 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 94 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	infinimend{1.0.1} [Infinity & Mending Unnerf] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.3.2} [Backpacks!] (backpacks 1.12 - 3.3.2.jar) 
	UCHIJAAAA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.7 mc1.12.jar) 
	UCHIJAAAA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UCHIJAAAA	jei{4.7.8.92} [Just Enough Items] (jei_1.12.1-4.7.8.92.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.2.19} [Tinkers' Construct] (TConstruct-1.12-2.7.2.19.jar) 
	UCHIJAAAA	thedragonlib{1.12-4.1.0} [TheDragonLib] (thedragonlib-1.12-4.1.0.jar) 
	UCHIJAAAA	armorplus{1.12-11.5.1.16-alpha} [ArmorPlus] (armorplus-1.12-11.5.1.16-alpha.jar) 
	UCHIJAAAA	astralsorcery{1.6.1} [Astral Sorcery] (astralsorcery-1.12-1.6.1.jar) 
	UCHIJAAAA	base{3.0.0} [B.A.S.E] (base-1.12-3.0.0.jar) 
	UCHIJAAAA	bdlib{1.14.1.6} [BD Lib] (bdlib-1.14.1.6-mc1.12.jar) 
	UCHIJAAAA	betterthanmending{1.1.1} [Better Than Mending] (BetterThanMending-1.1.1.jar) 
	UCHIJAAAA	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	blockdrops{1.3.0} [Block Drops] (blockdrops-1.12-1.3.0.jar) 
	UCHIJAAAA	codechickenlib{3.1.2.297} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.2.297-universal.jar) 
	UCHIJAAAA	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHIJAAAA	brandonscore{2.3.2} [Brandon's Core] (BrandonsCore-1.12-2.3.2.129-universal.jar) 
	UCHIJAAAA	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHIJAAAA	chiselsandbits{14.6} [Chisels & Bits] (chiselsandbits-14.6.jar) 
	UCHIJAAAA	clumps{2.0.0} [Clumps] (Clumps-3.0.0.jar) 
	UCHIJAAAA	cofhcore{4.3.5} [CoFH Core] (CoFHCore-1.12-4.3.5.13-universal.jar) 
	UCHIJAAAA	cofhworld{1.0.1} [CoFH World] (CoFHWorld-1.12-1.0.1.8-universal.jar) 
	UCHIJAAAA	cucumber{1.0.0} [Cucumber] (cucumber[1.12]-1.0.0.jar) 
	UCHIJAAAA	dailies{1.12-6} [Bailey's Dailies] (dailies-1.12-6.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCHIJAAAA	draconicevolution{2.3.3} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.3.261-universal.jar) 
	UCHIJAAAA	durabilityshow{5.0.0} [Durability Show] (Durability Show-1.12-5.0.0.jar) 
	UCHIJAAAA	dsurround{3.4.7.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.7.0.jar) 
	UCHIJAAAA	presets{3.4.7.0} [§3Presets!] (DynamicSurroundings-1.12-3.4.7.0.jar) 
	UCHIJAAAA	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2.jar) 
	UCHIJAAAA	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCHIJAAAA	enderrift{2.1.9} [Ender-Rift] (EnderRift-1.12.1-2.1.9.jar) 
	UCHIJAAAA	extrabitmanipulation{1.12-3.1.1} [Extra Bit Manipulation] (ExtraBitManipulation-1.12-3.1.1.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.jar) 
	UCHIJAAAA	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHIJAAAA	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCHIJAAAA	fencejumper{1.0.0} [Fence Jumper] (fencejumper-1.12-1.0.0.jar) 
	UCHIJAAAA	gardenstuff{1.12-2.1.0} [Garden Stuff] (GardenStuff-1.12-2.1.0.jar) 
	UCHIJAAAA	hammercore{1.9.4.0} [Hammer Core] (HammerCore-1.12-1.9.4.0.jar) 
	UCHIJAAAA	waila{1.8.20} [Waila] (Hwyla-1.8.20-B35_1.12.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJAAAA	journeymap{1.12-5.5.0b3} [JourneyMap] (journeymap-1.12-5.5.0b3.jar) 
	UCHIJAAAA	jeresources{0.8.3.23} [Just Enough Resources] (JustEnoughResources-1.12-0.8.3.23.jar) 
	UCHIJAAAA	keepinginventory{2.2} [Keeping Inventory] (KeepingInventory-1.12-2.2.jar) 
	UCHIJAAAA	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCHIJAAAA	largeveins{@VERSION@} [Large Veins] (LargeVeins-1.12-1.1.0.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.5-1.12.jar) 
	UCHIJAAAA	llor{1.1.4-mc1.12} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.4-mc1.12.jar) 
	UCHIJAAAA	lostcities{0.0.20beta2} [The Lost Cities] (lostcities-1.12-0.0.20beta2.jar) 
	UCHIJAAAA	mendingfix{1.0.1} [Mending Fix] (mendingfix-1.0.1.jar) 
	UCHIJAAAA	metamorph{1.1.3} [Metamorph] (metamorph-1.1.3-1.12.jar) 
	UCHIJAAAA	moartinkers{0.5.4} [Moar Tinkers] (moartinkers-0.5.4.jar) 
	UCHIJAAAA	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCHIJAAAA	mobends{0.24} [Mo' Bends] (mobends-0.24_for_MC-1.12.jar) 
	UCHIJAAAA	morepaintings{1.11.2-3.2.1.1} [Paintings++] (morepaintings-paintings-1.12-3.2.1.1.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.3-1.12.jar) 
	UCHIJAAAA	mmm{1.0.3} [mmm] (mutatedmobs-1.0.3.jar) 
	UCHIJAAAA	mysticalagriculture{1.6.3} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.3.jar) 
	UCHIJAAAA	nmsot{1.2.1-mc1.12} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.1-mc1.12.jar) 
	UCHIJAAAA	personalcars{1.4} [Personal Cars] (PersonalCars-1.4.jar) 
	UCHIJAAAA	pressure{1.3.1.2} [Pressure Pipes] (pressure-1.3.1.2-mc1.12.jar) 
	UCHIJAAAA	quickleafdecay{1.2.4} [Quick Leaf Decay] (QuickLeafDecay-MC1.12.1-1.2.4.jar) 
	UCHIJAAAA	cobwebs{1.0.3} [Realistic Cobwebs Mod] (realistic-cobwebs-1.12.1-1.0.3.jar) 
	UCHIJAAAA	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UCHIJAAAA	thermalfoundation{2.3.5} [Thermal Foundation] (ThermalFoundation-1.12-2.3.5.14-universal.jar) 
	UCHIJAAAA	thermalexpansion{5.3.5} [Thermal Expansion] (ThermalExpansion-1.12-5.3.5.19-universal.jar) 
	UCHIJAAAA	redstonearsenal{2.3.5} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.5.13-universal.jar) 
	UCHIJAAAA	roguelike{1.7.1} [Roguelike Dungeons] (RoguelikeDungeons-1.12-1.7.1.jar) 
	UCHIJAAAA	simplemagnet{1.12.0-1.2.6} [Simple Magnet] (simplemagnet-1.12.0-1.2.6.jar) 
	UCHIJAAAA	solarfluxreborn{3.25r} [Solar Flux Reborn] (SolarFluxReborn_1.12-3.25r.jar) 
	UCHIJAAAA	spartanshields{1.3a} [Spartan Shields] (SpartanShields-1.12-1.3a.jar) 
	UCHIJAAAA	switchbow{1.4} [Switch-Bow] (switchbow-1.4.jar) 
	UCHIJAAAA	thermalcultivation{0.1.1} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.1.6-universal.jar) 
	UCHIJAAAA	thermaldynamics{2.3.5} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.5.12-universal.jar) 
	UCHIJAAAA	torcharrowsmod{1.12-2} [TorchArrows] (torcharrows-1.12-3.jar) 
	UCHIJAAAA	trashslot{8.4.4} [TrashSlot] (TrashSlot_1.12.1-8.4.4.jar) 
	UCHIJAAAA	vanillamagic{1.12-0.22.1.4} [Vanilla Magic] (VanillaMagic-1.12-0.22.1.4.jar) 
	UCHIJAAAA	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCHIJAAAA	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCHIJAAAA	wailaharvestability{1.1.11} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.11.jar) 
	UCHIJAAAA	wawla{2.5.240} [What Are We Looking At] (Wawla-1.12.1-2.5.240.jar) 
	UCHIJAAAA	weatherconfig{1.0.1} [WeatherConfig] (WeatherConfig-1.12-1.0.1.jar) 
	UCHIJAAAA	webshooter{1.0.2} [WebShooter] (webshooter-1.11-1.0.2.jar) 
	UCHIJAAAA	witherskelefix{2.2.2} [Wither Skeleton Tweaks] (Wither Skeleton Tweaks-1.12-2.2.2.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
AstralCore (astralsorcery-1.12-1.6.1.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.7.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
IMLoadingPlugin (infinimend-1.12-1.0.1.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
weatherconfig_coremod (WeatherConfig-1.12-1.0.1.jar)
  net.dries007.weatherconfig.asm.WeatherConfigTransformer
BCModPlugin (backpacks 1.12 - 3.3.2.jar)
  brad16840.common.asm.ClassTransformer
SFRCore (SolarFluxReborn_1.12-3.25r.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* ArmorPlusApi (2.0) from armorplus-1.12-11.5.1.16-alpha.jar
		* Base|API (1.0.0) from base-1.12-3.0.0.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12-0.4.5.34.jar
		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-14.6.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.5.13-universal.jar
		* DLDungeonsAPI (1.1) from DoomlikeDungeons-1.9.3-MC1.12.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12-2.3.3.261-universal.jar
		* GraphApi (1.3.0) from GraphLib-1.3.0.jar
		* jeresources|API (0.8.3.23) from JustEnoughResources-1.12-0.8.3.23.jar
		* journeymap|client-api (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b3.jar
		* journeymap|client-api-display (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b3.jar
		* journeymap|client-api-event (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b3.jar
		* journeymap|client-api-model (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b3.jar
		* journeymap|client-api-util (1.4-SNAPSHOT) from journeymap-1.12-5.5.0b3.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.1-4.7.8.92.jar
		* pressureAPI (1.3.1.2) from pressure-1.3.1.2-mc1.12.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar
		* WailaAPI (1.3) from Hwyla-1.8.20-B35_1.12.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.0.9.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LocoMinerDad'/366, l='New Worldv rare 2', x=244.07, y=72.00, z=650.38]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by nrllewellyn** [comment]
I'm also seeing this issue. Crafter places fine, but gives an identical exception (including the array index of '9') when you try to set the recipe.

**Comment by Baileypup2001** [comment]
I'm having this issue too. I placed the crafter, then tried to put a recipe in and it crashed. I am trying to get back in my world to get rid of it, but the first time it took around 10 minutes on just the building blocks part before I gave up. I tried again and now it crashes a few seconds after I choose the file.
