### ISSUE TITLE
Builder's Wand rendering bug

### ISSUE THREAD

**Issue by AlexandraIsabel** [rwtema/extrautilities_old_issues#168]
[FML Log](https://db.tt/F72HGTsD). When attempting to use the Builder's Wand or Creative Builder's Wand, a rendering bug occurs resulting in the displayed world to appear Blueish-gray.
![2014-07-11_16 08 52](https://cloud.githubusercontent.com/assets/7906551/3558159/e8cc0cc6-0938-11e4-9877-67e077347206.png) This screenshot shows this just that the screenshot has the bounding boxes which, are not displayed in the client.

**Comment by rwtema** [comment]
Unable to replicate and the log shows nothing. I don't know of anything that would cause the renderer to go into wireframe mode. Unless you have more info, I'm afraid I can't help.

**Comment by AlexandraIsabel** [comment]
It could just be my ATI Mobility Radeon 4000 series graphics card not being able to handle this kind of stuff anymore.

**Comment by AlexandraIsabel** [comment]
Just decided to test this in linux and it does not happen.
