### ISSUE TITLE
Angel ring not working

### ISSUE THREAD

**Issue by Avalonzo** [rwtema/extrautilities_old_issues#169]
Hello, I just finally managed to craft my Angel ring and it's not letting me fly I can see my wings and also making sure my hunger bar is full & also tried it in my baubles slots to no avail is there anything else I'm meant to be doing other than double tapping spacebar?

I'm running MC 1.7.2 with Forge build 10.12.2.1147

Thank you

**Comment by rwtema** [comment]
No idea, that should work. Do you have any more info?

**Comment by Avalonzo** [comment]
Hello, I'm not sure what else you would like but here is a screenshot of the mods I'm using - http://i1217.photobucket.com/albums/dd394/Christian_Gaisford/Modcollection1.png
I hope it helps

**Comment by rwtema** [comment]
Not enough info to go on I'm afraid. I'm guessing your server has disabled flying or you've made a mistake somewhere. Feel free to try with 1.1.0e.

**Comment by Avalonzo** [comment]
I was playing in ssp not smp and I will try that on my 1.7.10 ssp thank you for getting back top me.
