### ISSUE TITLE
Transfer Nodes Issuing TickingTileEntity and NullPointer

### ISSUE THREAD

**Issue by Phi--Phi** [rwtema/extrautilities_old_issues#17]
I made a cobble gen with your transfer nodes, then I made a 2nd cobble gen next to it. I accidentally shift-clicked in the mining upgrades and it inserted them into ether a chest or an ME chest(both where same distance and the only inventories attached to my pipes) and it crashed instantly. This was in single player and my crash report is here: http://pastebin.com/YCKaursx
Then I restarted Minecraft and it crashed on loading the world. this crash report is here: http://pastebin.com/3cTeZgmm
I was using the Thec World 2 ftb modpack

**Comment by DaximusMaximus** [comment]
I am also having a NullPointer error. Using Extra Utilities pipes with my MFR grinder, laying pipes while backing up, shift right click to attach a transfer pipe to an item transfer node, and BAM. Crash. I've gotten it multiple times, on multiple world saves. Crash report: http://pastebin.com/hz0KMjda
Using FTB Direwolf20 1.6.4 1.0.20

**Comment by the-vindex** [comment]
I'm getting the same crash as @DaximusMaximus, I can provide world as this happens in my sandbox world.

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
