### ISSUE TITLE
Project Red

### ISSUE THREAD

**Issue by ppappila** [rwtema/extrautilities_old_issues#171]
ok....spending a long time figuring out what is going on...using minecraft 1.7.1.10 and the latest version of Project Red....when trying to log on the server with extra utilities cannot log on and an error as reported before. However if I remove Project Red I can now log on to the sever with extra utilities.  I believe this happened before with Project Red...maybe should you contact them ask wtf is going on....I remember when I reported last time them shoved off

**Comment by rwtema** [comment]
Crash log?
