### ISSUE TITLE
(1.12.2) poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [rwtema/extrautilities_old_issues#1739]
Hey ! I launch my game, like other days, and... poof! crashes.
[crash-2017-11-01_21.42.50-client.txt](https://github.com/rwtema/extrautilities/files/1435648/crash-2017-11-01_21.42.50-client.txt)

Can you help me to fix this crash, please ? :D

**Comment by Diamondman121314** [comment]
Oh look, I saw you somewhere else. >_> 
But I have the same problem, too.

**Comment by IchigoGames** [comment]
same issue may be about time to fix update your mod

**Comment by cjburkey01** [comment]
Same issue, there's no auto updater, right?

**Comment by cjburkey01** [comment]
Figured it out; downgrade to forge  14.23.0.2522 or below. Same issue as #1736

**Comment by Migmag789** [comment]
I have many mods that require latest version of forge :/ I'm going to wait for a update ;)

**Comment by DeadSix27** [comment]
@Migmag789 ye mainly BoP. Time to wait eu2 update
EDIT: You should prob change title to "Forge 2528 causes EU2 to crash" or so, so he(and others) can see it easier

**Comment by C0rn3j** [comment]
Please close this issue as there's another one open already
@Migmag789

**Comment by Migmag789** [comment]
Ok ^^
