### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by CruaverVoidDrake** [rwtema/extrautilities_old_issues#174]
Ok so the latest optifine now works with this except for when I go to the deep dark (which the torched mod works very well in) as you can see: 
![screen shot 2014-07-14 at 7 26 25 pm](https://cloud.githubusercontent.com/assets/7862176/3588337/8568e0de-0c42-11e4-8b78-5fd1745bb2bb.png)

**Comment by CruaverVoidDrake** [comment]
Btw this only happens when I go to the deep dark otherwise the wood is normal.

**Comment by rwtema** [comment]
Intended. I assume you're near a castle in the deep dark. Colored wood/bricks has chunk-palette system, where you can alter their default colors within a chunk. Castles in the deep dark use this system to have different colors.
