### ISSUE TITLE
[1.12.2] JEI issue

### ISSUE THREAD

**Issue by 016Nojr** [rwtema/extrautilities_old_issues#1740]
When viewing ExUtils 2 items in JEI, they change appearance

https://gyazo.com/e6c201998aea0daae634e891a8bdd80f

**Comment by Peca21** [comment]
I've seen this happening with multiple mods so I don't think this si a ExU2 issue, but I am not sure

**Comment by 016Nojr** [comment]
Fixed on JEI's side
