### ISSUE TITLE
Still Problem with new Forge Versions >0.2517

### ISSUE THREAD

**Issue by Gulduka** [rwtema/extrautilities_old_issues#1744]
Hi there,
in front thanks for the 1.6.5 Update of extrautil but the bug with Forge Versions newer then 0.2517 is still remain.

Final the same error like with 1.6.4
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from extrautils2 (extrautils2)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry

With Forge 0.2517 all running fine. 

Hope you find fast the bug and thanks for the work on extrautil @rwtema

**Comment by Daihok41** [comment]
Hmm im running the 1.6.5 update on newest forge just fine. Im running 2529 forge.

**Comment by tgstyle** [comment]
Full crash log
https://gist.github.com/tgstyle/429f2466f733cf5e3aa7e4d7ae7357b6

**Comment by Gulduka** [comment]
Here my crash.log :-/

[crash-2017-11-05_12.57.51-client.txt](https://github.com/rwtema/extrautilities/files/1446005/crash-2017-11-05_12.57.51-client.txt)

**Comment by tgstyle** [comment]
Looks like your using the 1.11.2 version as per your log, I discovered the same thing.

extrautils2-1.11.2-1.6.5.jar

**Comment by zISKo666** [comment]
I am curious, why are you using an 1.11.2 version with MC 1.12.2?
Maybe you should try the correct version!?
https://minecraft.curseforge.com/projects/extra-utilities/files/2497041/download
