### ISSUE TITLE
[1.12.2] Ender Shards are uncraftable

### ISSUE THREAD

**Issue by TheLimePixel** [rwtema/extrautilities_old_issues#1758]
As as of forge 14.23.0.2532 you cannot make recipes where an item with any damage value is used, you cannot craft Ender Shards with a non-fully-repaired Glass Cutter.

**Comment by the-pieman** [comment]
Having this same issue. I was able to create a set of eight, which damaged the Cutter, and it would no longer display an output on trying to cut a second pearl with the damaged cutter.

Running version 1.6.5 of Extrautils2

**Comment by ouroborus** [comment]
Works correctly with forge 2531. 2532 introduced a number of crafting issues and not just for this mod.
