### ISSUE TITLE
Infinite Iron Ingots (Infinite Items): Crafting with transfer nodes

### ISSUE THREAD

**Issue by Micky2506** [rwtema/extrautilities_old_issues#176]
When crafting a inactive division sigil using the world interaction upgrade in a transfer node, you get infinite iron. When crafting in a regular crafting table, you get a variable amount of iron from 1-36 (possibly more, but highest that I found).

The infinite iron results from the division sigil not being used by when crafted in this manner.

A possibly related issue is that an activated division sigil will be 'used' when crafting in this manner, and while it is active it will not craft into iron.

Don't think that pictures are really required for this, but if you need/want them, I will be happy to post them.

**Comment by rwtema** [comment]
Fixed in 1.1.0e. The auto-crafting wasn't destroying 'broken' items.
