### ISSUE TITLE
World Interaction Upgrades and Speed Upgrades Bug

### ISSUE THREAD

**Issue by Beamfield** [rwtema/extrautilities_old_issues#177]
Hello, I found a bug that if you place down a Tranfer Node(Items) and you install a World Interaction Upgrade in it and place Speed Upgrades in the Node(16 or more, the more Speed upgrades the more items will duplicate) and drop an item front of the node.
This is basically the bug, I think Quetzz used this bug to get that many HV solar arrays that he has.
Have a nice day, and good luck to sold this problem!
-- Beamfield

Oh by the way I'm using Extra Utilities 1.1.0b

**Comment by rwtema** [comment]
This was fixed in 1.1.0c

**Comment by Beamfield** [comment]
Okay thank you.
