### ISSUE TITLE
Quantum Quarry Dim has lots of entities for some reason

### ISSUE THREAD

**Issue by Based199** [rwtema/extrautilities_old_issues#1777]
No idea why, but the quarry dim has lots of entities and tile entities there
![2017-11-21_16 30 31 2](https://user-images.githubusercontent.com/32063145/33103890-f9f29a32-ced9-11e7-8340-8645d4513e98.png)

Resonant Rise 4 modpack
exutils version: 1.10.2-1.6.3

**Comment by JoeSGT** [comment]
Update the Extra Utilities he had remove entities can no longer spawn in quantum quarry custom dimension
 Extra Utilities most recommend version is 1.6.7

**Comment by Based199** [comment]
Ah, very good thank you for the info
