### ISSUE TITLE
Magnum Torch Cannot find recipe in Version 1.1.0b

### ISSUE THREAD

**Issue by drutech** [rwtema/extrautilities_old_issues#178]
Hi

I'm using your mod in my personal LP and loving it. 

I've been wanting to make a Magnum Torch and cannot find the recipe. Look for it in some vids on the mod and tried them but they don't work.

I've even looked at the config file to see if there was something that said the recipe was turn off. nothing.

Hope you can help! :)

Thanks
Drutech

**Comment by rwtema** [comment]
It's crafted in the QED. Does the recipe not show up in NEI?

**Comment by drutech** [comment]
Sorry still new to some stuff in modded MC. What is a QED? I'm not using
NEI, 

i'm using CraftGuide  by Uristqwerty
http://www.curse.com/mc-mods/minecraft/craftguide.

Thanks
Peter G

_Sent from Gmail.com site_

**Comment by rwtema** [comment]
Not an issue then. Sorry, but NEI is the recommended source for recipes.

The QED is an advanced crafting table that requires significant resources and power. MTorches were moved there as a balance measure. You can disable this in the configs.
