### ISSUE TITLE
[1.12.2] Glass Cutter Dupe

### ISSUE THREAD

**Issue by TheLimePixel** [rwtema/extrautilities_old_issues#1780]
When trying to repair 2 Glass Cutters, they don't get used up, but there durability does instead, allowing you to, in a way, get an infinite amount of them:
![image](https://user-images.githubusercontent.com/25333164/33229655-2e14e54e-d1d3-11e7-8607-8dd04203df66.png)
![image](https://user-images.githubusercontent.com/25333164/33229658-340f778e-d1d3-11e7-91ba-b1d79254bd0b.png)
![image](https://user-images.githubusercontent.com/25333164/33229660-37e7dcde-d1d3-11e7-9b26-9a93990bf6bf.png)

Oh, and the Ender Shard recipe once gain doesn't work with used up Glass Cutters:
![image](https://user-images.githubusercontent.com/25333164/33229667-52ce2b66-d1d3-11e7-90c1-08339412cc68.png)

**Comment by JoeSGT** [comment]
Fixed in the EU 1.6.8
