### ISSUE TITLE
[1.12.2][1.6.5]  Holding Enderlily reduces FPS by ~120

### ISSUE THREAD

**Issue by Dalarrus** [rwtema/extrautilities_old_issues#1781]
While holding other objects in my hand, I have 70-200 FPS, simply holding the ender lily will drop my fps to ~10, I'm playing the Direwolf20 pack, and have not added, removed, or configured any mods differently.

![modlist_1](https://user-images.githubusercontent.com/12202558/33249595-2586ad26-d2f1-11e7-97b7-7dfd7ae4d643.png)
![modlist_2](https://user-images.githubusercontent.com/12202558/33249596-26b545cc-d2f1-11e7-843b-34ec31349333.png)
![modlist_3](https://user-images.githubusercontent.com/12202558/33249598-27d0cc42-d2f1-11e7-9bc1-360e549925d5.png)
![modlist_4](https://user-images.githubusercontent.com/12202558/33249600-28fc2c24-d2f1-11e7-94ce-2c48748662c1.png)

**Comment by runescapejon** [comment]
it's been fixed just update your Extra utilities
