### ISSUE TITLE
Bug. Missing method

### ISSUE THREAD

**Issue by K-4U** [rwtema/extrautilities_old_issues#180]
Happens in my dev environment 1.7.10 with latest version (1.1.0e)
I place down a liquid transfer node and one of my lava pumps next to it(Hydraulicraft).
I then get this crash: http://pastebin.com/pbbXfzaj

If any more info is required, let me know.

**Comment by rwtema** [comment]
It looks like an older version of BCs API is loaded. Do you have you got the latest BC Api installed?

**Comment by K-4U** [comment]
I'm using Buildcraft 6. That might actually be the issue. Haven't checked that properly.
What version of Buildcraft is ExtraUtils built against?

**Comment by rwtema** [comment]
Latest version of the Buildcraft API.

**Comment by rwtema** [comment]
Ultimately this is not an Extra Utilities issue, so... closed.
