### ISSUE TITLE
Energy extraction pipes can pull from solar generators when the generator is not in transmitting mode

### ISSUE THREAD

**Issue by vtsman** [rwtema/extrautilities_old_issues#181]
By attaching an energy extraction pipe to a solar generator and an energy node, you can circumvent the additional redstone to automate solar generators and the 10 second cooldown, making them very OP

**Comment by TherminatorX** [comment]
Pic of setup? Version?

**Comment by vtsman** [comment]
I'm running on ftb unstable, though I also tested on 1.1.0e with the same results. My setup is shown below.
![2014-07-19_16 56 25](https://cloud.githubusercontent.com/assets/3949672/3635733/70a3105a-0f87-11e4-84c2-e143e020304e.png)

**Comment by rwtema** [comment]
Thanks. Will be fixed in next version.
