### ISSUE TITLE
A lot of error messages that I don't understand

### ISSUE THREAD

**Issue by Shahelion** [rwtema/extrautilities_old_issues#1811]
Something pink? https://hastebin.com/xezigexelo.md

**Comment by NeedAUser** [comment]
hm...are you trying to do something with both xreliquary and extrautilities? My /guess/ is that an extrautilities thing is trying but failing to use a xreliquary  block. possibly with a xreliquary pedestal of some kind.

**Comment by Shahelion** [comment]
No pedestals in this world at all yet, or any reliquary blocks, and no XU blocks or items either that I know of, except some moonstone in a chest.

**Comment by NeedAUser** [comment]
No idea then.

**Comment by Shahelion** [comment]
If I can reproduce this, I'll re-open it. Otherwise, it's likely just a one-time thing.
