### ISSUE TITLE
[1.7.10] Crash to Desktop - Generators. 

### ISSUE THREAD

**Issue by Ayrrow** [rwtema/extrautilities_old_issues#182]
Suddenly I crashed to desktop, cannot load the world again without crashing. I do not have any generators from your mod placed in world. Using the latest version (1.10e) and forge 1187.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 20/07/14 5:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at com.rwtema.extrautils.tileentity.generator.BlockGenerator.getWorldModel(BlockGenerator.java:290)
    at com.rwtema.extrautils.block.BlockMultiBlock.func_149743_a(BlockMultiBlock.java:50)
    at net.minecraft.world.World.func_72945_a(World.java:1410)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1488)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1812)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
    at net.minecraft.entity.passive.EntityChicken.func_70636_d(SourceFile:56)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:660)
    at net.minecraft.world.World.func_72870_g(World.java:1983)
    at net.minecraft.world.World.func_72939_s(World.java:1836)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:501)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.rwtema.extrautils.tileentity.generator.BlockGenerator.getWorldModel(BlockGenerator.java:290)
    at com.rwtema.extrautils.block.BlockMultiBlock.func_149743_a(BlockMultiBlock.java:50)
    at net.minecraft.world.World.func_72945_a(World.java:1410)
    at net.minecraft.entity.Entity.func_70091_d(Entity.java:596)
    at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1488)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1812)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
    at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
    at net.minecraft.entity.passive.EntityChicken.func_70636_d(SourceFile:56)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1609)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2019)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:660)
    at net.minecraft.world.World.func_72870_g(World.java:1983)

-- Entity being ticked --
Details:
    Entity Type: Chicken (net.minecraft.entity.passive.EntityChicken)
    Entity ID: 418
    Entity Name: Chicken
    Entity's Exact location: 121.18, 73.20, 87.58
    Entity's Block location: World: (121,73,87), Chunk: (at 9,4,7 in 7,5; contains blocks 112,0,80 to 127,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Entity's Momentum: -0.04, -0.07, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1836)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:501)

-- Affected level --
Details:
    Level name: alphaOne
    All players: 1 total; [EntityPlayerMP['Ayrrow'/359, l='alphaOne', x=-31.97, y=68.00, z=241.54]]
    Chunk stats: ServerChunkCache: 751 Drop: 0
    Level seed: 5249746382817395476
    Level generator: ID 03 - amplified, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-104,64,252), Chunk: (at 8,4,12 in -7,15; contains blocks -112,0,240 to -97,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 343776 game time, 326775 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 92941 (now: false), thunder time: 3107 (now: true)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 143081896 bytes (136 MB) / 674500608 bytes (643 MB) up to 3186360320 bytes (3038 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:MaxPermSize=512m -Xmx3G -Xincgc
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.24.1187 Minecraft Forge 10.13.0.1187 60 mods loaded, 60 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.24.1187} [Forge Mod Loader](forge-1.7.10-10.13.0.1187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.0.1187} [Minecraft Forge](forge-1.7.10-10.13.0.1187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv1-alpha-3} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Aroma1997Core{1.0.2.6} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.11} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.30} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.30-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AetherCraft{1.4.3.24} [AetherCraft](AetherCraft-1.7.10-1.4.3.24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.0.17} [BuildCraft](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{2.0_beta} [Ender IO](enderio-2.0_beta.142.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.0.16} [Baubles - Princess Edition ](Baubles-princess-1.7.2-1.0.0.18p.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.0.297} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0e} [Extra Utilities](extrautilities-1.1.0e.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mekanism{7.0.0} [Mekanism](Mekanism-1.7.10-7.0.0.62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv1-alpha-3} [Applied Energistics 2](appliedenergistics2-rv1-alpha-3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Aroma1997CoreHelper{1.0.2.6} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AromaBackup{0.0.0.2} [AromaBackup](AromaBackup-1.7.2-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.7.4} [BiblioCraft](BiblioCraft[v1.7.4][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1g%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.1-82} [Botania](Botania r1.1-82.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.0.17} [BC Builders](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.0.17} [BC Energy](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.0.17} [BC Factory](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.0.17} [BC Transport](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.0.17} [BC Silicon](buildcraft-6.0.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.5 [DEV] - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Eln{19} [Electrical Age](ElectricalAge_BETA-1.7_r19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Enchiridion{1.2} [Enchiridion](Enchiridion-1.7.2-1.1a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.4.9} [EnderStorage](EnderStorage-1.7.10-1.4.4.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{2.1.4} [ExtraCells](ExtraCells-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{1.7.10-0.8.86} [Factorization](Factorization-1.7.10-0.8.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{1.7.10-0.8.86} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Steamcraft{0.22.8} [Flaxbeard's Steam Power](FlaxbeardsSteamPower-1.7.10-0.22.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{2.4.2.30} [Forestry for Minecraft](forestry_1.7.10-2.4.2.30.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.58-dev-139-7d397cb} [Inventory Tweaks](InventoryTweaks-1.58-dev-139.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.41.729} [Iron Chest](ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mariculture{b12.5} [Mariculture](Mariculture-1.7.10-b12.5-46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismGenerators{7.0.0} [MekanismGenerators](MekanismGenerators-1.7.10-7.0.0.62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismTools{7.0.0} [MekanismTools](MekanismTools-1.7.10-7.0.0.62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons{1.12.0.1} [NEI Addons](neiaddons-mc1710-1.12.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExtraBees{1.12.0.1} [NEI Addons: Extra Bees](neiaddons-mc1710-1.12.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|Forestry{1.12.0.1} [NEI Addons: Forestry](neiaddons-mc1710-1.12.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|CraftingTables{1.12.0.1} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NEIAddons|ExNihilo{1.12.0.1} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SpiceOfLife{1.1.0} [The Spice of Life](SpiceOfLife-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.0.297} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aobd{2.2.0} [Another One Bites The Dust](AOBD-2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.0.297} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.297-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: alpha rv1-alpha-3 for Forge 10.13.0.1152
    AE2 Integration: RotaryCraft:OFF, IC2:OFF, RC:OFF, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:ON, Waila:OFF, CLApi:OFF, RB:OFF, InvTweaks:ON, NEI:ON, CraftGuide:OFF, FMP:ON
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Ayrrow'/359, l='alphaOne', x=-31.97, y=68.00, z=241.54]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by rwtema** [comment]
Looks like blocks were placed but the necessary tile entities weren't created. This _may_ have been caused by another mod being removed at the same time Extra Utilities was put in. Try disabling the generators in the config, reloading the world (so they get set to air) and then re-enabling them.

In the mean time I'll add a simple check for that.

**Comment by Ayrrow** [comment]
Hey mate thanks for the response. 

Disabling the generators loaded the world, however it took around 5 minutes to do so (rather than the usual 5-10 seconds).
