### ISSUE TITLE
Crash with Transfer Node crafting

### ISSUE THREAD

**Issue by Swordfish19** [rwtema/extrautilities_old_issues#183]
![1](https://cloud.githubusercontent.com/assets/2706833/3649207/61cb4d1a-1110-11e4-8b23-3c0c0414cd9e.jpg)
![2](https://cloud.githubusercontent.com/assets/2706833/3649208/61cd3f12-1110-11e4-926f-3f82f6ffd67c.jpg)
![2014-07-21_21 43 29](https://cloud.githubusercontent.com/assets/2706833/3649219/7691dfa2-1110-11e4-9e68-c44899166cfb.png)

See the attached screenshot:
Place the world interaction update in the left transfer node, wait a few seconds: Crash

**Comment by rwtema** [comment]
Not sure, I'll look into it.

Is there any particular reason why you included screenshots of the crash logs as opposed to just copying the text?

**Comment by ericBG** [comment]
Erm... that seems to be ProfMobius' fault from looking at the crash log...

**Comment by rwtema** [comment]
It seems to have crashed while extracting the item. I can't see any reason on my end for this to happen, it's checked the item is there and non-zero stack size. Gonna say probably a JABBA bug.
