### ISSUE TITLE
Mechanical crafter bug

### ISSUE THREAD

**Issue by NickOver** [rwtema/extrautilities_old_issues#1848]
Sorry for topic, i doesnt know how name that bug. If, in mechanical crafter i set recipe using one piece of resource and i put that resource in more that one slot machine use one piece from all slot.
For example:
I set recipe using one piece of cobble and one piece of dirt and, in mechanical user inventory i put for example 2 stack of cobble and dirt it craft only one stack, because for one crafting it use one peace of resource from all slots. If i use recipe using 3 cobble, 3 cobble will be taken from all inventory slots where cobble is. 
Only buckets look's work correctly.
I play on 1.12 with EU2 1.7.2 on direwolf20 modpack.

**Comment by pinter-gabor-at** [comment]
I cannot reproduce this bug on a clean install Minecraft 1.12.2, Forge 14.23.1.255, extrautils2-1.12-1.7.2.jar
I am crafting torches.
Initial state:
![2](https://user-images.githubusercontent.com/6544011/35326363-bcc5fcb8-00f6-11e8-9d20-2f1e54bd9e69.png)
Final state:
![3](https://user-images.githubusercontent.com/6544011/35326366-c399dde8-00f6-11e8-8d3d-6d98dcc619ff.png)
This is the correct and expected result.
