### ISSUE TITLE
NullPointerException: Ticking Player

### ISSUE THREAD

**Issue by Xogue** [rwtema/extrautilities_old_issues#1857]
MC 1.12.2
Forge: 2601
EU: 1.7.3

Attempting to place a transfer node for items on an interface from playerstorage.  I asked the mod dev of playerstorage about it and he told me it was an issue with this mod.  I hope this crash log helps.

[crash-2018-01-29_13.51.58-server.txt](https://github.com/rwtema/extrautilities/files/1674943/crash-2018-01-29_13.51.58-server.txt)

**Comment by joselitosn** [comment]
Got the same bug, for now the solution is to revert to the previous version.
