### ISSUE TITLE
Ring of Flying Squid stops working after changing dimensions.

### ISSUE THREAD

**Issue by undeadbanana** [rwtema/extrautilities_old_issues#1858]
I have more than enough GP available (Around 50 during daytime and 31 during night) and for some reason the flight is working intermittently. Sometimes taking it out of bauble slot, putting into hotbar and hovering over it with mouse will kickstart into working again but other times it just doesn't want to work. I did create it prior to 1.7.3's release, so unsure if it being created before made it buggy. I'll make another to see if that one works better.

**Comment by undeadbanana** [comment]
I reverted to previous edition, but have been running into same issue. I have a wireless battery and ring of flying squid, so energy use is at 21, minimum generated now is 35 at night. The best way i've found to getting it to work again is by throwing the ring on the ground and picking it up, seems to update the system to realizing we should be able to fly.

All the power is in a chunkloaded area also; unsure what's causing this.

**Comment by Endmateria** [comment]
Can confirm.  Ring of Flying Squid not working as intended/exactly as @Undeadbanana describes.

MC 1.12.2
Forge 1.12.2 - 14.23.1.2607
Extra Utilities 1.12 - 1.7.3

**Comment by undeadbanana** [comment]
Figured it out. It's occuring whenever there's a change in dimensions, whether it be from the End-Overworld, CompactMachines-Anywhere, etc. For some reason it stops working;  Dropping the item and then picking it up resyncs it and everything works normally until another dimension change is made.

**Comment by calloatti** [comment]
You just have to right click on it in your inventory and click it back in. No need to drop it.
