### ISSUE TITLE
Server Crashing on v1.1.0e

### ISSUE THREAD

**Issue by cdempsey** [rwtema/extrautilities_old_issues#187]
While trying to start up a new MC 1.7.10 server running Extra Utilities v1.1.0e with Forge 7.10.24.1187. When I remove the Extra Utilities .jar from /mods the server starts up without issue.

[Here's the server log when it crashes](https://paste.ee/p/OW10e)

**Comment by rwtema** [comment]
Not sure what's happening here.

It appears some mod has added a BlockSlab that doesn't implement abstract methods. No idea how they managed to do this though since this should be caught in compile.

Sorry nothing I can do about it.

**Comment by cdempsey** [comment]
Just to help out anyone in the future that might run into this I found it was AbbysalCraft-1.7.10-1.6.0.jar that was causing the issue. I removed it and the server started up normally with Extra Utilities v1.1.0e.
