### ISSUE TITLE
Entity colision crash with Conveyor belts

### ISSUE THREAD

**Issue by rstat1** [rwtema/extrautilities_old_issues#189]
Just started getting this crash whenever I (or anyone else on my server) go near converyor belts. I end up with an over a MB log file full of StackOverflowException whenever this occurs.

http://paste.ee/p/zb8Ol

**Comment by rwtema** [comment]
Unable to replicate I'm afraid. Any more info?

**Comment by rstat1** [comment]
Someone on my server had a bunch of conveyor belts in a pool of water that in hole dug in a desert biome, and whenever I (or anyone else) got near them the server crashed. It wouldn't crash in an offline world.

Server is running Cauldron and forge 1187, running on (I think) Java 7.

That's really all I have.

**Comment by rwtema** [comment]
Still unable to replicate. Nothing I can do.
