### ISSUE TITLE
Builder's Wand with Top Slabs

### ISSUE THREAD

**Issue by arrowbounce** [rwtema/extrautilities_old_issues#19]
When you use a Builder's wand on a row of top-slabs, the wand builds in the bottom slabs.
![2014-03-31_12 13 13](https://cloud.githubusercontent.com/assets/7119127/2571637/8f8d86e2-b908-11e3-9412-b1108880589e.png)

**Comment by rwtema** [comment]
This is because the default position for the slab item is the downwards position. I could potentially fix this but this would lead to issues with mod blocks that have different default states.
