### ISSUE TITLE
extrautilities-1.1.0e -  Pipes indicators facing both sides

### ISSUE THREAD

**Issue by MrAmericanMike** [rwtema/extrautilities_old_issues#190]
I know this was fixed for 1.7.2 on Issue #107 
But as for version 1.1.0d and 1.1.0e (Minecraft 1.7.10) Tried both and the pipes textures are broke again ;)

![2014-07-22_21 51 22](https://cloud.githubusercontent.com/assets/8037559/3697093/1a7df9cc-139e-11e4-869f-6a794f46fc33.png)

**Comment by rwtema** [comment]
Fixed in 1.1.0f
