### ISSUE TITLE
Psuedo inversion sigil ritual not recognising music discs.

### ISSUE THREAD

**Issue by Ndgc** [rwtema/extrautilities_old_issues#191]
In 1.7 versions of Extra Utilities the pseudo inversion ritual (or is it called stabilisation ritual? I forget) does not seem to recognise music discs placed in the western inventory.

tested under 1.1.0e for 1.7.10
forge:10.13.0.1188

**Comment by rwtema** [comment]
Yeah I noticed. It's because of changes to the ore dictionary. I've fixed it for the next version.
