### ISSUE TITLE
Hyper-Rationing Pipe Disappears but still takes space

### ISSUE THREAD

**Issue by KindarConrath** [rwtema/extrautilities_old_issues#193]
Placing Hyper-Rationing Pipe then hitting it with a BC wrench makes it disappear but you can't place anything where it was, as if the pipe is still there but it doesn't function.  Can be broken with TNT to remove from world.

Possibly related to #192

**Comment by sophieneuenmuller** [comment]
So that was what was happening to me... I was playing with them for some automation and as I am too used to wrench things out I did that to take them off. Is not only the visualization of the pipe, it disappears entirely. I used commands to take them out.

**Comment by rwtema** [comment]
Fixed in upcoming version.
