### ISSUE TITLE
Suggestion: Cache fuels

### ISSUE THREAD

**Issue by SoniEx2** [rwtema/extrautilities_old_issues#194]
I know it'll sound stupid and stuff, but by caching fuels you only have to ask for the fuel values when the item changes... plus it's a single ItemStack.isItemEqual + ItemStack.areItemStackTagsEqual vs multiple when getting the fuel values...

**Comment by rwtema** [comment]
I think some items have fuel values that change over time, such as the lava crystal from Blood magic.

**Comment by SoniEx2** [comment]
Oh... :(

**Comment by SoniEx2** [comment]
What about caching for a tick? I mean let's say you have 1000 generators burning coal. instead of calling the methods 1000 times, you just cache coal, and... oh wait, coal is already optimized...

~~Do generators have to pump energy out into conduits or can conduits pull energy from them? if it's the former then we need a better energy system... alternatively you could cache the connected conduits (if you don't already) and wait for a block/TileEntity update to refresh the cache (and if conduits don't send updates when you enable/disable a side, you should bug them about it, really)~~

Edit: I'm probably gonna make another issue for that

**Comment by rwtema** [comment]
Caching fuels is unlikely to be a large enough optimization to be worth the hassle and potential bugs. In any case if optimization is to be done, then it should be done on Forge's end.
