### ISSUE TITLE
Duplication bug with covers (microblocks)

### ISSUE THREAD

**Issue by Porcy** [rwtema/extrautilities_old_issues#195]
Whenever you break a cover covering a pipe, you get the cover back AND a duped pipe. (Tested with transfer pipe - item)

**Comment by rwtema** [comment]
Is this in 1.6.4?

**Comment by Porcy** [comment]
In your last version 1.something e
Forge 1180

**Comment by rwtema** [comment]
What version of FMP?

**Comment by Porcy** [comment]
1.7.10-1.1.0.297
Don't know if this could affect it, we also have fmpintegration 1.2.2

**Comment by Porcy** [comment]
Also dupes the transfer nodes covered with fmp covers (just tested now)

**Comment by Porcy** [comment]
And the pipe jacket (if there is one)

**Comment by Porcy** [comment]
Just did some rearranging of my sorting system and noticed that when I break the transfer pipes, the covers are duplicated.

**Comment by rwtema** [comment]
Unable to replicate. Try updating FMP and if that doesn't fix it I can't help you.

**Comment by Porcy** [comment]
Did some more formal testing. It appears to be doing this only when using
tools from Tinker's Construct. Wasn't able to replicate with Vanilla
diamond pickaxe. I will report it to mDiyo. Sorry for that

2014-08-03 13:28 GMT-04:00 RWTema notifications@github.com:
