### ISSUE TITLE
tranfer pipes connect to Mekanism cable through covers

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#196]
The transfer pipes try to connect to the universal cable from mekanism, even if I place a cover between them. can you fix this?
![ex_ut](https://cloud.githubusercontent.com/assets/8250746/3715183/5fd273e4-15d4-11e4-9c63-0c8a6f68151f.png)

btw: i think extra utilities is a very cool mod

**Comment by rwtema** [comment]
Can't really help. The mechanism cables need to implement this in their canConnectEnergy() method. My pipes will always defer to this method.
