### ISSUE TITLE
Crafting recipys disapearing

### ISSUE THREAD

**Issue by Skyqula** [rwtema/extrautilities_old_issues#199]
Using this config file: http://pastebin.com/J4iBLEj6
Using: extrautilities-1.1.0e
Using: Minecraft 1.7.10
Using: Forge 10.13.0.1180

The Enderthermic pump is not craftable. All the components are still craftable but the recipie itself does not function.

Other items/blocks are also not craftable. IE: Compressed cobblestone/sand/gravekl, golden lasso and drums.

**Comment by Skyqula** [comment]
Problem is also present in the new version.

Using: extrautilities-1.1.0f
Using: Minecraft 1.7.10
Using: Forge 10.13.0.1190

**Comment by rwtema** [comment]
Fixed in upcoming version.
