### ISSUE TITLE
Ender Lilies on End Stone

### ISSUE THREAD

**Issue by Neshram** [rwtema/extrautilities_old_issues#2]
**What was expected**
I have heard, ender-lily seeds planted on end stone should grow noticeably faster than those planted on other materials.

**What was observed**
The ender-lilies appeared to grow at the same rate regardless of "soil".

**Tested in**
_Primarily_ in Extra Utilities v1.0.3a; both by itself, and as included in Direwolf20 1.6.4 Pack v1.0.16
_Also_ just verified the behavior appears unchanged in v1.0.3b

**Steps to reproduce** (based on final test detailed below)
1. Install new instance of Minecraft with Forge and Extra Utilities.
2. Start a new creative flatland world.
3. Select a 3x3 area of grass.
4. Replace roughly half the area with end stone.
5. Equip a watering can on hotbar.
6. Execute the command "/time set 0".
7. Plant ender-lily seeds on all 9 blocks.
8. Water the seeds until the sun is directly overhead.
9. Execute the command "/time add 18000".
10. Go to step 8 (as needed).

**Additional description**
While the lilies on end stone do occasionally drop an extra seed, I am not seeing them grow any faster.

When I noticed, I set up a test with a 8x8 patch of seeds on half grass and half end stone. Of course the growth was random-ish, but not noticeably different between the materials. In fact, a couple of the first to "bloom" were on grass.

As a follow-up I did the same test, except adding a bunch of Thaumcraft "lamps of growth". Here it was more obvious; no matter the material, at the dawn of every fourth day the whole field would start flickering with Thaum-assisted growth.

As I final test, I removed all mods except Extra Utilities, started a new creative flatland, and tested a 3x3 patch of lilies (2x2 end stone, remainder grass). I used the watering can on them from dawn until noon (or until they all grew) for 14 cycles (using "/time add" to get from noon to the next dawn). Regardless of material, they all grew at the same rate.

_(Hope this layout works for you. If you prefer a different layout for bug reports, just let me know.)_

**Comment by rwtema** [comment]
Thanks the layouts great. I've fixed the issue, it was checking the wrong block for end stone.

**Comment by Neshram** [comment]
Awesome. Thank you. =)

Sounds like it was an easy fix, but as a matter of principle: Confirmed; fixed in v1.0.3c.
