### ISSUE TITLE
Trade Post Issues

### ISSUE THREAD

**Issue by ph1x3r** [rwtema/extrautilities_old_issues#20]
There are two trade post issues that I have come across while playing about with CC integration. Neither are probably bugs, but they are issues.

1) The trade shown by the trade post for a villager is not the last trade available for that villager in the GUI, but it does appear to be the last trade returned in the various tables returned in the CC integration. But there is no way to cycle through the trades to find the one you want. Perhaps an arrow to the left and right of each villager button to flip through the trades.

2) I have so far been unable to make the "performTrade()" function call make a trade. Of course, this could just be my lack of knowledge on how to use it correctly. But having no documentation and no source code, makes it tough to figure out how things are supposed to work :) 

3) There seems to be a discrepancy with table indexing. If getNumTrades(v) returns '5', then a call to getItemBought(v, 5) returns a nil value. Using '4' returns the last trade in the table. Likewise, using '0' returns the first entry.

Obviously, none of these are show stoppers, but I wanted to document them.

Thank you for the mod.

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
