### ISSUE TITLE
Builder Wand on Railcraft Half Slabs.

### ISSUE THREAD

**Issue by StoneLegion** [rwtema/extrautilities_old_issues#201]
EU: 1.1.0e
RC: 9.1.0.6
Can't use the builder wand at all on Half Slabs it seems made through Railcraft. For example Abyssal Block Slab.

http://i.imgur.com/yBGQ45r.jpg

Thanks.

Edit: I talked to CJ. He uses his own completely custom implementation. For example you can take 2 of his slabs and place them in the same block space.

**Comment by rwtema** [comment]
Not really anything I can do about it then. Simple limitation of the system.

**Comment by StoneLegion** [comment]
Ahh thanks. That is too bad I noticed it also happens to the forge microblocks. Thanks for checking in.
