### ISSUE TITLE
Extra Utilities v1.1.0F Generator Crash!

### ISSUE THREAD

**Issue by Shad0wB1ade** [rwtema/extrautilities_old_issues#205]
http://pastebin.com/1QUwKyfZ    Thats it!

**Comment by 61352151511** [comment]
I got that too :(

**Comment by LeChuckXIV** [comment]
same issue too

http://pastebin.com/unTzCHgh

replication steps:
chest full of tnt -> transfer node(stacks upgrade, 64 speed upgrades) -> tnt generator(x64)
reloading world shows 2 stacks removed from chest and generator working fine

**Comment by Thraxus** [comment]
Same here - http://pastebin.com/rCEmtd62

Edit: Forgot to mention, this is definitely related to the new generators - the only thing I have built is a x8 High Temp Furnace gen, and had a second in my backpack.  The only way to get back into the world was to revert to rev"e" and jump back to F (killing the generator).  Possibly related to the new sound scheme to only have the nearest gen to the player actually make sound?

**Comment by Shad0wB1ade** [comment]
Oh I was placing x64 ganerators and that happened didn't have trouble with x8 wierd!

**Comment by Thraxus** [comment]
Just happened again - this time none of the x8 generators were down, but I did have an x64 in my bag.  

http://pastebin.com/HKQT4aVy

One thing I did leave out before (I didn't think it was terribly important) - both of these issues occurred when I dimension traveled (jumped from a mining world (aroma's) back to spawn) with a x8 (and now x64) generator in my backpack.  Directly after making it back home, the game locks and crashed.  I made this trip dozens of times with rev "f" installed and an x64 generator down with no issue.  It wasn't until I had it in my back on the trip home did it cause issues.  

There is another x1 generator down close to my spawn point - just as an idea, maybe I'm jumping dimensions right when the sound event it triggered, but loading lag isn't allowing it to finish before the next sound starts?  

Only way to get back in is to kill rev "f", go back to "e" (to kill the generator), and log back in.

**Comment by rwtema** [comment]
Okay took some trial and error to replicate the crash consistently but it seems that Minecraft's code for checking to see if a sound is already playing is not entirely reliable. I've added a more powerful reflection-based method that runs reasonably fast and gives an exact answer. This will be fixed in the next version.

In the mean time, a hot fix is to go into sound settings and set 'Ambient' sounds to 0%. This simply disables the generator sounds.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0g

**Comment by alpharulesirulee** [comment]
extra utilities crashed on startup with optifine

---- Minecraft Crash Report ----
// You're mean.

Time: 1/10/15 1:55 PM
Description: Registering texture

java.lang.RuntimeException: Likely Optifine error. Please only report if it occurs without Optifine installed:
TextureAtlasSprite.load(IResourceManager manager, ResourceLocation location) called with bad parameters.
Expected resource path supergenerators/sgenerator_tnt_1_0, recieved textures/blocks/supergenerators/sgenerator_tnt_1_0.png.

```
at com.rwtema.extrautils.texture.TextureMultiIcon.load(TextureMultiIcon.java:88)
at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:172)
at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:122)
at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76)
at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at com.rwtema.extrautils.texture.TextureMultiIcon.load(TextureMultiIcon.java:88)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:172)
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:122)

-- Resource location being registered --
Details:
    Resource location: minecraft:textures/atlas/blocks.png
    Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
    at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76)
    at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8 (x86) version 6.2
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 468543152 bytes (446 MB) / 831029248 bytes (792 MB) up to 1043595264 bytes (995 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn288M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_U_A2 92 mods loaded, 92 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    InfiniBows{1.3.0 build 20} [InfiniBows](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.62} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.62-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    debug{1.0} [debug](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    BetterTitleScreen{1.7.10-1.1} [Better Title Screen](BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1004-universal.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.2.0a} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.2.0a%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{@VERSION@} [BuildCraft](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{@VERSION@} [BC Builders](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{@VERSION@} [BC Transport](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{@VERSION@} [BC Silicon](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{@VERSION@} [BC Factory](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{@VERSION@} [BC Energy](buildcraft-6.1.5l.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.2.8} [Carpenter's Blocks](Carpenter's Blocks v3.2.8 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.13} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.13-universal.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.648-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.648-experimental.jar) Unloaded->Constructed->Pre-initialized
    CompactSolars{4.4.37.314} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.37.314-universal.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.65} [ComputerCraft](ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized
    customnpcs{1.7.10b} [CustomNpcs](CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.1.5.248} [Ender IO](EnderIO-1.7.10-2.1.5.248.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    factorization{1.7.10-0.8.88.1} [Factorization](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    EnetBridge{1.4} [EnetBridge](enetbridge-1.4.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized
    factorization.misc{1.7.10-0.8.88.1} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.1.jar) Unloaded->Constructed->Pre-initialized
    FlatSigns{2.1.0.19} [Flat Signs](FlatSigns-1.7.10-universal-2.1.0.19.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized
    funkylocomotion{1.0} [Funky Locomotion](funky-locomotion-1.7.10-beta-2.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl{2.0.0b} [Nuclear Control 2](IC2NuclearControl-2.0.0b.jar) Unloaded->Constructed->Pre-initialized
    inpure|core{1.7.10R1.0.0B1} [INpureCore](INpureCore-[1.7.10]1.0.0B1-1.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-155-5dbbb14} [Inventory Tweaks](InventoryTweaks-1.59-dev-155.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    journeymap{5.0.0RC1} [JourneyMap](JourneyMap5.0.0RC1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized
    MineMenu{1.1.8} [MineMenu](MineMenu-1.7.10-1.1.8.B40-universal.jar) Unloaded->Constructed->Pre-initialized
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9B.jar) Unloaded->Constructed->Pre-initialized
    mopickaxes{611} [Mo' Pickaxes](More-Pickaxes-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughCodecs{0.3} [NotEnoughCodecs](NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore](OpenPeripheralCore-1.7.10-0.5.0-snapshot-142.jar) Unloaded->Constructed->Pre-initialized
    OpenPeripheral{0.2.0} [OpenPeripheralAddons](OpenPeripheralAddons-1.7.10-0.2.0-snapshot-122.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-433.jar) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.2.14-29} [PneumaticCraft](PneumaticCraft-1.7.10-1.2.14-29-universal.jar) Unloaded->Constructed->Pre-initialized
    ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.5.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    Launched Version: 1.7.10-Forge10.13.2.1230
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 9.17.10.2963, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [NostalgiaCraft1.7_Midbeta_1.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by 61352151511** [comment]
@alpharulesirulee Firstly you should have made your own issue. Secondly "java.lang.RuntimeException: Likely Optifine error. Please only report if it occurs without Optifine installed:
TextureAtlasSprite.load(IResourceManager manager, ResourceLocation location) called with bad parameters."

"Please report only if it occurs without Optifine" RWTema doesn't support optifine and it messes with a lot of stuff it shouldn't.

**Comment by jena-th** [comment]
ProTip: To increase log readability, use Gist ! https://gist.github.com/ :wink:

**Comment by alpharulesirulee** [comment]
i removed optifine
