### ISSUE TITLE
Infinite Liquid using drums and fluid transposer

### ISSUE THREAD

**Issue by rickdott** [rwtema/extrautilities_old_issues#206]
Hi, you can infinitely dupe any liquid using drums and fluid transposers, the process is like this:
In this example we use a molten metal, in this case Copper.
![2014-08-02_14 54 34](https://cloud.githubusercontent.com/assets/8337434/3787938/448fd4cc-1a44-11e4-98fd-6e1a7f7fdb47.png)
![2014-08-02_14 54 38](https://cloud.githubusercontent.com/assets/8337434/3787939/4843fdc8-1a44-11e4-9d51-196dbaa70260.png)
You put a drum with any amount of liquid in the fluid transposer with the fill mode so it fills from the drum into the transposer, when the drum should hit 0 and the internal tank of the transposer the amount of liquid that was in the drum both the drum and the internal tank go to a negative value, if you fiddle with it and fill/empty a few times the internal tank goes to a huge number:
![2014-08-02_14 58 36](https://cloud.githubusercontent.com/assets/8337434/3787946/c2ef5ffe-1a44-11e4-8c4e-6ae01b83f820.png) you can then pump it out in your preferred way.
Don't know if this is a problem with Extra Utils or TE but it's been happening since at least 1.6.4 (this was tested in the FTB pack Unstable 1.0.5 for 1.7.10, it's possible in Resonant Rise from the AT Launcher too.

**Comment by rickdott** [comment]
Thought i'd comment to say that I was not the one to discover this bug, I saw it on a video posted to /r/feedthebeast when I browsed new submissions a long time ago. It was removed shortly after I saw it.

**Comment by rwtema** [comment]
It's a forge bug.

I submitted a pull request here. https://github.com/MinecraftForge/MinecraftForge/pull/1272
