### ISSUE TITLE
Latest XU crashing with Tinker's Construct

### ISSUE THREAD

**Issue by pieisnotpi** [rwtema/extrautilities_old_issues#207]
Whenever I boot up MC using the latest Extra Utilities and the latest Tinker's Construct, it crashes one of two ways: this way if I have TMechworks: http://pastebin.com/2u7nqADD and this way if I don't: http://pastebin.com/EgBLdSLY. This has been tested in an isolated environment and the crash is fixed when removing Extra Utilities. EDIT: So, the crash only occurs when using older versions of forge (such as the recommended version) but does not occur when using the very latest version.

**Comment by AlexandraIsabel** [comment]
Try with the latest version of Forge to see if that fixes it

**Comment by rwtema** [comment]
This is apparently a TCon/Forge issue. Update forge to fix.
