### ISSUE TITLE
MissingModsException with latest XU and Thermal Expansion(+required mods)

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#209]
I´m getting a MissingModsException when using the latest version of ExtraUtilities(1.1.0f)
and the latest beta builds of ThermalExpansion, TeamCofhLib, TeamCofhCore and ThermalFoundation and CodeChickenCore together with XU on my dedicated server.
They both work without the other installed.

**Comment by rwtema** [comment]
Okay... what is the MissingModsException?

**Comment by ghost** [comment]
Sorry, but I have no time atm to investigate further, but updating to the latest Forge (1194) seems to have fixed the problem. Before that I used Forge 1180 recommended version.
The missing mods exception did not say anything about which mod was missing. There where just lots of FML classes in the crash log. I don´t have the log anymore, but if you need it I will try again tomorrow after work.

**Comment by rwtema** [comment]
No that's fine.
