### ISSUE TITLE
High-temprature Furnace Generator negative energy

### ISSUE THREAD

**Issue by jordan30001** [rwtema/extrautilities_old_issues#21]
Today i was checking up on my high-temprature power generator and i noticed that my power level is -1167 so i did some testing and found out that when i was throwing everything at it it was getting to around 1200 power level and then was flipping to -1200

![image](https://cloud.githubusercontent.com/assets/3898716/2608398/3528e53e-bb6a-11e3-8ec9-4d77c936711c.png)

**Comment by TherminatorX** [comment]
Found this today. Was trying to see if the HTFG could surpass the nether star with enough fuel.
![2014-04-20_15 03 15](https://cloud.githubusercontent.com/assets/7256249/2751354/a2c37b4e-c8c7-11e3-9794-41cb86251117.png)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.

**Comment by TherminatorX** [comment]
I was hoping you'd at least check them out yourself, but I'll get to it later.
