### ISSUE TITLE
Duplication Bug- V1.1.0b

### ISSUE THREAD

**Issue by taronz** [rwtema/extrautilities_old_issues#210]
Using the new Auto Crafting system with transfer nodes, breaking a block in front of the transfer node will duplicate the block. Initially found with crafting table replacement, tested further with both Vanilla blocks (Diamond blocks) and Mod blocks (Octuple Compressed Cobblestone / Amber blocks (Thaumcraft).

More speed upgrades increase the rate of duplication apparently, averaging about 4-6 duplicated blocks per stack of speed upgrades.

Tested both with and without microblock parts near the pipes as someone else mentioned a possible dupe bug with those pipes, but made no difference, rate of duplication is consistent.

Tested with both Bound pickaxe and Iron pickaxe, the duplication effect is the same as well.

EDIT: Additional testing with other types of blocks that break apart (Clay, Glowstone) also duplicate the dusts / component parts.

ADDITIONAL EDIT: Seems that any entity thrown at the pipe will still duplicate. Threw a speed upgrade at it and got 5 into the barrel, with 3 stacks of speed upgrades, it goes up to throw one in, get 19 back.

![2014-08-03_23 39 23](https://cloud.githubusercontent.com/assets/8342484/3790691/01feb1ac-1b14-11e4-8f32-7e5e5752e083.png)
![2014-08-03_23 39 27](https://cloud.githubusercontent.com/assets/8342484/3790692/0201d152-1b14-11e4-8a42-0ec2c43ad6ab.png)
![2014-08-03_23 39 43](https://cloud.githubusercontent.com/assets/8342484/3790693/020538d8-1b14-11e4-9c78-beaa93a09149.png)
![extrautils bug](https://cloud.githubusercontent.com/assets/8342484/3790700/38fd75c6-1b14-11e4-8693-db7e5ed9edbb.jpg)

**Comment by rwtema** [comment]
What version is this?

**Comment by taronz** [comment]
1.1.0b on MC 1.7.2

**Comment by rwtema** [comment]
Already fixed.
