### ISSUE TITLE
Crash with Sounds

### ISSUE THREAD

**Issue by TheCyberTronn** [rwtema/extrautilities_old_issues#212]
I'm crashing every now and then when I travel to the Deep Dark. I have a couple of generators in the Deep Dark. I believe the sounds are causing me to crash. I crash about every 3 journeys. It also might be worth noting that these generators are x8 Lava Generators. Crash log is here: http://pastebin.com/TPdQeZL4
Thanks for the brilliant mod, Tema!

**Comment by Acters** [comment]
duplicate of https://github.com/rwtema/extrautilities/issues/205
workaround is to turn ambient/environment sounds off/0%

**Comment by rwtema** [comment]
Seriously next time take 5 seconds to check that the issue isn't already there.

**Comment by TheCyberTronn** [comment]
Sorry! Will do next time.
