### ISSUE TITLE
Watering Can Breaking

### ISSUE THREAD

**Issue by leezallen** [rwtema/extrautilities_old_issues#214]
Hi, Having a weird issue where the watering can breaks when using it by hand pretty much straight away... Has the mechanics of this changed at all?.... I can confirm that I am not using it in any type of machine, however I may have put it in a chest after using it the first time.

**Comment by rwtema** [comment]
I'm guessing some mod is replacing the players entity with custom code that is triggering the fake player detection method. I don't know what mod it is but unless they have a very good reason for doing so and not using a less super-hacky method, I don't plan on fixing it.

This is possibly related to #215. Are you using Galaticraft?

**Comment by leezallen** [comment]
I am using Galacticraft. Let me try creating it without and see if that solves the issue.

**Comment by TheCyberTronn** [comment]
I have the same issue with Galacticraft. So far, I've found that I can't get to the Deep Dark and I can't open the Golden Bag of Holding, as well as this Watering Can bug.

**Comment by scaredtodeaf** [comment]
I've posted on their issues page about the conflict issues. I don't think its an issue on rwtema's side.

**Comment by leezallen** [comment]
Fair enough... it is always hard when a conflict between two great mods like these happen.... Thanks for the update.

**Comment by radfast** [comment]
Hey.  As posted here: https://github.com/rwtema/extrautilities/issues/211
in Galacticraft we do replace EntityPlayerMP with GCEntityPlayerMP (which extends EntityPlayerMP).

We have a very good reason for doing that, namely in Galacticraft we need to change the player's: damage (if there's no oxygen), gravity, fall damage, movement (if bounding in low gravity, or if in freefall in space), orientation, and a bunch of more minor things.  Client-side there are also rendering changes for space helmet, oxygen tanks, limb movements (if bounding in low gravity, or if in freefall in space), orientation, etc.

We aim to be compatible with all other mods, as much as possible, and Galacticraft gets included in plenty of modpacks.  We would like to co-operate in resolving this fake player issue.  As posted there, it's kinda hard without seeing your sources, though if you gave permission I guess I could de-compile...

You can make contact with me on Skype at "radfast2" (United Kingdom) if that's easier.

**Comment by rwtema** [comment]
Okay fair enough. I can add a second layer of fake player detection to catch issues like this.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0g

**Comment by radfast** [comment]
That's great news, we'll pass that on to players on the Galacticraft side.  Thank you for compatibility :)
