### ISSUE TITLE
Unable to access Deep Dark

### ISSUE THREAD

**Issue by scaredtodeaf** [rwtema/extrautilities_old_issues#215]
Hi, I've creatively spawned in a deep dark portal and for some reason i am not able to travel into the deep dark. 

http://puu.sh/aFz63/d91d9fd2ce.txt This is the list of mods i have currently installed. Not sure if this is a bug.

**Comment by Acters** [comment]
can you try to make a world without Galacticraft installed and see if it fixes the issue?

**Comment by scaredtodeaf** [comment]
Yep, Galacticcraft is causing the issue, I'll post on their forums then about the issue with the deep dark. Thanks for the help.
