### ISSUE TITLE
Shift-Clicking with wrench on Drum crashes game

### ISSUE THREAD

**Issue by Limerickarcher** [rwtema/extrautilities_old_issues#218]
Shift-clicking on a drum with a wrench crashes the game. I am using FTB Unstable pack with Extra Utilities 1.1.0e, minecraft version 1.7.10. The drum is a lava drum and the wrench is a charged omni-wrench from TE. Doesn't matter if the drum is being drained or not, tested it in a separate world.

**Comment by rwtema** [comment]
Fixed in 1.1.0f.
