### ISSUE TITLE
Bug: 64x Solar Generator does not generate any power

### ISSUE THREAD

**Issue by SnowShock35** [rwtema/extrautilities_old_issues#221]
The 64x Solar Generator in version 1.1.0f does not generate any power.

**Comment by alpharou** [comment]
I agree.

**Comment by rwtema** [comment]
Well it generates the same amount of energy per unit of sunlight received.

**Comment by Porcy** [comment]
Same thing for me. 64x solar gen doesn't charge nor output anything. And I don't know if it is a bug or intended, but the 8x seems to be the exact same as the 1x. Like, it has a power level of 40 max. and stores 500 000 rf. Didn't check it's output rate as I don't have an easy was to do so.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0g
