### ISSUE TITLE
ExtraUtilities 1.1.0f Disables Vanilla Mipmapping

### ISSUE THREAD

**Issue by lanAnderson** [rwtema/extrautilities_old_issues#225]
1.7.10 w/ Forge 10.13.0.1199: http://i.imgur.com/pGcrLfU.png

1.7.10 w/ Forge 10.13.0.1199 and Extra Utilities 1.1.0f:  http://i.imgur.com/cqcSKwp.png

Both have Mipmapping set to level 4 in the video options menu and no other mods are installed

**Comment by rwtema** [comment]
Took some doing but I've found the issue. I included a texture file that was less than 16x16, which causes Minecraft to drop the mipmapping level. The texture has been increased in size appropriately (it won't make a huge difference either way).

Also by the way, it seems Thaumcraft also includes a blank 1x1 texture, and will also disable mipmapping.

**Comment by lanAnderson** [comment]
Thanks Tema.
