### ISSUE TITLE
Extra Utilities golden bag of holding won't open with Galactcraft installed.

### ISSUE THREAD

**Issue by Kazzamkablam** [rwtema/extrautilities_old_issues#227]
Extra Utilities golden bag of holding won't open with Galactcraft installed.

ForgeModLoader-Client.log.:

https://drive.google.com/file/d/0B14v7mG8vy0NT2pvejI1dldJRE0/edit?usp=sharing

https://github.com/micdoodle8/Galacticraft/issues/762
For Galacticraft's github about issue.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0g
