### ISSUE TITLE
Generator and ME Power Relay

### ISSUE THREAD

**Issue by jkauven** [rwtema/extrautilities_old_issues#23]
You can fill the buffer from a generator over the 500k with a power relay from AE. If you give the AE-System more energy than it needs, it will fill the generator up. The ME-Controller was powered with Endergenerators and in the picture you see my backup power. There was no energy in the generator when i placed it. You can not fill the generator with a dynamo or an energy cell. It is probably also a bug with AE, but the buffer from the generators shut cap at 500k and not accept Power from other sources.

Version 1.0.3a in FTB-Pack "Agrarian Skies"

![2014-04-04_12 48 18](https://cloud.githubusercontent.com/assets/5494888/2614434/131c5976-bbe7-11e3-8736-d0f304fdc8ec.png)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
