### ISSUE TITLE
Cauldron server 1.1199.01.149	1.7.10 crashing with angel ring

### ISSUE THREAD

**Issue by spikeforever** [rwtema/extrautilities_old_issues#231]
i am running a Cauldron server version 1.1199.01.149.
minecraft version 1.7.10
forge version 10.13.0.1199
extra utilities version 1.1.0 f

 i recently installed your Extra Utilities mod into my client and server and i ran it fine for a while until  i made angel rings. i immediately started using them flying about the world. i only remember loading a chunk and then _poof_ i get this error/crash.
http://pastebin.com/a1QeVQNy

now starting after that. i can no longer log back into my sever. i continuously keep getting crashed with this error.
http://pastebin.com/L3C1xt41 

my attempts to troubleshoot:
 i deleted the failing world. and attempted to recreate the crash. guess what? it happened again. i continued to re-attempt it multiple times with different wings. its seems to happen with every type of wings. 

hopefully this made any sense. if you would like me to clarify, i am more than willing.( or further researching)  thank you for your time and dedication to your mod. i really enjoy your mod.

**Comment by rwtema** [comment]
Not an Extra Utilities issue. The issue is related to client-side spawning of mobs which I have nothing to do with.
