### ISSUE TITLE
Culinary Generator

### ISSUE THREAD

**Issue by ThoBekMic** [rwtema/extrautilities_old_issues#237]
This block does not work. It will not accept any food. This is with version 1.1.0f.

**Comment by Frontrider** [comment]
I know that it has issues with non-vanilla foods. Its eats mariculture raw fishes(way to void them), but it does not eats real food from that mod, and also does not accepts anything from forestry.

**Comment by rwtema** [comment]
Unable to replicate. If a mod does not mark an item as ItemFood then it is not recognized.

**Comment by Frontrider** [comment]
Theres any way for us to mark items as food?
