### ISSUE TITLE
Cursed earth does not work with CMS/ Mo's Creatures

### ISSUE THREAD

**Issue by Pwnsaucier** [rwtema/extrautilities_old_issues#24]
I'm trying to add Mo's Creatures to the DW20 modpack, and noticing that cursed earth ceases to function when CustomMobSpawner is installed.
http://www.minecraftforum.net/topic/1080677-162-custom-mob-spawner/

This really doesn't seem like a bug with Extra Utilities, however it is a bit of an unfortunate incompatibility that I figured was worth reporting.

It's been discussed in a couple places previously:
http://gaming.stackexchange.com/questions/163245/cursed-earth-from-extra-utilities-does-not-spawn-mobs
http://forum.feed-the-beast.com/threads/adding-mocreatures-to-ftb-monster.40445/

At this point I'm going to have to either remove Mo's Creatures or Extra Utilities. Mo's creatures is going to lose, of course.

**Comment by rwtema** [comment]
Not a lot I can do about that I'm afraid.

**Comment by Gagtech** [comment]
CMS disabled vanilla spawning. There is option in the config to enable vanilla spawning. But this apparently has compatibility issues. You can disable the CMS mod completely. Mo's Creatures will still spawn, albeit a bit slower.
