### ISSUE TITLE
MFR "Intergration"

### ISSUE THREAD

**Issue by BraynStorm** [rwtema/extrautilities_old_issues#240]
So I've tested it only on the Ender Core but the MFR harvester doesn't pick Ender-Lilies at all.
Video : http://youtu.be/EwYHX96ZlAI
Using versions of mods:
- extrautilities-1.1.0g
- MineFactoryReloaded-[1.7.10]2.8.0RC2-557

Edit: Just tested the planter - it doen't work either.

**Comment by Zaflis** [comment]
Just encountered the same problem, but i have slightly older version. Good to know updating wouldn't solve it yet. RC2-557 was the latest MFR at the moment.

I am growing 9x9 farm of enderlilies on endstone, using +3 range upgrade on harvester and planter.

**Comment by rwtema** [comment]
It's not fixed yet. I just copied the old version over and didn't really test it. I'll get around to fixing it at some point, when I'm not either busy or lazy.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0k

**Comment by rehven** [comment]
Using Direwolf20 1.7.10 beta pack, ExtraUtils 1.1.0k, and MFR [1.7.10]2.8.0RC3-591, I'm still having no success with both Planter and Harvester. I didn't see anything obvious in configs; do you know if Dire disabled ender lily automation through MFR (maybe in favour of Thaumcraft)?

**Comment by eldblz** [comment]
@rehven we have the same problem with Direwolf 1.7.10 ver 1.0.1

**Comment by starryknight64** [comment]
Mentioning #340 since this issue was closed a while ago.
