### ISSUE TITLE
World Crash waiting for AE2 crystals to grow

### ISSUE THREAD

**Issue by b0bst3r** [rwtema/extrautilities_old_issues#241]
http://pastebin.com/JUkveuG3

I use a transfer node with a world upgrade in it and filter waiting for AE2 crystals to grow, on loading world I freeze or crash out and get the above.

**Comment by rwtema** [comment]
Looks that  the world had a tile entity mismatch. I've added a catch for the crash but this is technically  corruption and you may have a bigger issue.
