### ISSUE TITLE
openblocks stops ExU wings from rendering

### ISSUE THREAD

**Issue by luchokoldo** [rwtema/extrautilities_old_issues#242]
Hi, idk if u know about this issue;

https://github.com/OpenMods/OpenBlocks/issues/470

**Comment by nevercast** [comment]
Clearly we're both changing the player renderer, perhaps we can improvise some compatibility so that both the gliders and the ExU wings work? Cheers

**Comment by rwtema** [comment]
I'm not changing the renderer, I'm using RenderPlayerEvent. It's a bug on my end don't worry about it.

**Comment by rwtema** [comment]
Fixed in 1.1.0h
