### ISSUE TITLE
Cast exception in block.BlockColor

### ISSUE THREAD

**Issue by MrIngelborn** [rwtema/extrautilities_old_issues#243]
Using Extra Utilities blocks with painted blocks from Ender IO or Carpenters Blocks will crash the client and give a cast exception in the crash-report.

Using Forge version 10.13.0.1202
and Extra Utilities version 1.1.0g

Crash report: http://pastebin.com/xuEP7tiW

**Comment by rwtema** [comment]
Fixed in dev
