### ISSUE TITLE
Null pointer exception, item transfer node, auto crafting, v1.7.10-1.1.0g

### ISSUE THREAD

**Issue by Ronzan** [rwtema/extrautilities_old_issues#244]
Hey,

I got this crash log, even after a server reboot.
http://pastebin.com/ypGwRm3t

**Comment by rwtema** [comment]
It looks like someone is not properly implementing the getTankInfo method of IFluidHandler. I'll add a catch for it on my end but ultimately the issue is with whatever the tank is.

**Comment by Ronzan** [comment]
Cool, thanks :)
