### ISSUE TITLE
Feature Request: Ability to toggle transfer node particles visibility via a config option

### ISSUE THREAD

**Issue by Adamvg** [rwtema/extrautilities_old_issues#246]
Can get annoying, and causes some clientside lag. An option to enable/disable the visibility of said particles would be nice. I remember there was an item which displayed the particles in previous versions. Maybe this could be enabled via config?

**Comment by rwtema** [comment]
You mean like the already existing disableTransferNodeParticles? Check the damn config before asking for config options.

**Comment by Adamvg** [comment]
Sorry, I must have missed it haha. Great mod by the way ^_^
