### ISSUE TITLE
Magnum torch info page lists the wrong radius.

### ISSUE THREAD

**Issue by jmonsted** [rwtema/extrautilities_old_issues#25]
On the "info" page for the magnum torch, radius is listed as 64, but it prevents spawns in a radius of 128.

**Comment by Syer10** [comment]
radius means half, I think you mean a diameter of 128 so he has the right wording

**Comment by jmonsted** [comment]
Nope, i placed it less than 128 blocks away and it prevented spawns. Radius is what i meant.

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
