### ISSUE TITLE
Ender-Thermic Pump problem.

### ISSUE THREAD

**Issue by UnPure** [rwtema/extrautilities_old_issues#250]
Hey there.
I'm currently using the latest version of ExtraUtilities with Forge 10.13.0.1200.
It seems like there are some problems with the Ender-Thermic Pump.
I'm trying to use it in the nether to pump lava into an endertank from the EnderStorage mod.
On 1.1.0f everything works fine. But on 1.1.0g not.
The pump replaces the lava with stone and lava is filled in the tank.
After 10-15min. the pump stops because its surrounded with stones.

Sorry for my bad english. I hope its not to hard to understand.

**Comment by Zaflis** [comment]
Ender-Thermic Pump is not doing anything for me, not even turning lava to stone. I have it placed vertically like: lava, empty (or netherrack), pump. Ender tank directly on top of the pump, but also tried extracting with EnderIO fluid pipes from sides. It simply doesn't pump anything in nether.

In config it looks like:
I:EnderPumpDimensionExceptions <
     >
B:disableEnderPumpInAllDimensions=false

And yes i have powered it up with RF, with 1 TE magmatic dynamo full of lava fed with buckets.

edit: It didn't work with 1.1.0f version either so i tried putting the pump down 1 block level. That fixed it for me.

**Comment by rwtema** [comment]
No idea. Not enough info.
