### ISSUE TITLE
ender transmitter/receiver problems

### ISSUE THREAD

**Issue by black3agl3** [rwtema/extrautilities_old_issues#252]
version 1.1.0g, single player

I have a chest with a transfer node and a stack of ender transmitters and a stack upgrade transmitting to another transfer node with a ender receiver. Everything works fine when I place them down. 

However, when I relog, the transmitter takes items out of the first chest but the items don't appear in the second chest.

---

I tried testing various situations and I get varying results. Sometimes the items get stuck in the transfer node with the ender transmitter, sometimes the items simply get voided. Most of the problems seem to come from the fact that I relog.

---

Also, the only way to reset everything seems to be breaking all the transfer nodes and connected inventories and then replacing them.

---

Might be related to #26 
I'm using forge 10.13.0.1207

I also have the transmitter and receivers on public spectrum if that matters.

**Comment by rwtema** [comment]
Should be fixed in newer versions.
