### ISSUE TITLE
Bug: Painted quartz localization is broken

### ISSUE THREAD

**Issue by SnowShock35** [rwtema/extrautilities_old_issues#253]
Version: 1.1.0g
Problem: Colored quartz localization is broken
Displays as: tile.quartzBlock.name
![2014-08-18_10 37 19](https://cloud.githubusercontent.com/assets/8388680/3949757/5e59caf6-26bb-11e4-871e-f81be4b43f0e.png)

**Comment by rwtema** [comment]
Technically a vanilla bug. I've worked around it in the next version.
