### ISSUE TITLE
Suggestion: Increase Energy storage of tiered Generators

### ISSUE THREAD

**Issue by RoyalBingBong** [rwtema/extrautilities_old_issues#257]
I think it kind of makes sense to increase the energy storage of the generators with increasing tier:
1x Generator: 500k RF
8x Generator: 4M RF
64x Generator: 32M RF

**Comment by TherminatorX** [comment]
I support the idea, even if you don't take suggestions.

**Comment by rwtema** [comment]
Will think about it
