### ISSUE TITLE
[BUG] Failed to handle packet -> Unable to Connect to Server

### ISSUE THREAD

**Issue by Kradxn** [rwtema/extrautilities_old_issues#258]
After updating to extrautilities-1.1.0h and  playing some minutes i got kicked and was unable to reconnect : 
Server Log: http://pastebin.com/6K55fmXx 
Full Log: https://docs.google.com/file/d/0B3WRbM3Yy_XwUTJLenQybjJJNGc/

**Comment by rwtema** [comment]
Should be fixed in 1.1.0i
