### ISSUE TITLE
Mipmap causing huge FPS lag

### ISSUE THREAD

**Issue by hisorange** [rwtema/extrautilities_old_issues#259]
Aye after 1.1.0f the releases causing a crazy fps lag if the mipmap turned on, peeps mentioning in the mc forum too. A ticking texture eating up the CPU what I can tell from the debug screen.

Hope you can find the root of this issue, best regards!

**Comment by rwtema** [comment]
are you using a texture pack?

**Comment by hisorange** [comment]
Nope, it's really interesting since even if i turn the mipmap off a texture is ticking with the new versions even in a raw superflat without any block placed.
I will run some tests today, it may be caused by some cross mod compability.

**Comment by rwtema** [comment]
There are absolutely no ticking textures in Extra Utilities if vanilla textures are used.
