### ISSUE TITLE
Ender receptor/transmitter bug

### ISSUE THREAD

**Issue by luchokoldo** [rwtema/extrautilities_old_issues#26]
Hi, first sorry for my english; I think is a bug.. when I Save my world SP and open later, ender receptor dont recibe energy.. i need remove and put it again.. I dont chage the frequency.. 

off: nace prank to dire tema :p

**Comment by maop** [comment]
Hi, 

I Second this. Whenever the chunk, in which one receiver is placed, is unloaded when reloaded it stops receiving, and only when you update the energy node by placing one more upgrade or moving the receiver it starts powering up again...
I have test one energy node without chunk loader and one with a chunkloader, only the last keeps receiving energy.

**Comment by luchokoldo** [comment]
Hi, i have both in chunkloader;

http://imgur.com/pCKliE3

in this picture you can see the 2 nodes; isnt be too far away; and if you know Opis you can see the blue mark in te corner are the chuncks are force loaded and the green are loaded by the player;

this are the nodes;

http://imgur.com/ncXMtmJ

http://imgur.com/aF4oLD3

This is my SinglePlayer map; this happen when a close the map and startup;

sorry for my english; I try to write the best I can; if u need anything just tell me

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
