### ISSUE TITLE
Not working with thermal expansion

### ISSUE THREAD

**Issue by derp1112** [rwtema/extrautilities_old_issues#260]
Extra utilities is apparently using an outdated RF. Extra utilities is one of my favored mods for modpacks but doesn't work with a lot of 1.7.10 mods.

-Thanks

**Comment by SnowShock35** [comment]
That's a problem with your end I have thermal expansion and a bunch of other mods with extra utilities in 1.7.10 its fine you might be using the wrong version of one of the mods make sure you have

Extra Utilities-1.1.0h
Thermal Expansion-4.0.0B3-11
Thermal Foundation-1.0.0B1-6
CoFH Core-3.0.0B3-26
CoFH Lib-1.0.0B3-20
Forge-10.13.0.1207
