### ISSUE TITLE
[1.1.0h] QED/Pillar Crash

### ISSUE THREAD

**Issue by BevoLJ** [rwtema/extrautilities_old_issues#264]
Updated to 1.1.0h and been getting a few of these reports coming in. (Both Forge and Cauldron servers- Only mod required to reproduce is Extra Utilities)

Crash Log: https://gist.github.com/BevoLJ/7fa24cf016065856986f
Forge Log: https://gist.github.com/BevoLJ/c3fac6cf9f8c46977ffa

How to reproduce: Put ExU on Forge server and place QED and a few pillars.  It normally doesn't directly crash when the pillars are placed (though sometimes it does) but if you leave that chunk (just one over works every time) and then move back into that chunk you will crash.  Dunno how that is possibly a thing _shrug_, just found it to be a thing from my testing. lol

**Comment by rwtema** [comment]
Should be fixed in 1.1.0i

**Comment by BevoLJ** [comment]
Just updated the pack to 1.1.0i last night before bed, and all indications are that all is well!  Thanks.
