### ISSUE TITLE
MFR integration crashes with COFH core dev version

### ISSUE THREAD

**Issue by tbung** [rwtema/extrautilities_old_issues#265]
ExtraUtils with version 1.1.0g and later (with MFR integration) crashes with MFR-2.8.0rc2-557

There seems to be a problem using IFactoryPlantable.

Crash report: https://gist.github.com/Tafiir/36ead815229a6ca0df5b

**Comment by BraynStorm** [comment]
It doens't look like a ExU problem. Did you froget to put COFH Core and Lib in the mods folder ? MFR requires it now. Also I don't have problem with the same MFR and latest ExU.

**Comment by tbung** [comment]
Ok, tracked it down, its a problem with the dev version of COFH core. It works with the standard version.
