### ISSUE TITLE
Connected textures face the wrong way on bottom-facing *microblocks*

### ISSUE THREAD

**Issue by eilamg** [rwtema/extrautilities_old_issues#266]
Same as #245, only with microparts placed on the bottom side of the block space rather than the blocks themselves.

**Comment by rwtema** [comment]
Unable to find what you're refering to, please provide a screenshot.

**Comment by eilamg** [comment]
![2014-08-30_14 52 39](https://cloud.githubusercontent.com/assets/4570254/4098863/7434cc1a-303c-11e4-9a0f-312e5aa2cff1.png)
Taken on Forge 1208 and Extra Utilities 1.0.0j
Of the three in the foreground, the two on either side are normal blocks and the middle one is obviously a microblock cover.
The three in the background are all solid blocks

**Comment by rwtema** [comment]
Gotcha

**Comment by rwtema** [comment]
Should be fixed in 1.1.0k
