### ISSUE TITLE
[1.1.0i] Ender Quarry will not accept more than 1k RF/t

### ISSUE THREAD

**Issue by tivec** [rwtema/extrautilities_old_issues#268]
I have a system set up that outputs 1920 RF/t (magmatic dynamos with upgrades) into enhanced power conduits from EnderIO. The conduits are capable of 5120 RF/t, but the quarry refuses to accept more than 1K, even if I do have a gold speed upgrade (x5 power drain).

Picture of my setup:
![2014-08-23_07 03 49](https://cloud.githubusercontent.com/assets/717574/4019704/e7ca176c-2a82-11e4-9eeb-b540121b0fa0.png)

**Comment by rwtema** [comment]
Oops forgot to remove the input cap. Will fix.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0j
