### ISSUE TITLE
Placing walls freeze mc client

### ISSUE THREAD

**Issue by kantally** [rwtema/extrautilities_old_issues#269]
Walls are bugged somehow, i get client freeze without any crash report right after i place a few of them. Doesnt matter what kind, after placing down a few, client freeze so i have to end proccess and delete walls in MCedit to be able log back into world. Tried on server too and others got same problem.

Log from console when trying walls in solo world:

SEVERE: Unusable texture for BlockMD [ForgeMultipart:block meta 0], icon=blank_16,texture coords 1328,880 - 1344,896

**Comment by rwtema** [comment]
Apparently this is an issue with COFH render sorting

**Comment by digitalseraphim** [comment]
Is the COFH team aware of this issue? Do you know of any work arounds?

**Comment by digitalseraphim** [comment]
For anyone else that found this thread first, here's a link to a thread where BevoLJ talks about his dealings with the issue: https://github.com/rwtema/extrautilities/issues/238
