### ISSUE TITLE
Fluid Transposer+Barrel = Infinite fluid

### ISSUE THREAD

**Issue by niteforce** [rwtema/extrautilities_old_issues#27]
Just put a lava/water/... barrel in a Fluid Transposer, it will go under zero and starts counting reverse in negative.
Its the 3.0.0.2 version of Thermal Expansion, and Extrautils 1.0.3c

![2014-04-13_19 38 07](https://cloud.githubusercontent.com/assets/6392625/2690182/531096e8-c333-11e3-9417-58abbecdac6c.png)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.

**Comment by TherminatorX** [comment]
dupe issue #22
