### ISSUE TITLE
RF Loss when Send rate greater than Recieve Rate

### ISSUE THREAD

**Issue by Vyrebird** [rwtema/extrautilities_old_issues#270]
I'm not sure if this is ultimately a bug in EU or TE, but it's somewhere in their interaction.

If you use an Energy Transfer Node to exchange RF between a source and a sink (say, two energy cells), if the sender's transmit is higher than the receiver's receive rate, RF will be lost.

The easiest setup to test this with is a (full) Leadstone Energy Cell, and a (empty) Hardened Energy Cell.  Dump the Leadstone into the Hardened - that will transmit successfully, usually lossless.  Now switch the input/output on the cells, so the Hardened empties into the Leadstone.  When completed, the Leadstone will have approximately 50% of the RF it should.  The problem is not unique to this setup - the same issue arises between two Redstone Energy Cells, for example, if you lower the Receive rate of one while leaving the Transmit of the other alone.

I have not tested if the behavior changes with larger networks or when pipes are involved - I've only tested with simple 3-block (cell) (transfer node) (cell) setups.

**Comment by BraynStorm** [comment]
I noticed something similar with Dynamo with full x8 Enery Production Augments hooked to a Energy Transfer Node and it seemd like it wasted most of the RF. Mhm....

**Comment by Vyrebird** [comment]
When the send and receive rates are similar, the behavior is inconsistent - ie 2000 send / 1900 receive sometimes loses energy, sometimes transfers lossless.  I'm not sure what causes it to work sometimes but not others.

When the receive rate is half, or less, of the send rate, the loss seems to reliably be 50%.  ie 2000 send / 1000 receive is 50% loss, as is 2000 send / 100 receive and (the most extreme I can test) 10000 send / 1 receive is still 50% loss.

(again, testing has been with TE Energy Cells, generally using 80k RF (from a Leadstone battery in a Enervation Dynamo - seems the quickest & easiest test setup I can find) as the base energy to transfer.  I've mostly tested with the same Cell-Node-Cell setups; I've done a handful of tests involving energy pipes, and the same issue is present, so leaving them out just keeps it simple.  The issue is present both for devices' native send/receive (ie Resonant Energy Cell -> Magma Crucible (Basic)) and for configured differences (ie messing with the Energy Cell's Input/Output values)).

**Comment by rwtema** [comment]
Found the issue - it will be fixed in the next version.
