### ISSUE TITLE
[1.1.0i] Deep Dark TPS Lag

### ISSUE THREAD

**Issue by Erelaszun** [rwtema/extrautilities_old_issues#272]
I currently have one large zoned ender quarry, and ender chest in the Deep Dark (nothing else is there), I tested this with a Tesseract from TE, and with a Transcever from EnderIO... if a player is not in the deep dark, tick time jumps up to 35ms. However if a player is in the Deep Dark, the tick time drops back down to 4ms. While this alone isnt enough to cause TPS Lag... with the overall lag from overworld, nether, etc... it starts to show up in the overall (using /forge tps)

If I have a speed 1 upgrade... Tick time in the Deep Dark jumps to 50 - 55ms... with speed 1 and fortune 1, I saw over 60ms tick time. (only while no players are in the deep dark, when a player is there... no issue, steady at 4 - 4.5ms tick time

This was not an issue in previous version.

**Comment by Erelaszun** [comment]
Did another test, this time, with no Ender Quarry upgrades... it jumped to 50ms tick time

![2014-08-23_22 51 21](https://cloud.githubusercontent.com/assets/8336490/4022467/f2212e64-2b39-11e4-8a87-24203d768f19.png)
![2014-08-23_22 51 49](https://cloud.githubusercontent.com/assets/8336490/4022466/f218d94e-2b39-11e4-8abb-b86990ace8e8.png)

**Comment by rwtema** [comment]
Is the quarry next to a chunk boundary?

**Comment by Erelaszun** [comment]
Actually it is. which is why I had power on the side, instead of the back. Known Bug?

**Comment by rwtema** [comment]
Try moving it and the power system to within the chunk.

**Comment by rwtema** [comment]
This could be anything causing it. If it isn't fixed then I can't help you.
