### ISSUE TITLE
Server crash when autocrafting near a buildcraft transport pipe

### ISSUE THREAD

**Issue by ANerdyElva** [rwtema/extrautilities_old_issues#274]
When using autocrafting via a world interaction upgrade in an item transfer node the game crashes if it tries to check a Buildcraft Transport pipe as part of the recipe (any type as far as I can tell, tried diamond and cobblestone).

The crash does not occur if no world interaction upgrade is present or the transfer node is full.

Crashing setup: 
![2014-08-24_17 55 09](https://cloud.githubusercontent.com/assets/800214/4023794/0b0301b0-2ba7-11e4-8aff-a82a68d13e66.png)

Crash log:
https://gist.github.com/KevinVDVelden/1d0f90f8c2d6ff25304f

Edit, forgot to add:
This is version 1.7.2 of minecraft with version 1.1.0b of extra utilities.

**Comment by rwtema** [comment]
Fixed in newer versions
