### ISSUE TITLE
1.1.0i Ender Quarry stop working

### ISSUE THREAD

**Issue by Keridos** [rwtema/extrautilities_old_issues#277]
I have the problem that my Enderquarry  (with Fortune III upgrade) will always stop after a few thousand blocks it has mined, I tried putting an chunkloader under it with enought range to cover the whole mining operation but it still stops after a few thousand blocks. Might be another bug with it? Even putting a normal chest over them and feeding energy via pipes into them does not make them return to working, just picking them up then replacing them helps.

**Comment by rwtema** [comment]
Unable to replicate. Try again in 1.1.0k.

**Comment by Keridos** [comment]
Had it on 1.1.0k again, after a few hundred thousand blocks our quarry stops working sometimes.
Screenshot of the setup I used: https://imgur.com/a/XH6kR The conduits are EnderIO ones (as directly connecting th tesseract makes it fail the same way. It still uses power but does not mine any blocks.
Maybe it happens when either energy or item flow is stopped. f.ex when the chest is full?

Our Quarry in the bedrock age (from TT:KAMI) seems to have no such problems, but it only ran for like 10 hours yet.
