### ISSUE TITLE
[1.7.10 1.1.0i] Deep Dark + Night Vision = No Vision

### ISSUE THREAD

**Issue by 61352151511** [rwtema/extrautilities_old_issues#279]
I'm not sure if this is an intended feature or not. A few versions ago (Not sure exactly which version) I was able to use night vision in the deep dark perfectly fine. Recently however I've been experiencing a completely black screen whenever attempting to use night vision inside of the deep dark. It only happens within the deep dark. It could be a number of other mods affecting it, I do not have optifine installed so it wouldn't be that, however anything is possible so here is a list of mods.

> Advanced Machines, Applied Energistics 2
> BDLib, Bibliocraft, Blood Magic, Botania, Brewing API, Buildcraft
> Carpenter's Blocks, Chisel, ClashoftLib, CodeChickenCore, CoFHCore, CoFHLib
> CompactSolars, ComputerCraft
> Dimensional Anchors
> Ender Storage, Extra Utilities
> Forestry
> Gendustry
> Immibis Core, IndustrialCraft, Inventory Tweaks, Iron Chests
> Liteloader
> Mantle, Mekanism (Generators & Tools), Minefactory Reloaded, Minestrappolation
> Not Enough Items (& Addons)
> OpenBlocks, OpenModsLib
> Pam's HarvestCraft, Pneumaticraft
> Railcraft, Redstone Arsanel,  Resonant Engine
> Secret Rooms
> Tinkers Construct, Thaumcraft, Thermal Expansion, Thermal Foundation, Tinkers Mechworks
> Universal Electricity
> WAILA

Sorry the list is so long. If this is not a bug and intended feature then please let me know. If it is a bug but you can't reproduce it again let me know and I will go through this list and find out which mod is conflicting. All mods are the latest version as of August 26th 12:00 PM GMT, Forge is one version behind (10.13.0.1207)

Here is a video demonstrating the issue. It may be some functionality added by blood magic to prevent the night vision modifier on bound armor being too over powered, or the functionality may be added by you. https://www.youtube.com/watch?v=tprH5jVECmw

**Comment by SnowShock35** [comment]
Its intended so you can't use night vision the idea is it is DARK hence the name DEEP DARK

**Comment by 61352151511** [comment]
I'd like an official word on this either on a wiki or on the forum thread or from RWTema, because as I've said it's not in any changelog unless I'm blind and can't see it after triple checking, and it worked fine not that long ago. I do realise it is called the deep darp and intended to be dark, so it would make sense, but I'm unaware when/if the change was made so it confuses me.

**Comment by rwtema** [comment]
It's not intended - it's a forge bug. I don't remember any of the details though.
