### ISSUE TITLE
Ender Generator Bug

### ISSUE THREAD

**Issue by maki-q** [rwtema/extrautilities_old_issues#28]
Sometimes when placing ender generators, they will not accept ender pearls and will not output power. When I tried it on a stack of ender generators, 18 of them would not function.

![untitled](https://cloud.githubusercontent.com/assets/7294363/2699968/b00b7194-c40d-11e3-9e48-c6af339fd171.png)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
