### ISSUE TITLE
Sound muffler doesn't work on ITickableSounds

### ISSUE THREAD

**Issue by unpairedbracket** [rwtema/extrautilities_old_issues#280]
I'm currently investigating moving Mekanism to the vanilla/forge sound system, partially so that our machines will work with your Sound Muffler. In this process I have found that the muffler appears to have no effect on sounds that implement `ITickableSound`.

In debugging I have discovered that while regular sounds are turned into `SoundMuffled` on the play event (these work), tickable sounds are turned into `SoundMuffledTicks`, which contains a `muffler` field that is always null - presumably this is incorrect, and it should be set to the closest muffler?

**Comment by rwtema** [comment]
ITickableSounds are no longer supported since these have arbitrary predefined logic that may or may not crash when replaced.

**Comment by unpairedbracket** [comment]
Ah, OK. That's a shame, but it makes sense.
