### ISSUE TITLE
Angel block can be placed and picked up anywhere

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#281]
Hey,

I run a Cauldron server and created a WorldGuard 6 protection in the world. When I do not have permission to place, break or use blocks in this area, I can place and break  angel blocks, bypassing the protection. Is it possible to pass events for these at so Bukkit can pick up and cancel these events from occurring?

Thanks!

**Comment by rwtema** [comment]
No idea and I'm afraid I can't support bukkit or custom plugins.
