### ISSUE TITLE
Feature request: Restrict Ender Quarry height

### ISSUE THREAD

**Issue by FredMSloniker** [rwtema/extrautilities_old_issues#282]
Would it be possible to add some mechanism for restricting how high an ender quarry mines? My specific issue is that, unless my small-scale testing has misled me, I can't use an ender quarry under someone's sky fortress without 'quarrying' it. Maybe have it only mine as high as the highest fence block in its boundary?

**Comment by rwtema** [comment]
It should only go 4 blocks higher than the enderquarry's level (or max level of a fence boundary)

**Comment by Radst0ne** [comment]
But maybe a restriction how deep the quarry can mine? By just placing a Y Coordinate Ender-Marker?

**Comment by xenxero1** [comment]
> rwtema closed this on *Aug 29, 2014*
