### ISSUE TITLE
NPE Crash when disabling Decorative_#Enabled

### ISSUE THREAD

**Issue by Xalcon** [rwtema/extrautilities_old_issues#283]
I tried to remove the fences and pipe jackets but the only settings I've found are Decorative_1Enabled and Decorative_2Enabled (would be nice to have some information about what those options exactly do, since they aren't realy descriptive), but when setting those (either one of them) to false lets the game crash on startup. 

Forge 10.13.0.1208
ForgeMultiPart 1.1.0.300
ExtraUtilities 1.1.0j (also tested on 1.1.0i)

Crashlog:
http://pastebin.com/ehhAp5yf

**Comment by rwtema** [comment]
Decorative1/2 are utility blocks for recipes and such. Do not disable them. Try microBlocksEnabled.
