### ISSUE TITLE
1.1.0j Cannot craft Frosted Stone

### ISSUE THREAD

**Issue by tgstyle** [rwtema/extrautilities_old_issues#285]
In NEI, the recipe for Frosted Stone shows Ice as Unnamed. Placing the recipe in a crafting table with Ice does'nt work.

**Comment by rwtema** [comment]
Are you using MFR?

**Comment by tgstyle** [comment]
Yes MFR is installed.

**Comment by rwtema** [comment]
It's almost certainly related to MFR replacing the ice block. It should be fixed with Forge's new alias system.
