### ISSUE TITLE
EnderQuarry Speed upgrade bug

### ISSUE THREAD

**Issue by Beamfield** [rwtema/extrautilities_old_issues#287]
I guess the Speed upgrade is broken for the Ender Quarry, it seems like if you put the speed 3 upgrade(tested with a creative 20k energy cell) it speed ups, and if you wait a little bit it slows down(I think this is because the 1000RF/t max storage and the power multiplier bug.)

**Comment by archmon** [comment]
Frankly for myself, once I found that the multiplier was upped from x10 to x80, I just removed it.  No way I can right now produce that much power.

**Comment by dullemarc** [comment]
Having the same problem, speed upgrade wont work

**Comment by rwtema** [comment]
Unable to replicate.
