### ISSUE TITLE
Angel Ring not flying

### ISSUE THREAD

**Issue by Towsty** [rwtema/extrautilities_old_issues#288]
I made an angel ring using ExtraUtilities version K and it will not fly. Flight is enabled on the server, other flying options work, not really sure what else to say. Anyone else having this issue?

**Comment by exzhawk** [comment]
A might workaround is take the ring off. e.g. throw it on the ground. then take it on again.

**Comment by Towsty** [comment]
Tried that before, no dice. 

—

**Comment by Towsty** [comment]
So this was not an ExtraUtilities issue and can be closed. Basically the armor I was wearing (chaotic armor from chaotic class) was inhibiting the flight for some reason.
