### ISSUE TITLE
1.1.0k Crash ItemHeatingCoil

### ISSUE THREAD

**Issue by Moonchu** [rwtema/extrautilities_old_issues#289]
Getting this crash on launch: http://pastebin.com/F3UdSicY

**Comment by rwtema** [comment]
It seems to not be finding the 'RF energy item' class. Not sure why this would be offhand. I'd speculate that perhaps some mod is not shipping the entire RF API and it's given preference over Extra Utilitie's version of the RF API. In any case, the code is included in XU.
