### ISSUE TITLE
EnderQuarry being deleted

### ISSUE THREAD

**Issue by YogsMcree** [rwtema/extrautilities_old_issues#29]
It appears that when you have a quarry in the Deep Dark , both the ender and BC quarry,it will delete the quarry after some time and they will go to oblivion, making me a sad panda. It has happened a few times and thought you would like to know

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
