### ISSUE TITLE
Ender Quarry Consume Power While Stalled

### ISSUE THREAD

**Issue by magerooster** [rwtema/extrautilities_old_issues#293]
My ender quarry will start up properly but then only run to the first 1 to 20 or so blocks and then stop. It continues to consume power and upgrades do not affect anything. Exactly how far it gets varies _slightly_ but for a given test location will generally run to the same spot, but not always. (I've broken the quarry, started it back up again and it'd go to say, 10 blocks scanned instead of 8)

Blocks ARE replaced with dirt to the point it stops, and the stopping point doesn't have anything unusual about it, just ordinary stone or netherrack. Waiting for long periods of time (hours) does not yield any further progress. It does not matter whether I use a fence or ender markers. I have tried large (64x64ish) and small (3x4ish) areas. I have tried nuking the config file.  I have tried several different sorts of generators, both from EIO and EU. They all behave as if the quarry is consuming its normal level of power, but the quarry makes no further progress. 

Reproduced in single player/multiplayer forge/multiplayer cauldron and with 1.1.0i and 1.1.0j, using various forges in the range of 1207 to 1212, varying in pack size from a full 80 mod pack down to EU completely by itself and on freshly generated and upgraded-from-1.7.2 maps. I definitely did not have this problem during 1.7.2.

**Comment by magerooster** [comment]
...I guess one can never test TOO thoroughly. Apparently, my problem was that it stopped wanting to eject the items into the dimensional transceiver directly (which it was doing fine in 1.7.2) and wanted a chest.

(When I was testing it alone without EIO, I was forgetting to put a chest next to it. Durr.)

Still, there's an oddity there and I'm not sure who's bug it is.

**Comment by magerooster** [comment]
I'll just rewrite the bug as the part that's actually a bug... unless the quarry is supposed to consume power when it has nowhere to send items.

**Comment by rwtema** [comment]
Intended. It will consume power when stalled.
