### ISSUE TITLE
ender markers don't drop when block below is broken

### ISSUE THREAD

**Issue by archmon** [rwtema/extrautilities_old_issues#294]
Not sure if it is intended or not, but just noticed that ender markers don't drop when you break the block below them.  

![2014-09-03_21 04 19](https://cloud.githubusercontent.com/assets/7947536/4144072/d9ae2e1c-33d7-11e4-8ff0-1d6c70a28509.png)
Using version 1.1.0j

**Comment by rwtema** [comment]
It's intended.
