### ISSUE TITLE
Request: The world is square 

### ISSUE THREAD

**Issue by smiletactician** [rwtema/extrautilities_old_issues#295]
Hey man,

Thanks for the awesome mod. Your doing really good work. I'm sure you know. I don't mind if you dismiss the idea, its just an idea or request per say. If you do dismiss please comment on which grounds. I like to be in the clear. 

So, I'm looking at the drums and i think there ace but i never use them. I was wondering If you could add a recipe to make them square. odd i know, cause everything is square (mostly, i do like the impossible shapes) I feel they are odd looking and mainly out of place but would work just as well as a square or more oblong shape. That is all :D

**Comment by rwtema** [comment]
No

**Comment by rwtema** [comment]
Sorry if I came off as a bit rude but.... still no.

**Comment by smiletactician** [comment]
A bit off slightly maybe but its fine now you've made apology for it's strength. Sorry to hear that but i'm sure you have there best interests and your own at heart. I was actually chuckling a little bit at the abruptness  :D
