### ISSUE TITLE
Item Duplication Bug. (Filing Cabinet)

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#296]
This is a bug that requires one player to be accessing the filing cabinet whilst it is broken and then replaced. 

The filing cabinet is removed, the player pulls items out the inventory. Then placing the filing cabinet which has an extra copy of what ever the player removed. 

(Done with 2 players this bug works very easily with the other player breaking and then placing the filing cabinet)

[Note:I was unable to test in the latest version, however I did not see any change log on this.]
[Extra Note: I was only able to test this in the Monster Pack. However, I believe it's a secret bug]

**Comment by rwtema** [comment]
This is a 1.6 bug, long since fixed.
