### ISSUE TITLE
Feature Request: 'Pre-evaluation' Transfer Node upgrade

### ISSUE THREAD

**Issue by TehSomeLuigi** [rwtema/extrautilities_old_issues#298]
I have a suggestion for a transfer node upgrade, but I don't know a good name to put to it. 'Pre-evaluation' will therefore be my name suggestion, but you can probably come up with a better name.

The upgrade would change the behaviour of the transfer nodes so that:
- If the container it is extracting from is empty, do nothing, do not travel, etc.
- When it advances to a container in the transfer pipes, it will extract at most only the items/fluids that can fit into the destination container and insert them immediately into the destination container.

In other words, I would like some way to prevent the transfer nodes having an internal buffer, so that the items/fluids are transferred directly from container to container, and not buffered if they cannot fit into the destination.

By doing so, only what can fit into the destinations will be extracted. Currently, other kinds of items/fluids will get blocked by the presence of other items/fluids already present in the buffer.

I hope you can understand my suggestion, I sometimes have difficulty putting my thoughts into words, so if you need clarification, please ask.

**Comment by rwtema** [comment]
No. This is not how transfer nodes should work.
