### ISSUE TITLE
Can't trigger stabilization ritual with a custom beacon

### ISSUE THREAD

**Issue by ephys** [rwtema/extrautilities_old_issues#301]
Because you're using getClass().equals(TileEntityBeacon.class) instead of instanceof, custom beacons that extend the vanilla beacon (and in my server's case, replace it) are not valid for the stabilization ritual.

**Comment by rwtema** [comment]
So use a regular beacon.

**Comment by ephys** [comment]
There isn't any, there wouldn't be much sense having a beacon with different mechanics if there is a cheaper version of it doing the same thing.

If you mind the performance drop between .equals and instanceof there are other ways to detect if the beacon is in range (like storing the beacon's location in the division sigil nbt ?)

**Comment by rwtema** [comment]
Sorry but I'm not going to support mods that remove blocks without good reason.

**Comment by ephys** [comment]
The block is not removed, it's replaced. Everything would work just fine by replacing that one line by instanceof.
