### ISSUE TITLE
Nether Star Generator x64

### ISSUE THREAD

**Issue by Lord-Mimir** [rwtema/extrautilities_old_issues#303]
When testing different Generators in the mod found that with current hard set max power for all tiers of the generator, the Nether Star generator when upgraded to the 64x generates 2,560,000 RF a tick but due to max Storage in generator all but 500,000 RF it lost.  at the 8x level the current max handles the 320,000 RF a tick without issue, only runs into problems when using the 64x version.    I am unsure what a person would ever need the 2.5 million RF a tick for as most power systems can not transfer that much a tick but thought would bring up the issue, as i have seen other posts asking about tiered max power based on tier of the engine.

**Comment by rwtema** [comment]
No point in fixing this. You would never need a 64x generator.

**Comment by buglord** [comment]
either quick-fix it by setting internal buffer capacity to over 2,560,000 or remove it entirely if you're not gonna make it functional.

**Comment by Sailren** [comment]
disable the 64x generators in the config, problem solved

**Comment by Frontrider** [comment]
I saw only a single mod, whitch could use up that mutch energy. Its the still work in progress technomancy.

**Comment by Hakameda** [comment]
It would be cool if it worked, Atm i have 25 steam turbines at 28k/t. Instead of all those i was planning to run a 64x generator. Currently with those 25 turbines, I have a net loss of power

**Comment by MikrySoft** [comment]
Nobody would ever need more than 640k of RAM, eh?

**Comment by Lordmau5** [comment]
What is the point in even having it when it's not being fixed?
Why keep it in still?
There's no point in closing this.

When you're end-game you don't have a use for the 1x generators anymore, so you increase the powergen to 8x or 64x.

**Comment by EnigmaticaGH** [comment]
RWTema I would love for you to fix this! These days, there ARE reasons one would need such high power output, such as RFtools dimensions and MFR mining lasers. And since you still generate the same RF, just quicker, you'd need an insane setup to keep up with nether star production, so it's not particularly unbalanced either.

**Comment by Frontrider** [comment]
At least increase the buffersize on that single block to be capable of handling the rf generated in every tick. You just added an infinite rf cable to thermal dynamics, there should not be any problems with the output. :D

**Comment by EnigmaticaGH** [comment]
@Frontrider They already do have increased capacity, at least in the version I'm running (infinity 1.3.4 modpack)

**Comment by AussieWarGod** [comment]
I'd like to point out that i DEFINITELY use x64 nether star gens, i had made 2 of them to power my entire base to cause minimal lag, now instead i have 128 x1's which cause horrendous server lag and i had to bump down to 64 x1's. I most definitely can use all the power provided by x64 power gens with ender quarries, Technomancy can also use all of the power provided using cryotheum fluxducts to move the power. especially with mekanism's new batteries that can hold trillions of RF, even quadrillions.

The other application is large cities on large servers, my base alone currently uses up to 1mRF/t and i have other players moving to the city surrounding my base that would be using my power supply. having a sustainable source of nether stars, it would be cool if i could continue to power my base without server lag.

**Comment by AussieWarGod** [comment]
even just fixing the x8 gens would be fine, i might not need a x64 but an upgrade from x1's would severely reduce lag.

**Comment by misterfixit** [comment]
in tema's defense the generators aren't intended for power storage.

**Comment by Lordmau5** [comment]
They sure are not intended for power storage.
But they should be capable of outputting high energy values nowadays.

**Comment by widd** [comment]
Still waiting on this to be fixed. Contrary to what tema stated there are various uses for this amount of power production. Ender quarries and certain machines (ic2 machines as an example) have percentage based increases in power consumption that get very expensive very fast. Both the x8 and x64 generators could save quite a bit of space and time. If the generators are not going to be fixed they should simply be removed. Broken features in an actively developed and released mod are completely pointless.

**Comment by AngellusMortis** [comment]
+1 RF Tools alone makes x64 generators viable.

**Comment by Psithief** [comment]
I need this to achieve Bacon Donut's dumb "1 billion RF/tick" achievement in his modpack.

…

~~Maybe~~ I'll just hexedit that storage/transfer capacity to something ridiculous.

**Comment by callous4567** [comment]
Doesn't work. I'm sad.

**Comment by RobinEH** [comment]
I'm surprised people are still having problems with this. According to the change logs for Extra Utilities 1.2.7 (2015 July 05):

> ...Generators now output the correct amount based on their multiplier...
> [http://minecraft.curseforge.com/projects/extra-utilities/files/2245576](url)

**Comment by callous4567** [comment]
Still having the issue and such; gone through multiple modpacks too :_:

**Comment by Psithief** [comment]
@RobinEH The change log is correct for the generators that should output under the hard storage/transfer capacity limit. Generators that should output more are capped.

**Comment by Psithief** [comment]
@RobinEH You should check #453 for more information.

**Comment by Psithief** [comment]
When the actual tile attempts to transmit energy, it calls a function called transferLimit(). This would be the the same as maxEnergyStored by default, but each generator type actually replaces this limit with a (small) static value.

That value is never increased by the multiplier, so the internal storage can now fill up at 2,560,000 RF/t but it can still only transfer out of the block at 100,000 RF/t.
