### ISSUE TITLE
No generators

### ISSUE THREAD

**Issue by rhyssean** [rwtema/extrautilities_old_issues#305]
I have NEI, and when I search for "generators" it comes up with a couple of generators froom EnderIO, Mekanism... But no extra utilities ones. I'm not sure why, but it seems like they aren't in the game (I use the latest 1.6.4 version), so I was wondering if there was a way to fix it.

**Comment by rwtema** [comment]
Please check the readme - I don't support 1.6.4 anymore. For the record I don't know what's causing your problem or how to fix it.
