### ISSUE TITLE
Item Duplication when Autocrafting with BetterStorage Storage Crates

### ISSUE THREAD

**Issue by fraenkelc** [rwtema/extrautilities_old_issues#306]
When the autocrafting mechanic is used with connected Storage Crates from BetterStorage a single item will be used for all (connected) slots. this allows for crafting an octuple compressed cobblestone from a single piece of cobble. This also allows for duplication of other items that can be crafted into blocks or require multiple items of the same type.
![2014-09-12_02 09 02](https://cloud.githubusercontent.com/assets/4005102/4243636/2a3834ce-3a11-11e4-9b61-0a0b252cfab4.png)
![crate](https://cloud.githubusercontent.com/assets/4005102/4243667/bde92872-3a11-11e4-9ce5-93c3873e7705.png)
![result](https://cloud.githubusercontent.com/assets/4005102/4243668/bdef469e-3a11-11e4-89d9-5d25c676be70.png)

Found this bug while testing a new compressed cobble setup:
![2014-09-12_02 17 09](https://cloud.githubusercontent.com/assets/4005102/4243696/3fd77b68-3a12-11e4-87d7-d273097bc62e.png)

Tested with versions:
extrautilities 1.1.0i
BetterStorage 1.7.10-0.9.4.111

**Comment by fraenkelc** [comment]
FWIW, I've tried reproducing the same behaviour with jabba barrels and bspace upgrades but it does not appear there.

**Comment by rwtema** [comment]
I suspect BetterStorage has an issue with draining items. Extra Utilities will only craft if it is successfully able to drain all the needed items from a block.

**Comment by copygirl** [comment]
From the looks of it, ExtraUtilities isn't open source. It would be useful to see the code that's used to extract items, even if the problem is on BetterStorage's end.
