### ISSUE TITLE
[1.1.0i] Etheric Sword and Soul Fragment Bug

### ISSUE THREAD

**Issue by jglenn1066** [rwtema/extrautilities_old_issues#307]
When you place the etheric sword into the crafting grid, and SHIFT+LMB on the soul fragment, it tries to craft as many soul fragments as it can, and subtracts the hearts accordingly. Only one soul fragment is created, but multiple hearts are taken. When the user tries to consume the soul fragment to undo the damage, they only get 10% back; that is, one heart rather than the multiple stolen in the crafting process of shift clicking the item.

Discovered today, 9/12/14 at 3:30pm EST on the TransMinecraft server by user Jessica_Lovejoy.

**Comment by rwtema** [comment]
Sadly not a lot I can do by the looks of it. Vanilla has some odd interactions with crafting stacks of items. I'll look into but for the moment, just don't shift-click.

**Comment by jglenn1066** [comment]
Hey, thank you for taking a look, and thank you for your work. We appreciate all you've created for the community. <3
