### ISSUE TITLE
Energy Nodes using double energy

### ISSUE THREAD

**Issue by Lord-Mimir** [rwtema/extrautilities_old_issues#308]
in Extra Utilities 1.1.0.k The Energy Node and Hype Energy node, drain twice the power that the block/machine requires.  When connected to a machine that takes 5 RF a tick to run, the Node will actually use 10 RF a tick.  

Examples: a MFR pre-charge laser takes 5,000 RF a tick to run at full power.  But with an energy node, the actual drain from the power supply is 10,000 RF a tick.

**Comment by Vyrebird** [comment]
Sounds like #270 - if the device supplying the energy can supply it faster than the receiving device can accept it, you seem to generally lose half the RF.

(A temporary workaround can be to set the power supply to output a max of 5000 RF/tick (to match the laser's input), which should avoid the energy loss in my experience.  But that requires the power supply to be configurable, and negates most of the benefits of having a power network in the first place, but it's something)

**Comment by rwtema** [comment]
Found the issue - it will be fixed in the next version.
