### ISSUE TITLE
Crash when right-clicking on liquid retrieval node

### ISSUE THREAD

**Issue by einsteinsci** [rwtema/extrautilities_old_issues#309]
Game crashes when right-clicking on a liquid retrieval node. This occurs with the FTB 2014 Pax Prime (not East) map & pack.

[Setup screenshot](http://i.imgur.com/LQkWpWD.png)
[Crash log](http://pastebin.com/yuTXnzXz)

**Comment by rwtema** [comment]
Sigh, it's the damn Invisible block replacement glitch again. Try updating forge.

**Comment by einsteinsci** [comment]
Strangely enough, it stopped happening even before I updated Forge.
