### ISSUE TITLE
Feature Req: "Compressor" backpack.

### ISSUE THREAD

**Issue by fluffle** [rwtema/extrautilities_old_issues#311]
Hi :-)

I know you're not a fan of feature requests but I didn't see any harm in trying anyway. While manually compressing cobble out on a mining run (playing Blood'n'Bones => no quarrying), I started thinking "it would be nice not to have to do this". Here's my vague idea:

Tier 1 compressor, compresses 9x {sand,dirt,cobble,gravel} -> compressed {X}.
string, cobble, string
iron, piston, iron
string, cobble, string

Tier 2, compresses 9 {X} -> compressed {X} and 9 compressed {X} -> 2x compressed {X}:
string, compressed cobble, string
iron, tier1 compressor, iron
string, compressed cobble, string

And so on, up to a Tier 8:
string, 7x compressed cobble, string
iron, tier 6 compressor, iron
string, 7x compressed cobble, string

These would be worn in place of chest armour and would compress cobble etc as it was mined into the player's inventory. It'd make a nice alternative to carrying around a crafting table and having to pause regularly to shift-click NEI a few times to clear out inventory space. The recipes are just handwaving, I didn't want to make it too cheap but might have erred on the side of "too expensive" instead :-)

Cheers,
--fluffle

**Comment by BraynStorm** [comment]
+1. I wanted to suggest the exact same thing. It could also be a Bauble so you can still wear armor but considering there are a LOT of baubles if you use botania - maybe both will be best (a bit like you can use the wings without them being in the Baubles' inventory).

**Comment by rwtema** [comment]
No thank you.
