### ISSUE TITLE
Extraneous amount of Silverfish while deep dark mining

### ISSUE THREAD

**Issue by jztech101** [rwtema/extrautilities_old_issues#313]
When an Ender Quarry is placed in the deep dark, and extraneous amount of silverfish sometimes spawns while mining lagging the server out.

**Comment by SparxySys** [comment]
Our server doesn't have many people on it, but we have several large ender quarries in the deep dark. The main issue is that sometimes the ender quarry hits what I'm going to assume is an extreme hills biome, which spawns silverfish. When our server TPS goes down, we have managed to note figures up to 4112 Silverfish entities being active in the deep dark chunk being quarried.

Are ender quarries supposed to spawn the silverfish and not dispose of them in any way? This many entities does cause issues for us.

Thank you!

**Comment by SparxySys** [comment]
Some additional information-
It looks like the silverfish spawn in the dirt in the ender quarried chunk, using up a lot of server time doing nothing. However, when a player loads the chunk, they all begin suffocating and die. Maybe they should do this without needing a player in the chunk? (or maybe they shouldn't spawn inside enderquarry-dirt at all?)

**Comment by rwtema** [comment]
In the next version, Silverfish will not spawn when mined by an Enderquarry.
