### ISSUE TITLE
Fluid incompatability causes Ender Quarry to crash server

### ISSUE THREAD

**Issue by YamadaShinichi** [rwtema/extrautilities_old_issues#314]
http://pastebin.com/Kier9qU9

Posted above is a crash report I got from my server. I suspect the issue is caused by the Ender Quarry with the Pump Upgrade trying to pump up the liquid flux from Thaumcraft 4.

**Comment by rwtema** [comment]
This looks to be a TC4 issue.

The Liquid Flux is returning true from canDrain() but it doesn't supporting draining.
