### ISSUE TITLE
Deep Dark Night Vision - Request to workaround (details inside)

### ISSUE THREAD

**Issue by SparxySys** [rwtema/extrautilities_old_issues#316]
Hello there,

Using Night Vision in the Deep Dark causes most screens on devices running older non-nvidia cards to turn pitch black.
I'd like to ask if you could perhaps work around this issue?
This is possible by having fog and skycolor both have a value > 0.
You can still render a black skybox if so desired.

Thanks if you make this happen <3

**Comment by rwtema** [comment]
This should really be fixed by forge itself.

I will consider it.
