### ISSUE TITLE
Magnum Torch preventing spawn of mobs

### ISSUE THREAD

**Issue by evenas98** [rwtema/extrautilities_old_issues#319]
my magnum torch prevents spawning mobs from cursed earth, using latest version

**Comment by rwtema** [comment]
Unable to replicate. Cursed Earth spawning and Magnum torch spawn prevention have nothing to do with each other. Your problem lies elsewhere.

**Comment by evenas98** [comment]
well, when i removed my magnum torch they started spawning, put it back down they stopped!

**Comment by TherminatorX** [comment]
GIF it
