### ISSUE TITLE
Crafting Magical Wood crashes game

### ISSUE THREAD

**Issue by Aelrath** [rwtema/extrautilities_old_issues#32]
While crafting Magical Wood the game crashes.
- Using FTB Horizons pack 2.1.1.
- First had version 1.0.3a when happened and then updated to 1.0.3c and still occurring.
- Asked friend to craft same recipe and he has same issue.
- Attempted crafting in various crafting stations (vanila, tinkerers etc) with same problem (log contains tinkerers crafting station attempt)
- Used all enchanted books (no enchants - crafted from enchanting table level 1 enchants) as well as enchanted books with enchants with no change

-- Excerpt of errorlog (full log link bottom) --

Caused by: java.lang.NullPointerException
at extrautils.crafting.RecipeMagicalWood.getEnchantmentLevel(RecipeMagicalWood.java:50)

http://pastebin.com/XwniMV3K

**Comment by Aelrath** [comment]
After writing the section on what enchanted books I used I went to test using only enchanted books with some sort of enchantment (e.g. Power I) on them. Seems the crash only happens when using "Enchanted Book" with no enchant on them obtained usually from enchanting with only 1 level.

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
