### ISSUE TITLE
CRASH: Advanced filing cabinet inventory

### ISSUE THREAD

**Issue by jbruett** [rwtema/extrautilities_old_issues#321]
I received this crash log while loading multiple items from multiple mods into an advanced filing cabinet

[http://pastebin.com/YLShKk0D](http://pastebin.com/YLShKk0D)

this is the crash log when i try to access it again

[http://pastebin.com/MfHhFM3L](http://pastebin.com/MfHhFM3L)

i would like to get a list of items that are in the adv. filing cabinet if possible and then I will trash the cabinet and spawn the items back via creative.

**Comment by rwtema** [comment]
Not my issue, looks to belong to -  "portablejim.veinminer.event.client.ItemNameTooltip"
