### ISSUE TITLE
Enderthermic Pump is pumping fluids other than lava

### ISSUE THREAD

**Issue by lilmoefow** [rwtema/extrautilities_old_issues#322]
Sorry not sure if this is suposed to be an intended feature, but i was under the impression that the Endethermic Pump was only supposed to pump out lava.  And i am playing with you mod along with a few others and one of the other mods is Biome o Plenty aswell which adds Blood to the nether and the Enderthermic Pump is somehow able to pick up this fluid.

forge-1.7.10-10.13.0.1208-universal.jar
extrautilities-1.1.0k.jar
BiomesOPlenty-1.7.10-2.1.0.981-universal.jar

**Comment by evenas98** [comment]
this is an big problem for me too, it always gets stuck with this "blood" in my pipes, thankfully the dynamos don't accept the blood

**Comment by evenas98** [comment]
a filter of some type would be very nice:)

**Comment by rwtema** [comment]
Working as intended.

**Comment by lilmoefow** [comment]
Alright cool i wasn't sure if that was intentional or not... thanks for the response

**Comment by evenas98** [comment]
can you add a feature to add some sort of filter?

**Comment by jena-th** [comment]
@evenas98 already available in extra utilities, use a bucket of the liquid you want to filter.

**Comment by swemoney** [comment]
Ran into this today. I took care of the issue by switching to the Ender Fluid Conduits from Ender IO. They allow more than one liquid to run through them at a time and there's a filter you can use buckets to set what kind of liquid to accept. I added a 2nd tank. Doesn't need to be anything special. Set the filter to accept blood, and then i have a normal fluid conduit coming out of the back into a build craft void pipe. Worst case, lava slows down while the blood is getting voided. Just for good measure, though, I ran around and filled all the pools of blood I saw with cobble.

**Comment by jena-th** [comment]
I just got an idea… Can someone test if this blood is usable for Tinker's Construct related stuff, like the pokefennium ?
