### ISSUE TITLE
Conveyor/BC Pipe conflict?

### ISSUE THREAD

**Issue by Fureniku** [rwtema/extrautilities_old_issues#324]
YO. Got a server-side crash with 1.1.0k. Server crashes instantly as soon as the relevant chunk gets loaded (ie, player logs in to the area). Setup is items moving along a conveyor, ready to be sucked up by a BC Obsidian pipe. The pipe does have a conveyor belt under it too for aesthetics, so it may be a conflict of some kind between both of the blocks trying to move the same item entity?

http://paste.silvaniastudios.com/paste/view/a46f9faa

**Comment by rwtema** [comment]
Will be fixed in next version.
