### ISSUE TITLE
Crash when placing cover on transfer pipe

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#328]
I tried placing a stone brick cover on a transfer pipe, but it caused a crash on the server instead.

Crashlog:
http://pastebin.com/Ax1eT3Ud

**Comment by TherminatorX** [comment]
The log seems to be pointing to CCC, poke @chicken-bones

**Comment by ghost** [comment]
Indeed something related to CCC, crashed when I tried placing a cover on an AE Cable.
