### ISSUE TITLE
Redstone Arsenal's Flux-Infused wrenches do not work on drums when charged

### ISSUE THREAD

**Issue by uberfuzzy** [rwtema/extrautilities_old_issues#33]
Redstone Arsenal (by CoFH) adds two wrench class items. The RedStone Flux-Infused (RSFI) OmniWrench and BattleWrench. When charged with RF, they do not pickup drums as a wrench should. When newly crafted with exactly 0 charge, they DO function as intended.

versions tested:
FTB Monster pack 1.1.1
Extra Utilities: 1.0.3a
Redstone Arsenal 1.0.0.0

**Comment by uberfuzzy** [comment]
also confirmed with EU 1.0.3c

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
