### ISSUE TITLE
Item Filter duplication with Trash Can

### ISSUE THREAD

**Issue by pthivent** [rwtema/extrautilities_old_issues#330]
Version : 1.0.3c
Reproducible : Always
Steps to reproduce :
- Setup a _Trash Can_ with an _Item Filter_ in it. 
- Open the Trash Can interface and manually dumpster an item by left clicking it while the filter is in the slot

Actual result :
- The item gets destroyed but you get a duplicate of the filter back.

Expected result : 
- Either not being able to dumpster an item while the filter is in the slot or not getting a dupe of the filter.

**Comment by rwtema** [comment]
Thanks, fixed in dev.
