### ISSUE TITLE
Liquid Transfer Node odd behavior

### ISSUE THREAD

**Issue by The-Mad-Cat** [rwtema/extrautilities_old_issues#333]
There seem to be issue with Liquid Transfer Node behavior, it not acting the same as item transfer node.

Take look at image "Items Sort Work" below. For the item transfer node the item(s) get sorted into chest and if that chest is full then goes into overflow line. Using the same design as item transfer node for Liquid Transfer Node, I replace chest with tank (tried using from Extra Utilities; simple fluid tank; or BuildCraft), and used Liquid Transfer Node which result in odd behavior see in image Liquid Sort Fails. The liquid went into tank and overflow line. The tank wasn't even close to being full.

For the Liquid Transfer Node or item Transfer Node only upgrades used are: Glowstone; Stacks Upgrade; and Speed Upgrade.

I have images and more information posted at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443963-extra-utilities-v1-1-0k?comment=2701

**Comment by rwtema** [comment]
Working as intended.

**Comment by The-Mad-Cat** [comment]
So, the Liquid Transfer Node by design has Pseudo Round Robin Upgrade already? If so is there way to remove that ability with upgrade to act like item transfer node?

I have central location for liquid that come from EnderTank to store area. When that store area overflow goes into MineFactory Reloaded machines. If there to much liquid(s) for the machines it continues down a long pipe that then ends up destroying liquids. Does this so doesn't backup into EnderTank.
