### ISSUE TITLE
Crash: Watering Can

### ISSUE THREAD

**Issue by Jagmar** [rwtema/extrautilities_old_issues#335]
When ever anyone uses a watering can on my 1.7.10 server all clients crash. I only have the report for my crash at the moment, but on request I can fetch the crash reports from the other clients. I'm not sure what else you would need to help you figure this one out. 

Using Multi MC as my launcher.

http://pastebin.com/En7ZjF28

**Comment by rwtema** [comment]
Fixed ages ago, update your version.
