### ISSUE TITLE
[Request] Flood Gate like block

### ISSUE THREAD

**Issue by Aedda** [rwtema/extrautilities_old_issues#336]
I find ExU and other mods have mostly replaced BuildCraft in my game play. However one thing I still use BC for is the Flood Gate, I use it to fill pools and ponds with current-free water. It would be amazing if like the Ender-Thermic Pump more or less replaced the BC pump if ExU could provide a block/device to replace the Flood Gate.

**Comment by rwtema** [comment]
No thanks.
