### ISSUE TITLE
Any node + any pipe = crash

### ISSUE THREAD

**Issue by qwertyuioplkjhgfdsa** [rwtema/extrautilities_old_issues#34]
http://pastebin.com/9SEvu0x6
The crash occurs when i place a node somewhere with or without inventory at the back and place any kind of pipe on the same block as the node is.(see screen
![2014-04-19_14 51 33](https://cloud.githubusercontent.com/assets/7346402/2748408/63fd8db6-c7c1-11e3-9d12-7b8a7b17f9c2.png)
![2014-04-19_14 53 05](https://cloud.githubusercontent.com/assets/7346402/2748416/99287460-c7c1-11e3-9cd2-5db91442cb05.png)

)

**Comment by Tetha** [comment]
This happens if transfer nodes interact with ANY forge multipart, be it covers, transfer pipes (which is quite fiendish if you want to place a transfer pipe on a transfer node), and (bugging me right now) the transparent display if placing covers

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
