### ISSUE TITLE
1.7.10 extrautilities-1.1.0k transfer node (liquid) does not work

### ISSUE THREAD

**Issue by SniperHauss89** [rwtema/extrautilities_old_issues#341]
Hi, I've been messing around with the latest build of extrautilities and the transfer node for liquids doesn't seem to register any liquid under it at all. I have tried changeing forge versions once and there wasn't any change at all. I've been only using extrautilities and openblocks (for their tanks) so I know it's not a mod conflict, but I haven't seen where anyone has this problem and this build of extra utilities has been out long enough I would think someone else would of recognized a problem like this. anyway I just quite curious as to why this is. Any information is greatly appreciated. :)
![2014-10-03_02 07 51](https://cloud.githubusercontent.com/assets/9005067/4502303/009c6126-4ac4-11e4-8e55-5c35a723a1bc.png)
![2014-10-03_02 11 56](https://cloud.githubusercontent.com/assets/9005067/4502315/4a980fdc-4ac4-11e4-9adb-08a7f18cd38e.png)

**Comment by EchoDel** [comment]
You need to have a world interaction upgrade in the transfer node.

**Comment by SniperHauss89** [comment]
O ok thank you very much I guess I should have paid attention to the upgrades a little more and try to troubleshoot a little deeper. it wasn't like that in 1.6.4 and that's where I've played the majority of my mods pack worlds. anyway thank you for taking the time to point out my obliviousness ;) (I should of figured it out being there was more upgrade slots in the interface than in 1.6.4)
