### ISSUE TITLE
Extra Utilities causing crash

### ISSUE THREAD

**Issue by auricorage** [rwtema/extrautilities_old_issues#345]
I have the latest 1.7.10 Extra utilities and the lastest forge 1.7.10 and I have mantle, IC2, build craft and tinkers construct as my current mods, for some reason I load with Extra utilities it crashes. Is there a way to have it not crash and still be compatible with these other mods?

**Comment by TherminatorX** [comment]
Really? You say "I crash" and expect it fixed???? 

At the very least, provide a crash log.

**Comment by auricorage** [comment]
My bad, it was simple Forge and updates not compatible, all works fine now, just updated to the most recent.
