### ISSUE TITLE
crash when trying to shift click items into filing cabinet

### ISSUE THREAD

**Issue by Rious** [rwtema/extrautilities_old_issues#346]
http://pastebin.com/gefBdHZM

tried this using regular enchanting books, but whenever i tried to shift click something into the cabinet, it crashes client side.

using the DNS pack from ATLauncher v7.4.1
extrautilities-1.1.0k

**Comment by TherminatorX** [comment]
Does this happen with wawla removed? The only time EU is mentioned is in the fact that these things are in a filing cabinet.

**Comment by rwtema** [comment]
Looks like Scala was removed. Not my issue.
