### ISSUE TITLE
Filing cabinet [Any kind] crashing

### ISSUE THREAD

**Issue by iKurama** [rwtema/extrautilities_old_issues#349]
Extra Utilities Version: 1.1.0k

While I have some non-stackable items [for adv. filing cabinet] And shift clicking them in, will cause crash, same goes for the normal one.

Crashlog: http://pastebin.com/U1S7ymvH

Not sure if a dupe issue, since the other problem was about Vein miner, which Hermitcraft MS doesn't have.

**Comment by TherminatorX** [comment]
does this happen w/o Wawla? the first few lines reference it.

**Comment by rwtema** [comment]
Looks like someone is not include Scala. In any case, not my issue.
