### ISSUE TITLE
Request: Ender Quarry Auto-Fill upgrade

### ISSUE THREAD

**Issue by kagenin** [rwtema/extrautilities_old_issues#351]
Heya, I'd just wanted to make a suggestion for an Ender Quarry upgrade.  I did read the readme, and totally understand if this is something you'd rather not add.

What I'd like my Ender Quarry to do is fill in any empty space with dirt.  Is this at all possible?  It would be really handy to run an EQ near my base, and have it fill in any and all caverns, which would help keep my nearby mob farm/grinder running at peak efficiency.  Something that would be the complete opposite of what the World Hole upgrade does, essentially.

As a sidenote, the EQ seems to grab TiCon torches, but leaves vanilla torches alone.  Kinda odd.

Anyway, thanks for your time, and your efforts.  ExtraUtils is one of my favorite mods.  Peace!

**Comment by TherminatorX** [comment]
So, if somehow via Heaven or Nether RWTema decided to be okay with this, this "dirty upgrade" wouldn't dig anything up, just replace air and/or lava/water with dirt?

**Comment by kagenin** [comment]
Oh it'd dig stuff up, too, but also fill in caverns.  Maybe leave liquids untouched, unless the pump upgrade was active, too.

**Comment by rwtema** [comment]
No. This is not the purpose of the Quarry.
