### ISSUE TITLE
Additional options for transfer nodes

### ISSUE THREAD

**Issue by za3k** [rwtema/extrautilities_old_issues#352]
Since transfer nodes include many features (crafting, cobblegen, water gen at least), would you be willing to include options to enable/disable those features more granularly in the config? I would love to include an autocrafting option but not fast cobblegen, for example. 

Edit: Not sure how to label this as a feature request

**Comment by TherminatorX** [comment]
You can't, and he won't. Tema no likey "feature requests"

**Comment by rwtema** [comment]
Correct. The current system works fine.
