### ISSUE TITLE
Transfer Node failing

### ISSUE THREAD

**Issue by omegablue8392** [rwtema/extrautilities_old_issues#355]
using EU 1.1.0k and when i try to make a cobble gen with the transfer node it's not pulling and cobble from the block. I have lava on one side and water on another but not pulling any cobble. Tried just using chests and it works. Was the cobble gen a bug that was fixed or is it a bug now that it won't pull any?

**Comment by TherminatorX** [comment]
did you put in a mining upgrade? that's required now.

**Comment by omegablue8392** [comment]
I did not, and I didn't know it was required, thanks for the info. Ended up using a Igneous extruder to make cobble. Ill try the upgrade and then close if needed

**Comment by omegablue8392** [comment]
It's FIXED (keywords for google searches) and the proper name for the required item is "World Interaction Upgrade" happy gaming! thanks TherminatorX
