### ISSUE TITLE
Watering Can Bug

### ISSUE THREAD

**Issue by MarshMilo100** [rwtema/extrautilities_old_issues#357]
I am not sure if this is intended or not, but I have experienced and 'bug' of sorts with the watering cans, reinforced or not,  not applying to crops that have a solid block of any kind above them. This also may possibly be a vanilla bug, but i am not sure.

**Comment by TherminatorX** [comment]
Have you ever had vanilla crops grow with a block directly above them? (Screenshot)

**Comment by rwtema** [comment]
That is the way vanilla works.
