### ISSUE TITLE
Suggestion: Automation with QED

### ISSUE THREAD

**Issue by RoyalBingBong** [rwtema/extrautilities_old_issues#359]
I was kind of sad when I played around with the QED for automation and found out that it does not quite work out. Inserting items always has to be done manually, extracting with Nodes works fine though.
So my suggestion is to make the QED able to accept items. Maybe in the way the autocrafting works: 9 Chest as crafting grid and the QED in front instead of a crafting table, rest as usual.

**Comment by Zaflis** [comment]
So transfer node would be the only way to pull items out? I imagine it being difficult to detect the chest/container pattern, and not mix it with the output side. If QED acted like a normal chest, i would use XU rationing pipe to normally transfer items in. It would only keep 1 stack of any given item in it. But as far as i can tell, QED item input from machines was disabled on purpose.

**Comment by RoyalBingBong** [comment]
I either didn't understand you or you didn't understand me. What I meant was something like this:
http://i.imgur.com/fE5t798.png (found via google) and instead of the crafting table you would have the QED.

**Comment by rwtema** [comment]
The QED is not meant to be automatable.

**Comment by Gunner76th** [comment]
So out of curiosity, what was your decision for not allowing the QED to allow items to be inserted, but allow for the automated removal of items? As it stands, from what I can see, the QED is the only crafting device (to include Thaumcrafts Arcane Altar, and Bloom Magics Altar) that does not allow for automation. 

Perhaps an alternative would be to put in a config option, thereby allowing server owners decide if they want to use the current "GTish" method of difficulty of manually depositing things in for processing and crafting, or if they want to allow item insertion for a more unified experience (as in more in line with what almost all other mods allow).

**Comment by Cbert** [comment]
"The QED is not meant to be automatable."
Discontentment.
