### ISSUE TITLE
[Major Issue] Duplication glitch w/ Golden bag of Holding

### ISSUE THREAD

**Issue by iHeartZigg** [rwtema/extrautilities_old_issues#36]
EDIT; Read last comment X_X

**Comment by rwtema** [comment]
Unable to replicate it. What version are you using and are you using inventory tweaks or similar and what version?

**Comment by iHeartZigg** [comment]
EDIT; Read last comment.

**Comment by iHeartZigg** [comment]
I went back into the server to test it further, it appears that it was just a visual bug do to latency.

The bag was nearly full of the item i tried to move, and it tried placing it back into my inventory (Which was full) so the first item in the bag got moved to the empty space i clicked, and also left a ghost item.
