### ISSUE TITLE
Problematic amounts of silverfish from Ender Quarry in Extreme Hills biome

### ISSUE THREAD

**Issue by Zarkov2** [rwtema/extrautilities_old_issues#361]
Extra Utilities 1.1.0k
Minecraft Forge 10.13.0.1208

This issue is similar to the closed issue #313, but is unrelated to the deep dark. I'm mining in a custom mining world (dimension id 4) using an Ender Quarry with World Hole and Speed II upgrades. The dimension is a flat world consisting of only Extreme Hills biome.

The number of spawned silverfish while mining is so high that the quarry cannot be used:

![2014-10-20_20 22 44](https://cloud.githubusercontent.com/assets/9017939/4706910/0510ad70-5889-11e4-8b04-b3c62064239f.png)

Using a regular BC Quarry, there are no silverfish spawned.

**Comment by Zaflis** [comment]
This would also concern hellfish from Nether Ores mod. I have disabled them just for this reason.

**Comment by Zarkov2** [comment]
Fixed in 1.2.0 (no silverfish spawning).
