### ISSUE TITLE
Crashes, everywhere (Solved)

### ISSUE THREAD

**Issue by BananaFendougle** [rwtema/extrautilities_old_issues#376]
Whenever I interact with any of the generators or the watering can my game crashes. I'm playing on my own server with friends
http://pastebin.com/284sWzvR
Forge: 1.7.10-10.13.0.1205
Mods: Damage Indicators
Ars Magica 2
Apllied energistics
Backpacks
Better storage
Buildcraft
Carpentersblocks
Chisel
Code Chicken Core
COFH core
Extra utilities 1.1.0b
Hats
Ichunutil
Iron chests
Mantle
Mekanism
Mekanism generators
Mekanism tools
Minefactory reloaded
Mr crayfish's furniture 
NEI
Pams harvest craft
Thermal expansion
Thermal foundation
Torched
Trailmix
WAILA
WAILA harvestibility

**Comment by jena-th** [comment]
No help will be provided if you don't join a crash log and give the versions of your forge and the mods you're using.

You can save your crashlog online in a gist: https://gist.github.com/ .

Looks like something similar to the #377 to me.

**Comment by TherminatorX** [comment]
Or a pastebin.

Also, do you run bukkit?

**Comment by BananaFendougle** [comment]
No, It's just a simple hamachi server, but any way its fixed now, I just updated the mod to 1.1.0k, THanks for your help any way guys!

**Comment by jena-th** [comment]
_scraching his head_ Hamachi… Don't you meant Hamashi, the vpn software ?

**Comment by TherminatorX** [comment]
Hamachi basically spreads LAN across the internet, not very well, mind you.
https://en.wikipedia.org/wiki/Hamachi_(software)

Also, if this is solved, close it.
