### ISSUE TITLE
Crash: Ticking block entity

### ISSUE THREAD

**Issue by artdude543** [rwtema/extrautilities_old_issues#377]
Forge: 10.13.2.1232
Mod Version: 1.1.0k
Crash Report: http://pastebin.com/247ax6Sr

Seems that after upgrading Forge this crash has started, if you need more details about the crash/setup please do ask.

Note: This seems to be effecting current worlds, on a new world I can't replicate this crash.

**Comment by artdude543** [comment]
Update on this crash this could be closed now, but after removing a mod which we had an item in the filter the filter still tried to filter the item which does not exist in the game anymore. So this could either be a bug which just needs catching in the code (nulling) or for the users to check filters before removing mods and loading the world backup.

**Comment by rwtema** [comment]
Found the issue, when a mod item is removed it leaves a null 'itemstack' from the nbt which I wasn't checking for.
