### ISSUE TITLE
Nothing to transfer with

### ISSUE THREAD

**Issue by laserjet25** [rwtema/extrautilities_old_issues#380]
I have recently put together a private modpack with about 40 mods and when I was testing it, I noticed that there were no type of transfer pipes or nodes from this mod. There were none from the normal creative mode menu or NEI.

**Comment by laserjet25** [comment]
Also this modpack is 1.7.10

**Comment by TheJulianJES** [comment]
Screenshots? Log?

**Comment by Frontrider** [comment]
i got it that the some of the stuff does not appear. it has something to do with qed crafting.

**Comment by TheJulianJES** [comment]
Screenshots? Log? Mod List?

**Comment by laserjet25** [comment]
At this point I'm going to just say I made a stupid mistake. I thought that some blocks were from this mod when they were actually from extra utilities. It ends up, I never actually had this mod installed...

**Comment by TheJulianJES** [comment]
...
