### ISSUE TITLE
Big reactors power tap does not updates from energy extraction pipe

### ISSUE THREAD

**Issue by Frontrider** [rwtema/extrautilities_old_issues#381]
if i plug in an energy extraction pipe into  the reactor, the rf is being extracted, but the tap does not turns green.

Reported to booth sides.

energy transfer nodes can keep up with big reactors. keep up the good work.

**Comment by rwtema** [comment]
No idea what the issue is.

**Comment by Frontrider** [comment]
<a href="http://indafoto.hu/frontryder/image/21970437-f9f755ab/"
title="Frontryder: 2014-10-31 18.35.32.png - indafoto.hu"><img src="
http://img1.indafoto.hu/1/1/184399_fb2b8d4f0a90f0b64cc566b0b7e6ad55/21970437_f9f755abbd35c023c96713ca6e6b4883_xl.jpg"
title="Frontryder: 2014-10-31 18.35.32.png - indafoto.hu" alt="Frontryder:
2014-10-31 18.35.32.png - indafoto.hu" border="0" /></a>

I think if you can fix it, than it might fix the issues with the dynamos.

**Comment by erogenousbeef-zz** [comment]
Hi @rwtema,

 I did some simple logging in my power taps. When they check for adjacent handlers, they ran this code:

```
TileEntity te = world.getTileEntity(x + out.offsetX, y + out.offsetY, z + out.offsetZ);
if(!(te instanceof TileEntityReactorPowerTap)) {
    // Skip power taps, as they implement these APIs and we don't want to shit energy back and forth
    if(te instanceof IEnergyHandler) {
        IEnergyHandler handler = (IEnergyHandler)te;
        if(handler.canConnectEnergy(out.getOpposite())) {
            BRLog.info("[%s] Attaching to RF network at supported handler at %d, %d, %d", worldObj.isRemote ? "CLIENT":"SERVER", x, y, z);
            rfNetwork = handler;
        }
        else {
            BRLog.info("[%s] Ignoring RF network, does not permit connection at %d, %d, %d", worldObj.isRemote ? "CLIENT":"SERVER", x, y, z);
        }
    }
    else {
        BRLog.info("[%s] No RF handler at %d, %d, %d", worldObj.isRemote ? "CLIENT":"SERVER", x, y, z);
    }
}
```

I slapped down an Energy Extraction Pipe from ExtraUtils 1.1.0j and got the following output:

```
[18:12:12] [Server thread/INFO] [BigReactors]: [SERVER] No RF handler at 610, 5, 1073
```

It seems like you're not implementing the cofh.api.energy.IEnergyHandler API on your pipe's tile entity. I believe all blocks capable of handling RF are supposed to implement this API.

To preserve the extra-only behavior, you could implement it, and have `canConnectEnergy` return `true` and hardcode `extractEnergy` to return `0`.
