### ISSUE TITLE
Transfer Pipes do not connect to Forestry Multifarms

### ISSUE THREAD

**Issue by pa-philos** [rwtema/extrautilities_old_issues#391]
Should be pretty self explanatory.

https://www.dropbox.com/s/mf49walzbwmbds2/Captura%20de%20tela%202014-11-05%2018.25.48.png?dl=0

**Comment by rwtema** [comment]
IIRC Forestry's tile entities are not marked as non-zero inventories client-side. They do connect, it just doesn't display. Any case, forestry issue.
