### ISSUE TITLE
Invincible skeletons (that do not attack) spawn from cursed earth

### ISSUE THREAD

**Issue by Jaksuhn** [rwtema/extrautilities_old_issues#397]
Version: 1.1.0k
- They do not attack
- Peaceful mode does not rid them
- Not every skeleton is like this, nor has this happened with any other mob (about 1/100 skeletons this happens)

The only way to get rid of them (that I know) is to relog, hit once (can't hit more than once), relog and repeat until you kill them.

**Comment by rwtema** [comment]
Sounds like some mod is messing up spawning. Can't really help I'm afraid.
