### ISSUE TITLE
Mobs dont spawn on cursed earth

### ISSUE THREAD

**Issue by RajatheBeast** [rwtema/extrautilities_old_issues#398]
Mobs rarely spawn on my cursed earth. Also I will get invisble skelies. version 1.1.0k.

pic can be see here http://forum.feed-the-beast.com/threads/problem-with-cursed-earth.54746/

when i first did the ritual it was fine but now that i have placed it no mobs are spawning

**Comment by rwtema** [comment]
Unable to replicate.

**Comment by RajatheBeast** [comment]
hmm so it seems to work now...
