### ISSUE TITLE
Trying to void Liquid

### ISSUE THREAD

**Issue by Razorskills** [rwtema/extrautilities_old_issues#4]
Currently, I am using this mod instead of buildcraft. But I cannot seem to get around not having the void pipe. It could get rid of items and liquids. Only thing I couldn't use it for was thermal expansion it seemed. is there a way you could allow us to trash our liquids with fluiducts/pipes. Or maybe add a pipe that will act like the void pipe? I always hated that thermal expansion ducts did not hook up to the buildcraft version.

Or maybe a separate Item, like a Drain(Similar to the trashcan) But the liquids would disappear into the earth or something.. Maybe requiring a dirt block below it.. IDK

**Comment by rwtema** [comment]
This is for bugs not for suggestions. I am not taking suggestions for Extra Utilities at this moment.

**Comment by Razorskills** [comment]
Sorry, I guess I thought it was a bug I couldn't trash my liquids. But then went on a tangent since I was here.
