### ISSUE TITLE
Crash issue with Enderchest placed on an Ender Quarry

### ISSUE THREAD

**Issue by devryb** [rwtema/extrautilities_old_issues#40]
When a player places an enderchest on top of a quarry for the item output things run fine however on the next server restart it will crash and will not start unless enderstorage is removed.  To get enderstorage back we have to remove it place a block on the ender quarry and then re-add the enderstorage mod.
Apologies if this is not a bug with extra utils and it's actually with enderstorage.

http://pastebin.com/LC6CAW6x

**Comment by TherminatorX** [comment]
See what happens when you remove Bukkit. Things get odd with it.

**Comment by devryb** [comment]
Thanks, that is actually the case in this situation, I have logged this appropriately with the MCPC team

**Comment by devryb** [comment]
Sorry to bug you again with this but I've noticed with forge only it actually resets the chunk that the ender quarry is in.  mcpc plus handles this differently I guess and just crashes the server when it detects this issue.

**Comment by rwtema** [comment]
1. It's got nothing to do with me. All I'm doing is asking what block is at a position and someone else is crashing.
2. I'm no longer developing for 1.6.4. Unless this issue persists in 1.7 then it will not be addressed by me.
