### ISSUE TITLE
Running Quarry in large areas causes major lag

### ISSUE THREAD

**Issue by alc19803** [rwtema/extrautilities_old_issues#400]
While running the ender quarry in an area of about 60 x 64 I have noticed that the amount of experience orbs builds up under the surface causing major lag. The quarry does a good job but unfortunately after a while it causes the world to lag so bad that you have to use mcedit to delete the chunks and start over. 

Is there anyway to allow the quarry to collect the experience and dispose of it or, even better allow it to collect is and maybe output it as liquid experience

**Comment by rwtema** [comment]
It should not be dropping XP in theory but I've added a check to stop it.
