### ISSUE TITLE
Unstable Ingots dont explode While in a workbench

### ISSUE THREAD

**Issue by jtheninja5555** [rwtema/extrautilities_old_issues#402]
![untitled](https://cloud.githubusercontent.com/assets/8117944/5019607/ea5ed584-6a8e-11e4-839b-72ac8b66a2f3.png)

The ingot will continue to flash constantly between yellow and will only explode if it enters an inventory slot or if the player exits the workbench. Over all, the player will ultimately die, but the ingots wont kill them as long as they items stay in the crafting grid.

This is in Extra Utilities 1.1.0k version on the DireWolf20 1.7.10 pack.

Hope You Fix it!

**Comment by TherminatorX** [comment]
If you can craft something with them, and do so after this happens, does the player still die?

**Comment by rwtema** [comment]
A limitation of the 'explosion' method. Will not be fixed.
