### ISSUE TITLE
Ender quarry scans one block then must be picked up and replaced.

### ISSUE THREAD

**Issue by Ligerzero564** [rwtema/extrautilities_old_issues#403]
I am trying to use the ender quarry on a small 2x2 chunk area and have an ender I/O capacitor feeding the quarry witch is in turn fed by two lava generators slow but its still early. The problem is the quarry scans one block then continues rapidly draining the ender I/O capacitor of all of its power. If I pick the quarry up and replace it it scans one more block than last time and continues draining energy with no further gains.

**Comment by TherminatorX** [comment]
Can you pastebin a portion of a Forge log that coincides with this event?

**Comment by rwtema** [comment]
Unable to replicate.

**Comment by The-Lynix** [comment]
I have a similar problem, the quarry get stuck on a block, while draining power. I am using a much larger quarry (in a stable mystcraft dimension) with a speed II uppgrade, designated by ender-markers. The only way i have found to make it continue is to break and replace the quarry, which causes the quarry to rescan every block it allredy has mined. Even if it scans blocks again after a break and replace it only mines one extra block, then it gets stuck again. its both powered and sending items through a tesseract. 
I have tried to remove all uppgrades, run it with world hole uppgrade and moved the quarry, neither of which make a diffrence
I am playing on a server that is runing DW20s pack v 1.0.2

**Comment by Ligerzero564** [comment]
Problem Discovered, The Ender quarry was getting back stuffed because the pipes do not interact with an ME chest. check your item flow to see if the quarry is able to empty into your sorting system if you have a similar problem.

**Comment by The-Lynix** [comment]
Found it, thanks for the help
