### ISSUE TITLE
Ender Quarry removed from power source and still running.

### ISSUE THREAD

**Issue by xThyArmageddonx** [rwtema/extrautilities_old_issues#417]
I'm going to take a look at the config just to make sure nothing got changed on accident, but my ender quarry is acting kind of strange.  When it was connected to a TE energy cell, it would drain the max amount of energy that the cells output was, but run at the same speed regardless.  I removed the cell for a second to try and put something in that would try and pull energy more naturally, but when I removed the energy cell, the quarry still ran.  And I'm not talking used up it's internal energy, I mean after a minute of being removed from its power source, it's still running.  

I'm going to see if it'll keep going if I find nothing wrong with the config, but my only guess is that it's internal buffer, if it has one, has a huge amount of energy in it and that's why it's still working despite having no power source.  I'm still also not sure why it's pulling out the maximum amount of power it can be supplied with while still running at the same speed, I tested this as low as 200 rf/t and it was running the same speed at 200 rf/t as it was at 2000 rf/t, and I'm honestly surprised it's running at 200 rf/t, but my understanding of the calculations for this are very minimal.  

I have a pump, silk touch, and world hole upgrade installed, so I'm not sure the amount of rf/t it should be taking, so if anybody knew that, that'd be helpful as well, but the main problem right now is once it starts up, you can remove the power source and just let it go.

**Comment by jutoft** [comment]
Ender quarries have a 10M RF internal buffer.
Thats why it continues to run.

**Comment by xThyArmageddonx** [comment]
Alright, good to know thank you.  I continued my test more long-term after I posted this and noticed after prolonged time on that low output it did eventually slow down to a stop, so it must just take as much energy as the buffer can hold and then work with that energy.
