### ISSUE TITLE
Unlimited items

### ISSUE THREAD

**Issue by cindermike** [rwtema/extrautilities_old_issues#42]
Basically lock a better barrel from JABBA and then remove the item so their are 0 in the barrel, throw a transfer node on the bottom and the transfer node will still pull from the empty barrel. If done fast enough you can grab one of the items that the node removes [ex. wither skeleton seed or magic fertilizer] and you have unlimited of the item.

video showing whats done : 
https://www.youtube.com/watch?v=BntmUFxAUkE&feature=youtu.be

**Comment by TherminatorX** [comment]
Does this work with TE itemducts? If so, it's an issue with JABBA, not XU

**Comment by cindermike** [comment]
not sure i havent attempted it with any other items other than the barrel, pointed it out to a friend and he directed me here to report the issue

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
