### ISSUE TITLE
Crash with EXTRA UTILITIES [1.2.0][1.7.10][FORGE][1.7.10-Forge10.13.2.1240]

### ISSUE THREAD

**Issue by Artuto** [rwtema/extrautilities_old_issues#427]
The crash are in Pastebin: 

http://pastebin.com/GsdKnU9i

D:

**Comment by TherminatorX** [comment]
Any other details we might want to know, like how to reproduce this crash, or what you were doing when it happened?

**Comment by Artuto** [comment]
No, the error is on Mojang Screen

**Comment by TherminatorX** [comment]
Did you have a world open before hand, or was this when you first started up your pack?

**Comment by Artuto** [comment]
I used the 1.1.0b and no crash :/

**Comment by vavraCZe** [comment]
same https://github.com/rwtema/extrautilities/issues/406

my crash http://hastebin.com/poyewozuvo.coffee
