### ISSUE TITLE
[1.7.2] Crash on startup if Mariculture is installed

### ISSUE THREAD

**Issue by emouse** [rwtema/extrautilities_old_issues#43]
http://pastebin.com/JqHY11tw

**Comment by NolanSyKinsley** [comment]
I believe this is a mariculture issue, there are reports of crashes similar to this from mariculture when loaded with other mods. It has something to do with it overriding the vanilla fish.

**Comment by Peach774** [comment]
This issue has to do with the waterbreathing potion in specific. Wait until joshie fixes it, he just got internet access for the first time in a while.

**Comment by emouse** [comment]
I had it reported on his side as well, but it got deleted on there for whatever reason. 
Really don't know on which side is the issue.

**Comment by joshiejack** [comment]
https://github.com/joshiejack/Mariculture/blob/master/src/main/java/mariculture/fishery/items/ItemVanillaFish.java#L90

Line in question. But I can't see how that would crash, unless there is a null stack being passed somehow. Or a stack with a null item.

**Comment by rwtema** [comment]
I'm guessing it's because Mariculture hasn't implemented isPotionIngredient method but I'm not sure. I've added a catch for it, which will supress the crash at least.

**Comment by ProsperCraft** [comment]
Fingers are pointing in both directions :P
