### ISSUE TITLE
Energy pipe don't connect to ThermalExpansion machines

### ISSUE THREAD

**Issue by samuelpatro** [rwtema/extrautilities_old_issues#435]
And energy node connect and don't pull energy inside machine buffer.

![2014-12-15_18 31 49](https://cloud.githubusercontent.com/assets/3110002/5440436/ad7330ca-8488-11e4-8672-358ee9f1000b.png)

ThermalExpansion: [1.7.10]4.0.0B8
Extra utilities: 1.2.0

**Comment by mzx987** [comment]
Well thank God someone else posted this issue. I appear to have this exact same problem.
They don't hook to MineFactory Reloaded machines either. It may be a problem with either Extra Utilities, or the other ones.

**Comment by tivec** [comment]
I second this, I am getting the same issue. It is possible the issue is caused by an old version of the RF API in ExU. I'm using ThermalExpansion-[1.7.10]4.0.0B8-23 (and CoFHCore-[1.7.10]3.0.0B9-40) which updated recently. Solution would be to downgrade to the previous version of the CoFH mods.

**Comment by bochen415** [comment]
There is a new ExU version with the updated api.
From the changelog: 
Updated: Added support for new RF API interfaces
Check the new version and come back with a report
http://www.curse.com/mc-mods/minecraft/225561-extra-utilities/2222051

**Comment by samuelpatro** [comment]
Its working with new update :+1:
