### ISSUE TITLE
Various Crashes.

### ISSUE THREAD

**Issue by morlanius** [rwtema/extrautilities_old_issues#442]
Client side crash using extrautilities-1.2.1 forge 1.7.10 1236
http://pastebin.com/cKKWmn7X  <--crash log

persistent server side crash using version 1.1.0k
http://91.121.75.102/pages/error.log

**Comment by morlanius** [comment]
It wont let me edit so im adding this as a comment.
The first crash happens client side (not tested on server yet), game loads then bails whilst loading the world, giving me the impression that its likely @side(server) issue.

The second issue has something to do with transfer nodes I think happens only server side, once this crash has occurred the server will bail every time it attempts to load the chunk with the problem block in it. notice the cords are almost at the top of build height, important?

**Comment by GaXyLa** [comment]
Same here.
I have updated my Server and i havent the Issue.. But other Players have this and they Game crash in Multiplayer and Singleplayer..

Crash Log: http://pastebin.com/Q4tsK3Qf

From v.1.10k to 1.2.1
1.2.0 crash too

**Comment by GaXyLa** [comment]
Okay, i have found the Problem.
delete your Rei's Minimap and try it again.

**Comment by morlanius** [comment]
That solved it, thanks.
