### ISSUE TITLE
Deep Dark Silver Fish spawn

### ISSUE THREAD

**Issue by vabene1111** [rwtema/extrautilities_old_issues#447]
When running a quarry in the deep dark it spawns thousands of silver fish because its breaking the stone in the lower levels. We had 4 enderquarry's running in the deep dark and our server crashed after about 30 mins. Checking with opis showed that we had 15.000 silverfish in the deep dark.

**Comment by TherminatorX** [comment]
What version of ExU?

**Comment by vabene1111** [comment]
I have tested it on version 1.1.0k (sry that i forgot to mention that). I will test it in the latest version as soon as possible.

**Comment by vabene1111** [comment]
Just tested it with version 1.2.1 (using DW20 pack). Could not get the Quarry working at all in the deep dark (stopped after scanning 7/8 blocks). Also i needed to generate a new world since my old world was lost, so it was a new generated deep dark. Since didn't see silverfish when mining down by hand i guess its fixed in the latest version.
