### ISSUE TITLE
Ender Quarry problem registering chunk-preserving method

### ISSUE THREAD

**Issue by Threesins** [rwtema/extrautilities_old_issues#45]
When placing ender quarry it finishes Analysing the fence with the message: problem registering chunk-preserving method. After this the ender quarry reads as finished.

**Comment by TherminatorX** [comment]
Version?

**Comment by Threesins** [comment]
1.0.3a

**Comment by rwtema** [comment]
It probably means that the server has either disabled chunk-loading blocks or there are already too many ender quarries going and the system has run out of 'tickets'. Either case the block is working as intended.
