### ISSUE TITLE
Crash in creative taps

### ISSUE THREAD

**Issue by JadenWong** [rwtema/extrautilities_old_issues#46]
Got this crash while scrolling through the creative search tap
something with facades of bc and filing cabinet

forge-1.7.2-10.12.1.1065
extrautilities-1.1.0-prerelease-1
buildcraft-6.0.7

http://pastebin.com/FA0MTLuv

**Comment by JadenWong** [comment]
still in 
extrautilities-1.1.0-prerelease-1a
buildcraft-6.0.8

**Comment by rwtema** [comment]
Fixed in next prerelease
