### ISSUE TITLE
Soulcrafting takes too much of your player's "soul"

### ISSUE THREAD

**Issue by Zedrimar** [rwtema/extrautilities_old_issues#466]
this issue seems to make it to where when you do soul crafting you lose 3 full hearts rather than 1 (I was not using heart containers at the time) like it should have resulting in a loss in more health than intended. It also gives spam in chat of losing -10 max health three times.

**Comment by kurokuno** [comment]
if you have heart containers on its a flat 10% of your health not just 1 heart

**Comment by Zedrimar** [comment]
sorry, forgot to mention that I was not using heart containers. the client just spammed the taking of 10% 3 times :(
