### ISSUE TITLE
Builder's Wand

### ISSUE THREAD

**Issue by MapleSight** [rwtema/extrautilities_old_issues#47]
Stone slabs from vanilla Minecraft ( Block ID: 43:8 ) cannot be placed by the builders wand.
Crafted by combining 2 stone slabs in a crafting grid.

Is this intended?

**Comment by rwtema** [comment]
Seems to work fine for me. In any case, this seems to be an edge case, so I'm not worried about it

**Comment by MapleSight** [comment]
Maybe I didn't explain very well.

![newstoneslab](https://cloud.githubusercontent.com/assets/7471393/2871693/a176bc64-d31d-11e3-82c3-922ba428f8b2.png)

Block on the left is called a double stone slab. The block on the right is called a smooth full half slab. The smooth full half slabs do not work with Building Wands.

BUT if you happen to have the double stone slab blocks in your inventory, the wand will place douvle stone slabs over smooth full half slabs.

If you have any questions about my bug report, then please ask. It is a little confusing to explain since both blocks have the same name in-game.
