### ISSUE TITLE
Unable to make QED

### ISSUE THREAD

**Issue by lokkenpa** [rwtema/extrautilities_old_issues#495]
I have all the parts and when put into a crafting table (vanilla or TC version), it does not produce.  I just upgraded to the latest version of Extra Utilities from 1.1.0k.  It also did not work in that version.

Thanks in advance.

**Comment by Zaflis** [comment]
Are you playing Minecraft 1.6.4 with forge? Extra utils 1.2.1 is latest version for MC 1.7.10.

**Comment by lokkenpa** [comment]
Sorry about the late response...  but I think I fixed iit because now I can... I didn't do anything either...
