### ISSUE TITLE
Crash Report mentions ExtraUtilities

### ISSUE THREAD

**Issue by tonyism** [rwtema/extrautilities_old_issues#496]
http://pastebin.com/UnD4sgFQ

**Comment by jena-th** [comment]
Can you tell what was the problem ?

Like so, all peoples that may encounter the same could have a quick answer !
And pro-tip: to have well formatted crash-logs you can use [Gist](https://gist.github.com/) !
Which give us: [That crash log](https://gist.github.com/kane-thornwyrd/1ba688c0149cf0441ff9)

Thank you in advance ! :smiley:

**Comment by tonyism** [comment]
I am pretty sure it was a rendering issue conflict between my shaders and an incompatible version of optifine, because as soon as fixed that up the crash stopped. I could be very wrong, but thats the answer I felt comfortable with so I closed to issue before wasting anyone's time. :)

**Comment by jena-th** [comment]
Thank you ! :) You actually maybe helped some to avoid wasting time reporting something already resolved !
