### ISSUE TITLE
Crash extra utilities 1.7.10 in my pack

### ISSUE THREAD

**Issue by Printabl3** [rwtema/extrautilities_old_issues#497]
---- Minecraft Crash Report ----
// Don't do that.

Time: 2/1/15 11:59 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
    at com.rwtema.extrautils.ExtraUtilsMod.preInit(ExtraUtilsMod.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: com.rwtema.extrautils.item.ItemHeatingCoil
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 45 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/ItemEnergyContainer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 47 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.ItemEnergyContainer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 51 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.7.0_75, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 848821112 bytes (809 MB) / 1686110208 bytes (1608 MB) up to 3817865216 bytes (3641 MB)
    Mod Pack: ~~ERROR~~ NullPointerException: null
    LiteLoader Mods: ~~ERROR~~ NullPointerException: null
    LaunchWrapper: 32 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: net.smart.core.SmartCoreTransformer
          - Transformer: openmods.OpenModsClassTransformer
          - Transformer: openblocks.asm.OpenBlocksClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
          - Transformer: com.rwtema.extrautils.command.CommandASMCore
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 85 mods loaded, 85 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291-universal.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.74} [Not Enough Items](Not-Enough-Items-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    PlayerAPI{1.1} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized
    SmartCore{1.0} [Smart Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Trapcraft{v2.2.1a} [Trapcraft]([1.7.10] Trapcraft - v2.3.0a.zip) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized
    ArmorStatusHUD{1.28} [ArmorStatusHUD]([1.7.10]ArmorStatusHUD-client-1.28.jar) Unloaded->Constructed->Pre-initialized
    FLabsBF{4.1.2} [Better Furnaces]([1.7.10]Better_Furnaces_V4.1.2.jar) Unloaded->Constructed->Pre-initialized
    StatusEffectHUD{1.27} [StatusEffectHUD]([1.7.10]StatusEffectHUD-client-1.27.jar) Unloaded->Constructed->Pre-initialized
    Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized
    smeltchevsky{b3} [Armor Smelter](ArmorSmelter_1.7.2_b3.zip) Unloaded->Constructed->Pre-initialized
    Artifacts{1.0.6} [Artifacts](Artifacts-1.0.6.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.1.2} [iChunUtil](iChunUtil-4.1.2.jar) Unloaded->Constructed->Pre-initialized
    Grinder{4.0.0} [Grinder](AttachableGrinder-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    B0bGrowsOre{1.9.2} [B0bGary's Growable Ores](B0bGary's Growable Ores-1.9.2 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
    tennox_bacteria{2.3.2} [Bacteria Mod](Bacteria Mod 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.1} [BiblioCraft](BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    chisel{2.1.3} [Chisel](Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.0} [Damage Indicators](Damage-Indicators-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    props{1.11} [Decocraft](Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    mwaw{1.7.10-0.0.4} [Elemental Witch Mod](Elemental-Witch-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.27} [EnderStorage](EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized
    examplemod{1.0} [Example Mod](ExtraShoes-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Extrashoes{2.0 Beta Build 0.1} [ExtraShoes](ExtraShoes-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.7} [Waila](Waila-1.5.7a_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct](TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed->Errored
    extvil{1.7.10-2.4} [Extended_Villages](extvil-1.7.10-2.5.jar) Unloaded->Constructed->Pre-initialized
    F2L{1.7.10b} [Flesh2Leather](Flesh2Lether [1.7.10b].jar) Unloaded->Constructed->Pre-initialized
    ganysend{1.8.8} [Gany's End](Ganys End-1.8.8.jar) Unloaded->Constructed->Pre-initialized
    ganysnether{1.7.7} [Gany's Nether](Ganys Nether-1.7.7.jar) Unloaded->Constructed->Pre-initialized
    ganyssurface{1.9.5} [Gany's Surface](Ganys Surface-1.9.5.jar) Unloaded->Constructed->Pre-initialized
    Hats{4.0.1} [Hats](Hats-4.0.1.jar) Unloaded->Constructed->Pre-initialized
    HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized
    imc{1.6} [Improving Minecraft](Improving-Minecraft-Mod-1.7.10%281%29.jar) Unloaded->Constructed->Pre-initialized
    InfernalMobs{1.5.9} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    instantblocks{1.5.4} [Instant Blocks](InstantBlocks_v1.5.4.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized
    minegicka3{1.0.0} [Minegicka 3](minegicka3-1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    MineTweaker3{3.0.9} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized
    MTRM{1.0} [MineTweakerRecipeMaker](MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) Unloaded->Constructed->Pre-initialized
    mobsandwichesmod{1.0} [Mob Sandwiches Mod](Mob-Sandwiches-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    exomaster_mystictools{1.0} [Mystical Tools](Mystical Tools-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized
    ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-430.jar) Unloaded->Constructed->Pre-initialized
    powerGems{0.3.0} [Power Gems](Power-Gems-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ProjectE{Alpha 0.2c} [ProjectE](ProjectE-Alpha 0.2c.jar) Unloaded->Constructed->Pre-initialized
    radixcore{1.3.4} [RadixCore](RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized
    runicdungeons{0.9.3} [Runic Dungeons](runicdungeons-0.9.3.jar) Unloaded->Constructed->Pre-initialized
    rwbyCraft{1.7.2} [RWBY Craft By KelcoK22](rwby_c_1.7.10_V1.2.jar) Unloaded->Constructed->Pre-initialized
    SaintsCore{0.8} [Saintscore](SaintsCore-0.8-Minecraft-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    mod_Saintspack{0.8} [Saintspack](SaintsPack-0.8-Minecraft_1.7.10) Unloaded->Constructed->Pre-initialized
    securitycraft{v1.6.1} [SecurityCraft](SecurityCraft v1.6.1 for 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    wuppy29_simplerecipes{1.8.2} [Simple Recipes](Simple Recipes 1.7.10-1.8.2.jar) Unloaded->Constructed->Pre-initialized
    SmartMoving{15.2} [Smart Moving](SmartMoving-1.7.10-15.2.jar) Unloaded->Constructed->Pre-initialized
    SmartRender{2.0} [Smart Render](SmartRender-1.7.10-2.0.jar) Unloaded->Constructed->Pre-initialized
    tpmod{1.9.0} [Teleportation Mod](Teleportation Mod 1.9 for MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized
    kitchen{1.3.8} [The Kitchen Mod](TheKitchenMod-1.3.8-1.7.2-10.jar) Unloaded->Constructed->Pre-initialized
    TiCTooltips{1.2.0} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.0.jar) Unloaded->Constructed->Pre-initialized
    toolsdoneright{1.1.4} [Tools Done Right](Tools Done Right by NukeDuck [1.7.10][1.1.4].zip) Unloaded->Constructed->Pre-initialized
    Translocator{1.1.1.14} [Translocator](Translocator-1.7.10-1.1.1.14-universal.jar) Unloaded->Constructed->Pre-initialized
    sgs_treasure{2.4} [SGS Treasure!](Treasure-1.7.10-2.4.jar) Unloaded->Constructed->Pre-initialized
    wawla{1.1.0} [What Are We Looking At](Wawla-1.1.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    zipline{1.0} [Zipline](Zipline-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    denseores{1.0} [Dense Ores](denseores-1.4.2.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by jena-th** [comment]
To have something more readable, you can use [Gist](https://gist.github.com/). :smiley:

**Comment by Printabl3** [comment]
This is Gist file: https://gist.github.com/Dadob00/973298643c753c89b020

**Comment by jena-th** [comment]
Thank you. That's better.

Is there any specific scenario in which the crash happen ?

Beccause it look like you used the heating coil in something that doesn't seem to like it…

Can you also try to manually downgrade extra utilities to 1.2.0 or 1.1.0k ?

**Comment by Printabl3** [comment]
I already updated to version 1.2.1 (latest ) , but I still crash , in this pack there are only mod adventure , there aren't technic mods

**Comment by Printabl3** [comment]
I had not seen the word downgrade, I'll try and let you know

**Comment by jena-th** [comment]
Sorry, I've realized after posting my comment you were already up-to-date, therefore I edited my comment.

The types of mods used are meaninless. The only thing we can see is that something is using the heating coil, and is not implementing a method he expect, leading to this error.
Finding whom the heating coil is calling back could be a serious help, you could afterward try to help extra utilities and the culprit mod to have matching [API](https://en.wikipedia.org/wiki/Application_programming_interface) versions, hence my request to test with different versions of EU.

This look like a modpack related issue, but because you seems intelligent and open to dialog, I try my best to help you.

**Comment by Printabl3** [comment]
I tried as advised me to downgrade the version 1.1.0k , but the problem is that it keeps giving me the error of the heating coil .

**Comment by Printabl3** [comment]
I tried to remove the Not Enough Items and starts, this error intrigued me: https://gist.github.com/Dadob00/9a95fa26bf8dc3f49ac9

**Comment by jena-th** [comment]
@Dadob00  you found the solution ?

**Comment by Printabl3** [comment]
The mod was that the crash was ExtraTic , I removed.
Thanks for help
Davide

**Comment by jena-th** [comment]
Thank you for reporting the bug and his cause !

Has A newbie modpacker I'll pay a special attention to those two thanks to you ! :)
