### ISSUE TITLE
Solar generators do not react to redstone output from computercraft computers

### ISSUE THREAD

**Issue by Mercwear** [rwtema/extrautilities_old_issues#5]
*\* Please see comment 3 below for updates **

The solar generator in 1.0.3c will not change states from charging to transmitting when a redstone computer begins to output a redstone signal.

They will change states if I first run redstone from the computer and place the generator next to the redstone however this prevents me from being able to use the generator with the open peripherals mod since it will no longer be touching the computer and does not allow for the wired modem to be placed on it.

To be clear, the computercraft command I am using is:
redstone.setOutput("bottom", true)
the generator is on the bottom of the computer and does not change states once this command is issued (all other redstone devices work with it).

**Comment by Mercwear** [comment]
*\* Please see comment 3 below for updates **

One more thing I just noticed: Instead of transmitting upon receiving the redstone signal from computercraft the generator simply stops doing anything. It will no longer increase (or decrease) the amount of energy stored.

**Comment by Mercwear** [comment]
After more testing I have discovered the generator does respond correctly to the redstone signal from comptercraft. The bug is actually a display bug. The generator never displays the 10 second countdown to let the user know it's switching states in it's GUI. After 10 seconds it does start to transmit RF.

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
