### ISSUE TITLE
[Server-side] "Serious error calling getRenderType()"

### ISSUE THREAD

**Issue by Lordmau5** [rwtema/extrautilities_old_issues#501]
**Crashlog**: http://puu.sh/fHiFL/743fb0e23f.txt
**How to reproduce**: Install [Integrated Circuits](https://github.com/Victorious3/Integrated-Circuits) and Extra Utilities on a server, boot it up and wait for the server to die during _Extra Utilities' postInit-phase_.
**Current workaround solution** _(example)_: https://github.com/Victorious3/Integrated-Circuits/commit/c0b51de40c758c426b3c5aa0e3f41d6577a56916

**Fix, that'd have to be done to Extra Utilities**: Stop usage of Client-functions on the server-side.
Just stop.

**Comment by Victorious3** [comment]
This is literally asking for trouble, besides checking if it is a fence in that way being a really harsh workaround. I'd just catch the error silently, as getRenderType() isn't meant to be called on the server side, as the exception suggests already. It should't crash the game because of that.

**Comment by rwtema** [comment]
getRenderType() is a server-side method and is called by the vanilla server.

**Comment by Victorious3** [comment]
Yeah, I looked it up and yes, vanilla is using it several times for entity collision and that alike. That was unexpected, gonna blame vanilla for it's terrible inconsistency then... bad practice is bad practice. Sorry for the inconvenience.
