### ISSUE TITLE
Pseudo Inversion Sigil Ritual : killing golem do nothing

### ISSUE THREAD

**Issue by Lorenzo77** [rwtema/extrautilities_old_issues#509]
hello,

i try to activate the Pseudo Inversion Sigil, all seems ok but nothing append when i kill the golem.
this is sad, i really want the super builder wand :-)
not sure about this issue ... maybe a mod is preventing the normal behaviour ?

---

[CHAT] Stabilization Ritual
[CHAT] 
[CHAT] - To the north, Children of Fire: 12 / 12
[CHAT] - To the south, Gifts of Earth: 12 / 12
[CHAT] - To the east, Descendants of Water: 12 / 12
[CHAT] - To the west, Spices of Air: 12 / 12
[CHAT] 
[CHAT] Ritual Markings: Strength - 68 / 100 / 64
[CHAT] 
[CHAT] Everything is prepared.
[CHAT] 
[CHAT] Sacrifice one who would sacrifice himself.

---

appliedenergistics2-rv1-stable-1.jar
BigReactors-0.4.1A2.jar
ChickenChunks-1.7.10-1.3.4.17-universal.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0B9-40.jar
EnderIO-1.7.10-2.2.8.344.jar
extrautilities-1.2.1.jar
FinderCompass-1.7.10.jar
InventoryTweaks-1.58-147.jar
MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
OptiFine_1.7.10_HD_B5.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-13.jar
Zans-Minimap-No-Radar-Mod-1.7.10.jar

---

minecraft 1.7.10
forge forge-1.7.10-10.13.2.1291
java 7.71
windows XP sp3

**Comment by Elvarion** [comment]
Isnt the Ritual Markings: Strength supposed to be 64/64/64?

**Comment by Rious** [comment]
you are doing the ritual wrong. to many of either redstone or string.
it's supposed to be 64/64/64
