### ISSUE TITLE
[1.7.2] Texture Startup Crash

### ISSUE THREAD

**Issue by Xcox123** [rwtema/extrautilities_old_issues#51]
Due to what I suspect Optifine's connected textures, if I load Extra Utilities and Optifine together I get this crash --> http://pastebin.com/QUrAUfrn

The reason I personally suspect Optifine's connected textures is because, the MultiMC launcher log( line 616 --> http://paste.ee/p/jOI2L ) optifine had just finished loading connected textures, and then it crashed with a texture issue. It may be something completely different, but I hope you can see where I'm coming from.

**Comment by rwtema** [comment]
Yeah it's optifine. Nothing I can do about it.

**Comment by bjornlc** [comment]
work`s with 1.1.0-prerelease-3
