### ISSUE TITLE
[Resolved][1.2.2] Unable to craft things with the Unstable Ingots

### ISSUE THREAD

**Issue by PierceSG** [rwtema/extrautilities_old_issues#518]
I hope it isn't intermod compatibility issues since I've now went back to 1.2.1 and I can craft items with the Unstable Ingots while I can't in 1.2.2.

Let me know if you want more information like the mods I have and stuffs.

**Comment by ghost** [comment]
I'm guessing this led to your death a lot. :P
And losing a lot of diamonds.
Try crafting with creative spawned stable ingots and see if it works.
Also try multiple recipes and crafting tables. (AE crafting terminal, TCon crafting station, autocrafter, etc)

**Comment by PierceSG** [comment]
I've tried spawning the ingots in via creative mode and still can't craft with them.

So far, I've only tried with vanilla crafting table and I've went back with 1.2.1.

**Comment by Zedrimar** [comment]
be wary that in the new version sticks are replaced with obsidian.....

**Comment by PierceSG** [comment]
I am using obsidian block for the craft. Not working.

**Comment by PierceSG** [comment]
Resolved. I shouldn't be shift clicking the ingots out of the crafting table. It bugs them.
