### ISSUE TITLE
[1.7.2] Crash on startup with ender constructor

### ISSUE THREAD

**Issue by Properjob** [rwtema/extrautilities_old_issues#52]
http://pastebin.com/rde0NUSg

**Comment by darkphan** [comment]
Same here. It seems to be some conflict between Totemic and Extrautilities, removing Totemic for me resolved it for now.

**Comment by Properjob** [comment]
@darkphan Thanks i was dreading trying combinations of mods to see what was causing it

**Comment by pgrosslicht** [comment]
Same problem here, however I don't have Totemic.

My Mods:
[1.7.2] ChickenShed (v1.1.3).jar
[1.7.2]bspkrsCore-universal-6.8(1.7.2).jar
[1.7.2]TreeCapitator-universal-1.7.2.r02.jar
advancedgenetics-1.5.2-1.7.2.jar
appliedenergistics2-rv0-alpha-107.jar
Aroma1997Core-1.7.2-1.0.2.1.jar
Baubles-1.7.2-1.0.0.10.jar
bdlib-mc172-1.3.0.8.jar
BetterChests-1.7.2-1.1.0.4.jar
BiblioCraft[1.6.3][MC1.7.2].jar
Blood Magic-v1.0.0d.jar
Botania beta-29.jar
buildcraft-6.0.9.jar
CodeChickenCore-1.7.2-1.0.0-universal.jar
CodeChickenLib-1.7.2-1.1.0.76-universal.jar
CompactSolars-1.7.2-4.4.28.310-universal.jar
CraftGuide-1.6.8.1.zip
CraftingPillars-MC1.7.2-1.5.jar
EnchantingPlus-1.7.2-2.0.1.6.jar
enderio-1.1.0_alpha.50.jar
EnderTanks-rev15.jar
ExtraCells-2.0.0.jar
extrautilities-1.1.0-prerelease-1b.jar
forestry-2.4.0.0-711.jar
ForgeMultipart-1.7.2-1.1.0.276-universal.jar
gendustry-mc172-1.2.0.10.jar
industrialcraft-2-2.1.476-experimental.jar
ironchest-1.7.2-6.0.14.719-universal.jar
Jabba_1.1.3_1.7.2.jar
Mantle-1.7.2-0.2.8.jar
Metallurgy-1.7.2-4.0.1.52.jar
MetallurgyCore-1.7.2-4.0.1.16.jar
MineChess-1.3.8.jar
natura-1.7.2-2.2.0a3.jar
neiaddons-mc172-1.11.0.3.jar
NotEnoughItems-1.7.2-1.0.1-universal.jar
OpenComputers-MC1.7.2-1.2.9.136-universal.jar
PneumaticCraft-1.1.7.jar
Railcraft_1.7.2-9.0.0.0.jar
RefinedRelocation-1.7.2-1.0.4a.jar
secretroomsmod-1.7.2-4.6.3.348.jar
ShetiPhianCore-v2.jar
SlimevoidLibrary-2.0.4.6.jar
SSR_1.7.2 0.9a.jar
TConstruct-1.7.2-1.6.0.a14.jar
Thaumcraft-1.7.2-4.1.1.11.jar
ThaumcraftExtras-2-1.0.jar
Thaumic Exploration 0.6.0.jar
ThaumicInfusion-1.7.2-0.991.Beta.jar
The Dalek Mod - 1.7.2.zip
TMechworks-1.7.2-0.2.7.jar
twilightforest-1.7.2-2.0.3.jar
voxelmap-1.7.2-1.0.jar
Waila-1.5.2a_1.7.2.jar
WaslieCore-1.1.jar
WirelessRedstoneCore-1.8.0.0.jar
