### ISSUE TITLE
[1.2.2] tools made from unstable ingots behave as their mundane counterparts

### ISSUE THREAD

**Issue by Zedrimar** [rwtema/extrautilities_old_issues#522]
the destruction pickaxe for example doesn't destroy blocks... it acts just like a normal pick

**Comment by MissPotato** [comment]
Intended feature.

**Comment by Zedrimar** [comment]
no the destruction pick should permanently destroy blocks.

**Comment by PierceSG** [comment]
No, the v1.2.2 changelog did mention that they are now mundane tools with infinite durability.

It is a feature.

**Comment by Zedrimar** [comment]
oh ok I am sorry!! I forgot to read the log this time lol
