### ISSUE TITLE
Breaking drums with Awakened Ichorium Pickaxe causes them to disappear

### ISSUE THREAD

**Issue by anaveragehuman** [rwtema/extrautilities_old_issues#539]
I have noticed that using Thaumcraft's Awakened Ichorium Pickaxe in "square mode" or "line mode" causes a drum to be destroyed but not dropped if in the pickaxe's range. Using the pickaxe in "block mode" seems to work.

**Comment by vicky5124** [comment]
thaumic tinker bug, report here https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues
