### ISSUE TITLE
Request: Option or ability to hide pipe jackets and microblock fences in NEI

### ISSUE THREAD

**Issue by GhostCrab** [rwtema/extrautilities_old_issues#54]
Currently there is no way to hide pipe jackets and microblock fences in NEI (of which there are multiple pages depending on the number of mods being used). Forge Multipart provides this functionality though right-clicking the "Microblocks" tab in the Item Subsets drop-down menu. Extra utilities does not have a specific tab for pipe jackets or fences so it is impossible to hide only those recipes.
If the pipe jackets and fences were in separate tabs in NEI, or if there was some config option somewhere to disable or hide these recipes, it would be appreciated.

**Comment by rwtema** [comment]
I've placed microblocks into a seperate creative tab which will allow them to be disabled once NEI adds that feature back in.

note: This is 1.7 only
