### ISSUE TITLE
End Stone Superior to Ender Core

### ISSUE THREAD

**Issue by Daniel-USA** [rwtema/extrautilities_old_issues#540]
Consistently End Stone is superior to Ender Core even though Ender Core is more difficult to craft. Is this on purpose or is there an error? I am using 1.7.10 FTB Infinity 1.2.1. Provided is a picture. 

It shows all End Stone grown lilies are at mature while of the 3 Ender Core lilies only 1 has reached maturity.

I have them all growing with direct access to sunlight (because I believe that direct sunlight helps it grow faster [don't know if it's true]). What is the purpose of Ender Core then?

![2015-03-19_20 36 48](https://cloud.githubusercontent.com/assets/11565004/6744483/1bc51b2c-ce78-11e4-94b2-9769e3c27fe8.png)

**Comment by TechDweebGaming** [comment]
http://m.ftbwiki.org/Ender_Core

That says ender lily's grow faster so this is probably a bug.

**Comment by Daniel-USA** [comment]
I knew I had read it some where but I couldn't remember the source. I know for a fact that End Stone grown lilies are growing at a consecutive faster pace than Ender Core grown lilies.

**Comment by TechDweebGaming** [comment]
Ya it's definitely a bug then. If I had access to the source I could try to help fix it but this isn't open source,  so really only Tema can fix it... Sorry.

**Comment by freddyheppell** [comment]
I believe it allows extra growth ticks to be applied, for example via the watering can.

**Comment by TechDweebGaming** [comment]
Hm that may be it...

**Comment by Daniel-USA** [comment]
I never read that on the wiki but from my understanding it works with extra ticks even on Endstone or Dirt as long as you apply the right kind of Tick. Bonemeal will revert the growth process.

**Comment by freddyheppell** [comment]
Shouldn't be too hard to try. In a creative world cheat in the better watering can and try watering some enderlilies, some on endstone and some on ender cores. The ones on endercores should grow first.

**Comment by Daniel-USA** [comment]
I got everything to try it in my world already. I will post if there is a difference or not.

**Comment by Optimoos** [comment]
Bumping this issue, appears to still be the case. The in-game NEI description of the ender core doesn't actually describe the ender-lily growth acceleration, has this functionality simply been removed?

**Comment by Daniel-USA** [comment]
I never tested it out in my game but it is true that Endercores allow ticks to work on the Ener-Lillies using other mods like Thaumcraft or Blood Magic.
