### ISSUE TITLE
Spikes (wooden) don't always kill mobs 

### ISSUE THREAD

**Issue by Bloodadept** [rwtema/extrautilities_old_issues#544]
I'm playing the Agrarian Skies 2 alpha and i'm noticing that mobs aren't always dying while standing on spikes (of the wooden variety). Some mobs have also shown in waila as having 0 health but will remain alive until personally hit. I'm noticing this problem mostly with skeletons, but there are the occasional zombies who do this.

Edit: I'm wrong, they do take continual damage, however they're going down to 1 hp and staying that way
![2015-03-22_17 00 54](https://cloud.githubusercontent.com/assets/11604159/6772216/ccbb6686-d0b5-11e4-8ef9-4806c8cf5640.png)
![2015-03-22_17 05 13](https://cloud.githubusercontent.com/assets/11604159/6772215/ccba94c2-d0b5-11e4-971f-ac642ffd3ebe.png)
![2015-03-22_17 07 40](https://cloud.githubusercontent.com/assets/11604159/6772222/005e7a82-d0b6-11e4-9fc2-aa9a6d5b3a72.png)
![2015-03-22_17 12 13](https://cloud.githubusercontent.com/assets/11604159/6772406/31ec8964-d0ba-11e4-90ed-f251aa8abf87.png)
![2015-03-22_17 11 51](https://cloud.githubusercontent.com/assets/11604159/6772407/343bd35a-d0ba-11e4-9991-75d1cbfeab95.png)

**Comment by TherminatorX** [comment]
That is the exact purpose of wooden spikes: to lower to 1 HP so something else can kill them.
Not a bug in any way, shape, or form.

**Comment by Bloodadept** [comment]
Oh... in that case ignore this
