### ISSUE TITLE
Crash Help!

### ISSUE THREAD

**Issue by TechDweebGaming** [rwtema/extrautilities_old_issues#545]
Ok so I develop a modpack for a small pixelmon server and it runs on the Technic Launcher. The pack works fine without Extra Utilities but whenever I add it I get a crash upon joining the server...
Any help would be appreciated!

Crash Report: https://gist.github.com/TechDweebGaming/6f75b3b10760382e1f35

Mod List:
Minecraft Forge
CodeChickenLib
Forge Multipart
MrTJPCore
Advanced Machines
Advanced Solars
AOBD
AE2
Archimedes Ships
Backpack
Bdlib
Bennie's Mods
Buildcraft
Carp Blocks
Chisel
CCC
CoFH Core
ComputerCraft
CraftGuide
Custom NPCS
Extra Utilitys
Flan's Mod
FMPIntegration
Forestry
Forge Relocation
Forge RelocationFMP
Gendustry
IC2
Inventory Tweaks
LogisticsPipes
Mantle
MFR
MineTweaker 3
Pixelmon
Pressure Pipes
Project Red (Base, Compat, Integration, Lighting, Mechanical and World)
Railcraft
Rei's Minimap
TConstruct
Thermal Dynamics, Expansion and Foundation
TMechworks
Wireless Redstone (Chicken Bone's Edition)

If you have any other questions please ask!

Edit: Yes, I know the crash report says I have Optifine which is not on the list of mods, and yes I do but another server member got the same error WITHOUT Optifine, so I don't think its that.

**Comment by TherminatorX** [comment]
#406 Dupe issue, conflict with Rei's Minimap. Use a different minimap for now.

**Comment by TechDweebGaming** [comment]
Thx!

**Comment by TechDweebGaming** [comment]
Is there a patch out by any chance?
