### ISSUE TITLE
Problems loading with latest gregtech & latest extra utilities (1.7.2)

### ISSUE THREAD

**Issue by BBoldt** [rwtema/extrautilities_old_issues#55]
Forge 10.12.1.1065
gregtech-openalpha 2
industrialcraft 2.1.476 exp
extrautilities-1.1.0 prerelease 2

When starting the game with these mods, it never loads and keeps spitting out errors to the console. I had to kill minecraft with task manager.

Console log (sorry, large file):
https://www.dropbox.com/s/1x5d14we9tzf7bb/ouch.txt

If you need any more information, just ask.

**Comment by BBoldt** [comment]
Here is what Greg said about it:

http://forum.industrial-craft.net/index.php?page=Thread&postID=157547#post157547

**Comment by rwtema** [comment]
The World instance passed to the 'difficulty-specific' recipe handler doesn't have proper difficulty data. Easy fix on my end though.

**Comment by BBoldt** [comment]
Just confirming that this is indeed fixed in the latest version.

Thanks.
