### ISSUE TITLE
Downgrade forge

### ISSUE THREAD

**Issue by Pilad** [rwtema/extrautilities_old_issues#569]
Please make for forge 1291 extrautilities-1.2.4a

**Comment by ThatGuyBob** [comment]
1.2.4a requires Forge 10.13.3.1355
The Curse Voice Minecraft launcher does not support 10.13.3.1355 (yet)

Only workaround as of right now is to downgrade Extra Utilities to 1.2.4 until Curse supports the new Forge version.

**Comment by Pilad** [comment]
Rebuild in Eclipse modes(extrautilities) need to forge a 1291. I do not understand where does curseforge?

**Comment by Dream-Master** [comment]
Yes I prefer a 1291 Version too. Please rebuild with Forge 1291. Thanks

**Comment by Nick-77ab2** [comment]
PLEASE 1352 or less would really work

**Comment by Nick-77ab2** [comment]
cant play at all with this mod unless its downgraded since a lot of other mods cause crashes in 1355 and up

**Comment by Nick-77ab2** [comment]
because of the change in fluid stuff so that modders can fix their fluids

**Comment by jznomoney** [comment]
I prefer you do a downgraded build too.

**Comment by nightstalker6669** [comment]
a downgrade would be nice, considering 1.2.4a fixes some major game breaking bugs.

**Comment by bochen415** [comment]
Relevant:
https://twitter.com/Extra_Utilities/status/586249135013154816

**Comment by Staegrin** [comment]
We'll have to stick with version 1.2.3 as the last stable version until every mod which handles fluids updates it's code to work with the new versions of forge. 
RWTema doesn't want to downgrade as is his choice. All I say to him is keep up the good work and thanks for the amazing mods.

**Comment by bochen415** [comment]
Remember to check the _latest_ Forge versions. ~~1358 fixed A LOT~~

**Comment by Nick-77ab2** [comment]
not enough doh :( Staegrin you can stick to 1.2.4 as that works -_-
well with 1352 forge that is and there's no issues in that with mod creators

**Comment by Staegrin** [comment]
I've actually made a minecraft instance with forge 1358. Three different mods with fluid tanks crashed when placing block/looking up tanks in NEI.

**Comment by Dream-Master** [comment]
Why you using a not recommend Version of Forge. Tell us the reason.

**Comment by Staegrin** [comment]
@Dream-Master 
10.13.2.1291 is the recommended version
I wanted to try version 1.2.4a of extra utilities. This required a version of 10.13.3.1355 or higher.
So I downloaded the latest version of forge which was 1358 and started minecraft fine. Sadly in game several mods didn't handle the latest foge version all that well.

**Comment by bochen415** [comment]
@Nick-77ab2 is right
Use the last Forge build before the fluid registry changes, that means 1352 or use the recommended build (1291). 
Check the Forge changelog if in doubt.
Of course that means no 1.2.4a.

**Comment by Dream-Master** [comment]
Newer Forge lag on my Server a lot so I dont want to to update the pack for only one Mod. I find another way solve the problem. Btw i using 130 Mods why only Extra utilities goes this way. All other Mods using recommended Version of Forge.

**Comment by Dream-Master** [comment]
I dont get it why some Mod Authors so obstinate. I want to know the Reason.

**Comment by atomic7777** [comment]
Some of other mods won't get support for Forge 1355, because their authors stopped at 1291 and now abandoned 1.7.10.
Please, take also a note about many Cauldron servers - last (not official) Cauldron versions are 1291, 1307, 1343. That means houndreds of servers and thousands of players. I know we can stick to 1.2.3 and I'll probably do that, but just keep in mind people who whould love to see your new mod version, because 1355+ is not going to be widely used in nearest weeks. 
It's also a funny thing, that bugged 1.2.4 and fixed 1.2.4a need different forge versions...

**Comment by Nick-77ab2** [comment]
this one came out before the other...

**Comment by Nick-77ab2** [comment]
Just be patient guys

**Comment by Nick-77ab2** [comment]
and stop whinning as pretty much all big mod makers have fixed this

**Comment by StarkRG** [comment]
This just in: according to Nick-77ab2 Mekanism is not a major mod. They are apparently only building against recommended Forge versions.

https://github.com/aidancbrady/Mekanism/issues/2542

**Comment by unpairedbracket** [comment]
Just as a note, I did update Mekanism to forge 1365 nearly a week ago, but it caused crashes with recommended forge and there was much complaining so I reverted to 1291. It seems we can't please everyone so I will re-update to latest.

**Comment by Nick-77ab2** [comment]
i said ALMOST all major mods -_- read
