### ISSUE TITLE
Cursed Earth doesn't work in Mushroom Island biomes

### ISSUE THREAD

**Issue by radcom** [rwtema/extrautilities_old_issues#57]
Don't know if its meant to or not but it seems (to me at least) that the cursed earth doesn't spawn any mobs in a Mystcraft Mushroom Island Biome void age I tested in my overworld and it works, I looked online and there doesn't seem to be a clear answer if it works or not

**Comment by rwtema** [comment]
Mobs won't spawn in mushroom island biomes, so cursed earth won't spawn them either. Working as intended.

**Comment by radcom** [comment]
Thanks for the reply and the great mod
