### ISSUE TITLE
[Suggestion] Please, downgrade your Forge version.

### ISSUE THREAD

**Issue by anishin** [rwtema/extrautilities_old_issues#577]
RWTema!
Firstly, great thanks fo your work!
Secondly, please, downgrade required Forge version of Extra Utilities to 1291. I (and many people) want to have this mod in modpacks. But the most mods are incompatitible with newest FMP (build 331) and new FluidRegistry/FluidContainerRegistry.
I believe, that it is temporary measure. It's needed until the next stable release of Forge.

Now Extra Utilities mod makes any modpack unplayable, because it requires Forge build 1355, that is incompatitible with build 1291 (which the most modders use).

I hope for your understanding.
P. S. Sorry for my English. I'm from Russia.

**Comment by Tsyklop** [comment]
https://github.com/rwtema/extrautilities/issues/569

**Comment by Nick-77ab2** [comment]
you should close this as this is un-needed, if you would so kindly read the forge changes, and figure out why the mods crash with the higher version of forge, its not forge but the other mods' problems itself

**Comment by Nick-77ab2** [comment]
nvm didn't see you already knew, but just be patient and wait
