### ISSUE TITLE
Configuration Options for Transfer Node Mining

### ISSUE THREAD

**Issue by MaPePeR** [rwtema/extrautilities_old_issues#58]
There is no way to configure the rate at which the transfer node mines or disable it.
Also no way to configure the effect of mining upgrades.

I would like if i could configure it in a way the transfer node does not mine cobble until it has a mining upgrade.

(If this would be Open Source i would add it myself - please open source it)

**Comment by rwtema** [comment]
No.

**Comment by MaPePeR** [comment]
:(

**Comment by MaPePeR** [comment]
> Note: A change from 1.6 is that mining upgrades are now called 'Interaction upgrades', and you will require at least one in order to pump liquid or generate cobblestone or craft items.

Thanks.
