### ISSUE TITLE
[Feature Request] Soul Rare Drop

### ISSUE THREAD

**Issue by TheLMiffy1111** [rwtema/extrautilities_old_issues#596]
Hello. Sometimes people want 100% health in modded, so can you please make it so that when killing mobs with etheric sword there is a super rare chance of getting a soul fragment?

**Comment by Shahelion** [comment]
Wouldn't that completely invalidate the reason for using the Soul Fragment in crafting in the first place? It's supposed to be a huge cost, 10% of your maximum health. Having a chance to just randomly get that back, no matter how low, breaks that. Choose, super watering can, or full health. You can always use a mod with uncrafting to get it back if you don't want it anymore.

**Comment by TheLMiffy1111** [comment]
Um it's already added so I'll close this

**Comment by Shahelion** [comment]
Wait, is that really a thing now? When was that added?
