### ISSUE TITLE
Duplication bug with nodes when they are moved    

### ISSUE THREAD

**Issue by zed-hex** [rwtema/extrautilities_old_issues#601]
If a node is moved with funky locomotion when a player is still accessing it any item pulled out of the inventory of the node will be duplicated this works with the upgrade slot as well (I have not tested with other means of moving the node but I’m guessing it will have a similar result). I would suggest fixing this problem in the same way other mods handle it so it kicks the player out of the inventory when it is moved/ broken.

Relevant mods to bug:
Extra utilities 1.2.4b
Forge 1387
Funky locomotion beta 5a

**Comment by junrw** [comment]
Same as issue #519
