### ISSUE TITLE
tile.extrautils:filing.5.name keeps chunks force loaded

### ISSUE THREAD

**Issue by GameBurrow** [rwtema/extrautilities_old_issues#603]
We noticed that our chunks are being force loaded. When we open /chunkloaders we see that there are 28 forced chunks and they all belong to extra utilites:
![Chunckloades](http://i.imgur.com/cKYiKZe.png)
If we check Opis we see that there is only one EU item what we have excatly 28 and it's:
![Opis](http://i.imgur.com/p5ePuVP.png)
Forge version

> 1.7.10-10.13.3.1401 

List of installed mods and their versions:

> AppleCore  1.1.0
> Archimedes Ships Plus   1.7.10.B
> Bibliocraft 1.10.4
> Big Reactors    0.4.3A
> Carpenter's Blocks  3.3.6
> Chisel 2    2.3.10.37
> ComputerCraft   1.73
> EnderIO 2.2.8.367
> Extra Utilities 1.2.4b
> Flan's Mod  4.10.0
> Flan's Mod - Manus Civil    1.7.10d
> Flan's Mod - Manus DayZ 1.7.10d
> Harvestcraft    1.7.10h
> Hunger Overhaul 1.7.0-beta6
> Iron Chests 2   6.0.62.742
> Lamps and Traffic Lights    1.11
> Malisdoors  1.7.1
> MineFactory Reloaded    2.8.0-104
> MrCrayfish Furniture mod    3.4.7
> OpenComputers   1.5.9.21
> Plant Mega Pack 4.17
> Project Zulu    1.4C2
> Railcraft   9.6.1.0
> Redstone(Remain) in Motion  2.6.1.2
> RoadWorks   2.02
> The Spice Of Life   1.2.3
> Thermal Expansion   4.0.1-182
> Tinckerers Construct    1.8.4a
> Tinker Tweaks   2.1.4
> Morpheus    1.6.4
> Better Title Screen 1.1
> DamageIndicators    3.2.3
> Inventory tweaks    1.58-147
> Journeymap  Unlimited 5.0.1
> MineTweaker 3   3.0.9C
> NEI 1.0.4.100
> NEI Addons  1.12.7.21
> Radio mod   1.7.10 PRE4
> TabbyChat   1.11.2.2
> Trade Booth Mod 1.7.10.1
> Waila   1.5.10
> Waila Harvestability    1.1.2

**Comment by TherminatorX** [comment]
Keep an eye on Twitter. @rwtema rarely comes on here anymore, but is always there. I suggest pointing it out via a tweet.

**Comment by WhiteFire-Sondergaard** [comment]
Why was this issue closed? I don't see a solution and it's happening to others.
