### ISSUE TITLE
bugs ive noticed in the proccess of building/testing my modpack

### ISSUE THREAD

**Issue by plaguewolf** [rwtema/extrautilities_old_issues#605]
i think i have noticed that there are already post about these specific bugs, maybe not, but please forgive me in advanced if i reiterate on what others have submitted, i just would like information about what fixes are available, or planned for them.

just today i noticed a big one. runing a local server and client setup to dual test for my pack, so i dont know whcich was the culprit, though i suspect it was the client. i was using space click to empty my inventory into a golden bag of holding. (inventory tweaks + extra utils) and bam my whole system locks up. talk about a memory leak, i wnt from ~14GB ram usage to maxed out 32GB in under a minute, had to do a cold reboot. cpu utilisation was at round abouts 80% on all 8 cores. it was ugly.

lol reminds me of that time i was testing my .concyrc, and needed to max out my cpu cores to test acuracy of lmsensors

so i did this:
for i in 1 2 3 4; do while : ; do : ; done & done

wow. good times.

**Comment by plaguewolf** [comment]
welp. there was no log, as it locked up my whole computer. easy enough to reproduce though.

forge 1291, NEI, Inv tweaks, extra utilities. give golden bag of holding, put in hotbar with other item(s) and space + left click on any item in hotbar to dump into bag. it tries to dump whole hotbar into bag, thus putting the bag inside itself, which is normally impossible, because it cant be picked up when its open.

just made a instance in MultiMC with that setup to test. the instant i space click stuff in hotbar with bag open it maxes out my cpu(amd 8 core @ 4.8Ghz) and begins leaking memory(from 1.5GB to 7Gb in about a minute. no logs though cause it doesnt hang, just freezes.

as posted here: https://github.com/Kobata/inventory-tweaks/issues/265

**Comment by plaguewolf** [comment]
has this been looked at? cause its still an issue. author of invtweaks says he's abandoning support for 1.7.10, is there any way that the golden bag could be causing this crash?

**Comment by Blue64** [comment]
should be fixed in the most recent version. I play on 1.7.10 with latest version and I don't get this problem, and I too use InvTweaks. I also use the Latest version of Forge.

- `Forge10.13.4.1614-1.7.10`
- `InventoryTweaks-1.59-dev-152`
- `extrautilities-1.2.12`

as far as I'm aware I am up-to-date.
