### ISSUE TITLE
Baubles API conflict

### ISSUE THREAD

**Issue by robaimes** [rwtema/extrautilities_old_issues#62]
Using the latest Baubles version (1.0.0.12) and ExtraUtils 1.1.0pr3 

http://openeye.openmods.info/crashes/1f5baa98274ea54c861ff6596ba9891e

**Comment by rwtema** [comment]
I don't distribute the API, so I'm not sure what this is all about.

**Comment by robaimes** [comment]
I do have Baubles installed, along with Thaumcraft. I'm assuming it's a conflict with baubles anyway, as it mentions it lower in the crash report. (Do correct me if that isn't it, i'm not an expert sorry!)

It is to do with the AngelRing, however and mentions Baubles below.

**Comment by rwtema** [comment]
Fixed in Pre5a
