### ISSUE TITLE
Microblock crash

### ISSUE THREAD

**Issue by samuelpatro** [rwtema/extrautilities_old_issues#620]
Crash after i load chunk.

Extrautilities: 1.2.2

Crashlog: http://icrazy.eu/code/raw/6KPFcpt4

**Comment by samuelpatro** [comment]
Anyone know how to fix ?

**Comment by Meegooo** [comment]
The same. Looks like Tema didn't update for lastest multipart version

**Comment by sandalle** [comment]
We get the same on [Modderation: Permabanned](http://www.technicpack.net/modpack/modderation-permabanned-edition.449941) after updating to Forge/KCauldron 1420, CodeChickenCore 1.7.10-1.0.6.43, and ExtraUtilities 1.2.5.

[pastebin of crash report](http://pastebin.com/0cHz0MHU).

**Comment by mechaet** [comment]
Should be noted the crash is client-side not server, so Forge (not KCauldron) 1420.

**Comment by BBoldt** [comment]
Here is another log if you want it:

http://pastebin.com/byYRzQnk

**Comment by Choonster** [comment]
As far as I can tell, this issue only occurs when using Extra Utilities microblocks that have connected textures. Using an older version of Forge Multipart (probably 1.1.2.334) and/or deleting the microblocks should work.

I wrote a list of microblocks with connected textures [here](https://gist.github.com/Choonster/388672f90e53d97e5626).

**Comment by Ionaru** [comment]
Version 1.2.6 of Extra Utilities fixes this issue.

**Comment by Papapayana** [comment]
http://pastebin.com/grC4pXSM

thats with the most recent version of both Extra utilities and forgemultipart

**Comment by utoc** [comment]
java.lang.IncompatibleClassChangeError: Found interface codechicken.microblock.CommonMicroblock, but class was expected

Here are two more logs, ExU 1.2.5, FMP 1.2.0.344, FML 1448:

http://pastebin.com/01q98DmW

http://pastebin.com/8wGL6j6L

**Comment by Papapayana** [comment]
try upgrading FMP to1.2.0.345 its currently working for me
