### ISSUE TITLE
[Suggestion] Nerf angel ring

### ISSUE THREAD

**Issue by samuelpatro** [rwtema/extrautilities_old_issues#621]
Hello,
angel ring is very OP for flying can you nerf it? opposite Jetpacks.

Maybe add some fluid or energy they can hold. Maybe fluid can generate in Deep dark.

**Comment by Staegrin** [comment]
If you don't want it, you can turn it off in the config.

**Comment by samuelpatro** [comment]
@Staegrin I want it but with no op :)

**Comment by F4ndroid** [comment]
So you want to force your will on others by requesting that the mod developer change their mod to match your idea of balanced, despite the inclusion of a config option to disable it?
Also, if you're not the server owner you have no business telling them what they should have on their server. Furthermore, if you don't like the item you don't have to use it.

**Comment by Staegrin** [comment]
You can also just change the recipe with minetweaker to something you believe is fair.

**Comment by samuelpatro** [comment]
@Staegrin I totally forgot that i can change crafting. Thanks
