### ISSUE TITLE
Precision Shears crash

### ISSUE THREAD

**Issue by wrincewind** [rwtema/extrautilities_old_issues#63]
I just had a crash when i tried to use some Precision Shears to cut a piece of vanilla tall grass. I left clicked on the grass and got the following crash report: 

http://pastebin.com/bY5mA8Ek

![2014-05-11_00 54 00](https://cloud.githubusercontent.com/assets/1457878/2937384/76c3b84c-d89e-11e3-8a3b-f61cbaa4bc3c.png)

I don't know if these items are meant to do anything yet, or what their benefit or drawbacks are, but, well. a crash is a crash.

Edit: This also seems to happen on vines and mushrooms - anything except sheep, it seems. Shearing sheep deposits their wool directly into your inventory. 

[this is in the latest version of Extra Utilities of as this posting, version 1.1.0-prerelease-3 for 1.7.2]

**Comment by rwtema** [comment]
Should be fixed in Pre6
