### ISSUE TITLE
Map crash.

### ISSUE THREAD

**Issue by frank89722** [rwtema/extrautilities_old_issues#638]
CrashReport:http://pastebin.com/W29DK2RB

I'm ruting with forge 1428,please fix it, I need you :3

I don't know this is FMP's problem or EU :((

**Comment by frank89722** [comment]
Chicken-Bones:Tell RWTema to update Extra Utils to the 1.2.X version of FMP

I need your help :P

**Comment by TherminatorX** [comment]
Ping @Chicken-Bones
