### ISSUE TITLE
IncompatibleClassChangeError with CodeChicken microblocks.

### ISSUE THREAD

**Issue by Ionaru** [rwtema/extrautilities_old_issues#639]
When players load into or enter a specific area of the server, their client crashes with the following report:

http://pastebin.com/CyJpYpH8

Tried using the newest semi-stable Forge version, 10.13.3.1428 I believe that is. But the result was the same.

Minecraft: 1.7.10
Forge: 10.13.2.1291
ForgeMultiPart: 1.2.0.344
ExtraUtilities: 1.2.5

I suspect is is because a block was placed in that area, but I am uncertain which block it was.

**Comment by TherminatorX** [comment]
Likely a dupe of #620

**Comment by Ionaru** [comment]
Fixed in 1.2.6. Closing ticket.
