### ISSUE TITLE
Angel Rings not swapping textures

### ISSUE THREAD

**Issue by wrincewind** [rwtema/extrautilities_old_issues#64]
I was playing around with angel rings and i noticed that if you had 2 different types of ring in your inventory, and dropped the one you were currently using, you would keep that style of ring until you selected the other ring. 

So let's say you have Golden Wings and Dragon Wings.
If you have the Dragon Wings selected on your hotbar and the Golden Wings in your inventory somewhere, like so,
![image](https://cloud.githubusercontent.com/assets/1457878/2937391/06fd1e0c-d8a0-11e3-8b92-f06cd81a9099.png)

then you toss away your dragon wings, like so...
![image](https://cloud.githubusercontent.com/assets/1457878/2937392/17e80a92-d8a0-11e3-8f84-b8431ec5f1c8.png)

you would keep your dragon wings until you selected the golden wings in your hotbar, or un-equipped all wings. 

[this is in the latest version of Extra Utilities of as this posting, version 1.1.0-prerelease-3 for 1.7.2]

**Comment by rwtema** [comment]
Should be fixed in Pre5a
