### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by AlexChanson** [rwtema/extrautilities_old_issues#647]
My server is crashing on startup (http://pastebin.com/xunwZ141)
It seems related to java 7 since my testing server running java 8 works just fine.
Some random number generation shenanigans i think. 
It was not happening with 1.2.4c only 1.2.5 and 1.2.6 are crashing.

**Comment by de4ek** [comment]
i am having the same issue.  http://pastebin.com/4nGNERTC

altho, 1.2.5 works for me just fine.

**Comment by alwaeles** [comment]
I have also the same issue ! (And a Pastebin isn't useful because there is !)

The 1.2.4c works fine on my server.

**Comment by Too-DAMN-Much** [comment]
same issue as #643 i believe.

**Comment by LokeYourC3PH** [comment]
Yep same issue, same log: http://pastebin.com/by4hJ6E2
