### ISSUE TITLE
Incomplete Information for Breadth-First Search upgrade

### ISSUE THREAD

**Issue by wrincewind** [rwtema/extrautilities_old_issues#65]
the 'Extra Utilities: Info' panel for the Breadth-First Search Upgrade [ID 4098/8] cuts out after two lines. 

![image](https://cloud.githubusercontent.com/assets/1457878/2937400/b91a5e9c-d8a0-11e3-93b8-ec8cf3c7fac8.png)

[this is in the latest version of Extra Utilities of as this posting, version extrautilities-1.1.0-prerelease-3 for 1.7.2]

[this is in the latest version of Extra Utilities of as this posting, version 1.1.0-prerelease-3 for 1.7.2]

**Comment by rwtema** [comment]
Fixed in Pre7
