### ISSUE TITLE
Outdated EnderIO API.

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#67]
The EnderIO API needs updating to fix crashes,

Crash Report: http://pastebin.com/m84hhrXq

https://github.com/CrazyPants/EnderIO/commit/835d099236ef478f2e6c4b7682d6f7a7cc310158

Cheers.

**Comment by CrazyPants** [comment]
This is actually the RF API.

**Comment by rwtema** [comment]
Fixed in Pre5a
