### ISSUE TITLE
Crash when placing an ender quarry (1.7.2)

### ISSUE THREAD

**Issue by BBoldt** [rwtema/extrautilities_old_issues#68]
Using latest Forge (1075)
Extra Utilities Pre Release 3

When I place the ender quarry as the corner block in a fenced area, it causes the following crash:

http://pastebin.com/XVh9dDFq

Crash happens after I right click the ender quarry.

![](http://i.imgur.com/mMp1VU0.jpg)

![](http://i.imgur.com/cLKxrFw.jpg)

![](http://i.imgur.com/m3g5lNe.jpg)

**Comment by rwtema** [comment]
Should be fixed in Pre5a
