### ISSUE TITLE
[Question/Suggestion]Ore generation in Deep Dark

### ISSUE THREAD

**Issue by Antillar** [rwtema/extrautilities_old_issues#680]
I would like to customise the way ore is generated in this dimension. I know that there is a higher chance of ores to spawn there, but this seem to overwrite all other settings to ore generation, including vanilla generation page, several mods options and JSON oregen file modification. 
Is it possible to do that, and, if there is no other way but code editing, can this be implemented? This would make the dimension really suitable for modpack/map makers, as FTB members change other dimensions a lot in their modpacks.

**Comment by Dream-Master** [comment]
Use Gregtech and you can  controle it. Make own Oremixes for this Dimensions.

**Comment by Antillar** [comment]
I am not really up to installing giant mod I am only be going to use for ore gen.

**Comment by Antillar** [comment]
com.rwtema.extrautilities/worldgen/Underdark/ChunkProviderUnderdark.class in line 98 generates ores. If line 98 is changed to id = stone_type; no ores will be generated in the Underdark.
