### ISSUE TITLE
Can't go to LastMillennium and DeepDark extrautilities 1.2.8

### ISSUE THREAD

**Issue by Xen1290** [rwtema/extrautilities_old_issues#684]
I can't right-click the portal blocks to go in the dimensions
Extrautilities 1.2.8
Forge #1490

**Comment by Teslakoyal** [comment]
I have the same issue and at least in my mod pack it is a error with Galacticraft not sure if its something I can get around with configs or not

**Comment by Dream-Master** [comment]
Add player 1.2 Api and it works.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api

**Comment by ghost** [comment]
I've added PlayerAPI and it fixes it in singleplayer but when in multiplayer it's still bugged. Right click and nothing. Nothing in the server console. Yes I did extract the jar file for PlayerAPI from the zip.

extrautilites 1.2.10
Galacticraft 1.7-3.0.11.333
Forge 1481

**Comment by Xen1290** [comment]
Thanks. Fixed with Player API
