### ISSUE TITLE
crash when placing energy node

### ISSUE THREAD

**Issue by bjornlc** [rwtema/extrautilities_old_issues#69]
My game crashes when i try to place an energy node. now there might be some dependencies i dont have because it mentiones a buildcraft api in the crash report, and i dont have build craft.

Using latest Forge (1075)
Extra Utilities Pre Release 3

http://pastebin.com/juS6dWQR

Edit: I tried installing all my mods 1 by 1 and have found out that it is railcraft that makes my client crash.without it the energy node works fine.

**Comment by rwtema** [comment]
Should be fixed in Pre5a
