### ISSUE TITLE
Unable to disable some items

### ISSUE THREAD

**Issue by KeepOnDigging** [rwtema/extrautilities_old_issues#7]
As I mentioned in another issue, I am installing ExtraUtilities but disabling some features which don't fit the theme of the world I am creating.

Some items which I would like to remove from the game:
Ender Transmitter
Ender Receiver
Creative Upgrade

I cannot just set I:upgradeNodeId=10014 to 0 because that removes some other items which I would quite like to keep (mining upgrade, speed upgrade for example).

There seems to be no option to disable crafting of these items in the recipes section either.

I have disabled the crafting recipes for these items with MineTweaks, but I can still see them in NEI and I would prefer them to be gone completely. 

Thanks again for this great mod!
KeepOnDigging!

**Comment by rwtema** [comment]
All these share the same item id and use different metadata and cannot be disabled individually.
