### ISSUE TITLE
Conversion of Skeleton Spawner to Wither Skeleton Spawner Via Dolly

### ISSUE THREAD

**Issue by qckcat** [rwtema/extrautilities_old_issues#707]
Steps to recreate:
1. Collect a skeleton spawner via a dolly.
2. Go to the nether world with said dolly.
3. Place spawner in the nether.
4. Collect spawer again.
5. Place it back in any world.

And there you go, you have a Wither Skeleton Spawner in the overworld.

**Comment by Entoarox** [comment]
... Dolly is from JABBA, not EX.
