### ISSUE TITLE
[MC 1.7.2] 1.1.0-prerelease-3 and AE2 build 116

### ISSUE THREAD

**Issue by ppvolto** [rwtema/extrautilities_old_issues#71]
This crash can be reproduces when placing a Item pipe next to a Fluix Cable or a Accelerator of AE2 in both Powered

AE2 version rv0.alpha build 116

http://openeye.openmods.info/crashes/3d9b01462f60b11d28c29710525c6e6b
Reported previous for AE2: http://ae2.ae-mod.info/Tracker/0421/

**Comment by rwtema** [comment]
AE2 Issue - already fixed
