### ISSUE TITLE
portals still does not work

### ISSUE THREAD

**Issue by macqo004** [rwtema/extrautilities_old_issues#719]
PlayerAPI-1.7.10-1.4
extrautilities-1.2.10

right clicking on portal does nothing
Any ideas ?

**Comment by Dream-Master** [comment]
Add player api.

**Comment by macqo004** [comment]
Dream-Master

what is in the first line of the post ?

**Comment by Dream-Master** [comment]
Did't see it. 
More Infos about the pack would be nice.

**Comment by macqo004** [comment]
it is custom pack
![screen](https://cloud.githubusercontent.com/assets/4783435/9516378/8f5cb212-4ca8-11e5-89cc-f2682137bbe9.png)

**Comment by Dream-Master** [comment]
If it is not Player api i have no clue. Can you enter the portals when only extra utilities and player api is in the pack ?

**Comment by macqo004** [comment]
I would try when back home

**Comment by Dream-Master** [comment]
Maybe check your dimension IDs. Maybe some other mod using the same id.

**Comment by macqo004** [comment]
just created pure world with only EU & NEI and it worked just fine
testing with changing id

**Comment by Dream-Master** [comment]
Now you have to adding mod by mod and test it.

**Comment by macqo004** [comment]
MoreCommands-1.7.10-1.4 does block this
it is strange that mod just adding commands to MC block dimensions when its own blacklist is empty

**Comment by Dream-Master** [comment]
Ok interesting. I didn't know this mod.

**Comment by macqo004** [comment]
ok ive managed to go to DD but i cannot go outside of the cobblebox
something blocks me
it is like forcefield
Last milleenium works fine AFAIK

edit: in pure world works fine < mindfu >
