### ISSUE TITLE
Portal to The Last Millenium don`t work

### ISSUE THREAD

**Issue by Tsyklop** [rwtema/extrautilities_old_issues#725]
Put a portal, click the right mouse button and nothing happens.

Extra Utilities 1.2.11

**Comment by Dream-Master** [comment]
Added Player Api allready ?

**Comment by Tsyklop** [comment]
@Dream-Master [this?](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api)

**Comment by Tsyklop** [comment]
@Dream-Master Ohh thanks. I added PlayerAPI and portal is working

**Comment by Dream-Master** [comment]
:+1:

**Comment by 1skandar** [comment]
Ok, why is this a thing? When did this become a thing? And why is this not documented anywhere?

**Comment by vagaprime** [comment]
Is player API Still needed with the latest EU?

**Comment by 1skandar** [comment]
If you have Galacticraft installed, yes.
