### ISSUE TITLE
Version 1.1.0 - Prerelease 4

### ISSUE THREAD

**Issue by mbbhudgins** [rwtema/extrautilities_old_issues#73]
I have extra utilities installed with latest Forge and this crash happens on start up after I placed a Solar Generator in a test world with an energy node behind it.

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyHandler.canConnectEnergy(Lnet/minecraftforge/common/util/ForgeDirection;)Z
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:126)

Full pastebin follows: 

http://pastebin.com/6ZGkfyrv

**Comment by KillerRamer** [comment]
Somewhat same crash That I've been getting trying to use anything related to rf. Went to post in the enderIO git, but was pointed here for this crash.

**Comment by rwtema** [comment]
Someone is apparently using an outdated API and it's not me. I've fixed the crash on my end but the issue likely remains.
