### ISSUE TITLE
[1.7.2]   B:disableGeneratorRecipe=true Does not disable the generator recipies

### ISSUE THREAD

**Issue by ProsperCraft** [rwtema/extrautilities_old_issues#74]
B:disableGeneratorRecipe=true

Is set in the config, but the generator recipes are not disabled.

**Comment by Peach774** [comment]
This hasn't ever actually worked, so I would also love a fix!

**Comment by ProsperCraft** [comment]
This is a bigger deal now in 1.7 because we can't set the item id to 0

**Comment by rwtema** [comment]
Fixed in Pre7. Also added the ability to disable blocks and items (equivalent to previous method of setting the id to 0).
