### ISSUE TITLE
Can't use Deep Dark portal

### ISSUE THREAD

**Issue by Reignthy** [rwtema/extrautilities_old_issues#765]
I can't use the portal. I crafted and right clicked but nothing happens. I'm using 1.2.11 version.

**Comment by Dream-Master** [comment]
Add player api to your pack and it works.

**Comment by Reignthy** [comment]
Thx now works correctly.

**Comment by Dream-Master** [comment]
@Reignthy 
Ok then please close this issue.

**Comment by Dream-Master** [comment]
:+1:
