### ISSUE TITLE
Online Chunk loading option - Quarry/Pump

### ISSUE THREAD

**Issue by Yorkforce** [rwtema/extrautilities_old_issues#77]
Would you be able to add an option to only allow the Quarry and Pump to load chunks/work while the player who placed it is online?

Offline chunkloaders causes many issues on servers and result in the items being banned.

**Comment by TherminatorX** [comment]
I agree, as this is an option in ChickenChunks, so the potential is definately there.

**Comment by rwtema** [comment]
I've looked into this possibility before but it is far from simple and requires very specialized code that I'm not familiar with. I won't say never but it's not a priority.
