### ISSUE TITLE
[1.7.2] Crash with Prerelease 4

### ISSUE THREAD

**Issue by iamceph** [rwtema/extrautilities_old_issues#78]
Ello. In the past Prerelease version 3 client functioned normally. Unfortunately, the new version of the Prerelease 4 client crashes when you start it. 
Crash report here: http://pastebin.com/SgYy3qjL

**Comment by BraynStorm** [comment]
Yup, same here. Tried to remove Thaumcraft and it worked

**Comment by iamceph** [comment]
I do not use ThaumCraft :/

**Comment by rwtema** [comment]
Should be fixed in Pre5a

**Comment by iamceph** [comment]
Thanks :)
