### ISSUE TITLE
Crash With 1.7.2 PR4 and Malisis Doors Mod

### ISSUE THREAD

**Issue by psychofad** [rwtema/extrautilities_old_issues#79]
Not sure what is happening, but this happens in post init and only on a dedicated server....loaded up just fine in the client with both mods.  Using Forge 1079, Extra Utilities Pre-Release 4, and Malisis Doors v1.0.6.  

Here is the latest.log with the error that crashed the server:

http://pastebin.com/JCK44Yty

Here is the fml-server-latest.log info as it seems a bit more complete:

http://pastebin.com/PTg6D00M 

I trimmed the fml-server-latest.log to fit on pastebin but i can post the full log if needed.

**Comment by rwtema** [comment]
Malisis is calling a client-side class (DoorRenderer) from a server-side function getRenderType() (yes , getRenderType is server side don't ask me why).

**Comment by psychofad** [comment]
Malisis fixed this issue...Thanks!
