### ISSUE TITLE
Prerelease 5, Items not dropping

### ISSUE THREAD

**Issue by nucleiclight** [rwtema/extrautilities_old_issues#82]
I seem to have an issue with items not dropping after breaking (if blocks), after appropriate mob based interaction (slaying pigs, shearing sheep, etc), or dropping from inventory (using the drop key, player death, or the click and release method). (If working with blocks, both bare hands and appropriate tools give the same results.  Only observed on gamemode 0)
This occurs on a fresh profile, on Forge 1083, with only Extra Utilities prerelease 5 installed.  Prerelease 4 does not appear to have the same issue.  
Tested on: Sand, Dirt, Cane, gravel, sheep, pigs, grass, wood, leaves, vines.
Still working: Buckets, fire tick

Computer specs: Java 7u45, 64bit Windows 7, single player

No crashes observed. 

fml-client-latest.log file at: https://dl.dropboxusercontent.com/u/17854787/fml-client-latest.log

**Comment by darkphan** [comment]
Same thing happens to me too in both single player and smp.

**Comment by rwtema** [comment]
Fixed in Pre5a
