### ISSUE TITLE
[1.8.9][EXU2 0.0.2] Transfer Nodes/Pipes bugs

### ISSUE THREAD

**Issue by Xiaminou** [rwtema/extrautilities_old_issues#826]
Transfer nodes and pipes are not recognized by Waila and will show as "unnamed".
Breaking Transfer pipes with a pickaxe will not return the pipe.

**Comment by ordzai** [comment]
Transfer nodes will also not return upgrades when broken.

**Comment by hron84** [comment]
also mining upgrade does not seem to work.

**Comment by Xiaminou** [comment]
it does work for me.

**Comment by hron84** [comment]
@Xiaminou yeah. The only thing that does not work is flowing lava/water. Previously (in 1.7) nodes did their work at a normal cobblegen too, not only with a water-cobble-lava 3 block setup. If the previous behaviour could be added back, it would be really awesome. Like, I could use it in skyblock/ExNihilo setup for mine both cobble and gravel.

**Comment by Xiaminou** [comment]
Interesting, well you should open another issue for that.
