### ISSUE TITLE
Peaceful table spawns huge amount of particles when left running in chunkloaded area (1.2.4)

### ISSUE THREAD

**Issue by adnub** [rwtema/extrautilities_old_issues#827]
I'm playing the FTB infinity evolved mod pack on peaceful mode.
There, I set up a couple of peaceful tables in order to farm some coal in the nether (from wither skeletons)
The area was left alone a few days while being kept chunkloaded.
Once I returned to the area, my FPS dropped to next to nothing.

Upon reaching the area, I could see a massive amount of particles being generated by the peaceful table. (The ones that appear when a mob is slain)

Please see attached screenshot.

Steps to reproduce:
- Set up peaceful table
- Set down chest next to it with etheric sword (or other weapon that doesn't break)
- Chunkload the area
- Leave this running for a couple of days
- Return to the area

Actual result:
- Particles that were generated while away suddenly spawn all at the same time, causing massive lag throughout the entire server

Expected result:
- Particles should only be generated while player is there to observe them.
  -- or --
- Particles are generated and decay even when the player is not present.

![extra utilities bug](https://cloud.githubusercontent.com/assets/18089980/14061532/4d44b2b8-f382-11e5-94a4-3e9d72c252fd.png)

**Comment by PrincessOfEvil** [comment]
Aren't these TC mana orbs?

**Comment by adnub** [comment]
No idea what mana orbs are. I just know these orbs appear for a short time when the peaceful table kills a mob. Well, for a short time under normal circumstances at least. These orbs cannot be picked up.

**Comment by Fadenfire** [comment]
Those are probably mana orbs. You can't pick them up with out having a wand in your inventory.

**Comment by adnub** [comment]
Oh, I just realised. Laz meant TC as in Thaumcraft, not Tinkers Construct. :p 
That makes a whole lot more sense.

I don't use Thaumcraft a whole lot, so I didn't realise that it's actually Thaumcraft doing this and not extra utilites.

Oh well, learned something new.

Closing as this is not an issue with extra utilites.
