### ISSUE TITLE
Crash when placing Enderthermic Pump

### ISSUE THREAD

**Issue by Pihrra** [rwtema/extrautilities_old_issues#83]
This issue occurs from the first prerelease to the 5a prerelease.
Just placing down an Enderthermic Pump crashes the game and makes the save crash on start afterwards.

http://pastebin.com/Z5NTYfdh
http://pastebin.com/vT2XJ1wS

(It happens also with just Extra Utilities and ForgeMultipart installed)

**Comment by rwtema** [comment]
Fixed in Pre6
