### ISSUE TITLE
FTB Infinity 2.5.0 Watering Can get instant damage (broken)

### ISSUE THREAD

**Issue by Kratzwurst** [rwtema/extrautilities_old_issues#855]
Hey all, i play with friends the modpack ftb Infinity evolved 2.5.0. and we crafting a autonomous activator from thermal expansions  for fast growing with a normal watering can from your mod...when i putt the can in the inventory into the machine... than get the can instandly damaged (broken).
https://youtu.be/Xcrklz7pBGw?t=12m as of 12 minutes can u see what i mean.

> KingLemming commented 
> COFH Team: This has nothing to do with us. That's an ExU design decision. He actively prevents it from working in the AA.

greets Kratzwurst

**Comment by Rakinare** [comment]
This is normal. Watering cans do not work in Autonomous Activators. You need a reinforced Watering Can.

**Comment by Kratzwurst** [comment]
okay...but on a another version of the mod can i try the can in the AA. hmm okay than i make a reinforced can....challenge accepted ^^

have a nice day....

**Comment by Rakinare** [comment]
I am not part of the modteam. I just know the mod pretty well. 
Depending on when you have checked that the last time, you might be right. If I remember correctly the normal can used to work but that was a very long time ago (way over a year I think).
Right now it is as I have told you :)

Good luck and have fun!
