### ISSUE TITLE
[1.9.4] Crash with RebornCore/TechReborn

### ISSUE THREAD

**Issue by erindal** [rwtema/extrautilities_old_issues#859]
http://pastebin.com/yB6ri2ri

Removing Extra Utils 2 fixes the issue. Not sure who's side this is on.

**Comment by dirtyfargo** [comment]
I have a similar issue with Tcon for 1.9.4. When Xu2 is added, I get this [crash report](https://gist.github.com/dirtyfargo/a0a2d015c1381c9af1d19a61b7090556) both client and serverside, removing Extra Utilities 2 fixes the issue.

**Comment by erindal** [comment]
@dirtyfargo My guess Tema didn't update his APIs

**Comment by copyyy** [comment]
Seems to be fixed in 1.0.0a: http://minecraft.curseforge.com/projects/extra-utilities/files/2304443
Had the crash with ElecCore before

**Comment by erindal** [comment]
You mean RebornCore? But yes the issue is fixed in 1.0.0a
