### ISSUE TITLE
Ender Quarry acting weird!

### ISSUE THREAD

**Issue by Acters** [rwtema/extrautilities_old_issues#87]
hmmm
![minecraft hmmm](https://cloud.githubusercontent.com/assets/6981852/3074176/0db10982-e329-11e3-8ac6-6fccd2dce9a1.PNG)
interesting it was going ok until it it wanted to go from -75% to 0%...
and its starting at the opposite end of the quarry boundary!(not directly at the other end somehow 25% away from where it should have finished at)

**Comment by rwtema** [comment]
Fixed in Pre7
