### ISSUE TITLE
[1.7.2] Startup Crash - EnderConstructorRecipesHandler

### ISSUE THREAD

**Issue by MrPopannes** [rwtema/extrautilities_old_issues#88]
Had a Collection of mods working, EU included. When i added IC2, IC2-AM, ExtraCells, Ironchests, Reliquary and Voxelmap following crashlog appeared on startup:

http://pastebin.com/raw.php?i=w255PRTn

Edit: Added Pastebin-Link

**Comment by rwtema** [comment]
You're using an outdated version. Already fixed in newer prereleases.
