### ISSUE TITLE
Chunk Loading Ward

### ISSUE THREAD

**Issue by cj89898** [rwtema/extrautilities_old_issues#880]
How exactly do you get a villager "under contract"? I have no clue what this means but I want to make the chunk loader.

**Comment by ArcheKnight** [comment]
1. JEI: "contract"
2. Craft: "contract"
3. Right click villager with "contract"

**Comment by cj89898** [comment]
Weird, I tried searching up "contract" before and nothing came up. Shows up fine now though, thanks!

**Comment by cj89898** [comment]
On a side note, how do I get them to accept it?

**Comment by smisch** [comment]
Most villagers won't accept the contract. Just try a different villager until a "Sign"-Button appears on the right.
