### ISSUE TITLE
[1.9.4] Server crash: conflict with RFTools? (java.lang.UnsupportedOperationException)

### ISSUE THREAD

**Issue by Xiaminou** [rwtema/extrautilities_old_issues#890]
Looks like there was a conflict with ExtraUtils2 when the Builder (Silk Quarry) attempted to mine a block:

Crash Report: http://pastebin.com/5s1qPRBJ

RFTools Issue: https://github.com/McJty/RFTools/issues/570

**Comment by McJty** [comment]
This can be closed. It is a bug in rftools
