### ISSUE TITLE
Lava Generator Crash/Fluiduct Bug

### ISSUE THREAD

**Issue by haywoodsloan** [rwtema/extrautilities_old_issues#9]
Occasionally a lava generator placed down next to a fluiduct won't connect to it. After this happens opening the lava generator GUI causes a crash with this report: http://pastebin.com/4sc1Wby5

**Comment by rwtema** [comment]
This is an issue with fluiducts altering the metadata of blocks when invisible air blocks are replaced. It happens with all mods (i.e. not my bug)
