### ISSUE TITLE
Bedrockium barrel not completely filled when taken out of creative inventory

### ISSUE THREAD

**Issue by nielsx25** [rwtema/extrautilities_old_issues#90]
If you take a barrel out of the creative inventory, it'll only be filled to 256 buckets, and not its full capacity of 16,384.

**Comment by rwtema** [comment]
Fixed in Pre7a

**Comment by nielsx25** [comment]
Still present in Pre7a:
http://puu.sh/91Y17/27353417d8.jpg

**Comment by nielsx25** [comment]
And RC1: http://puu.sh/93JRd/0dd6756b32.jpg

**Comment by rwtema** [comment]
Fixed in 1.0.0
