### ISSUE TITLE
Auto-crafting Free Items

### ISSUE THREAD

**Issue by nemervine** [rwtema/extrautilities_old_issues#91]
I'm not sure if this is on the Extra Utilities side or on Jabba but if you use Jabba barrels that are locked for one kind of item will continue to provide crafting material despite being empty. It doesn't seem to work for all items. I've seen it work with compressing cobble, furnaces, and gold blocks but not with gold chest armor. I've attached an image showing the setup. The crafting table and the transfer node are located behind the barrels. This was done using the most recent public versions of the mods. Let me know if you need any more info.

![2014-05-24_15 36 05](https://cloud.githubusercontent.com/assets/4467176/3075509/06925b58-e37c-11e3-9999-5b350b294276.png)

**Comment by rwtema** [comment]
Fixed in Pre7
