### ISSUE TITLE
Crash when placing energy node [PR6]

### ISSUE THREAD

**Issue by Distorti0n** [rwtema/extrautilities_old_issues#92]
When placing an energy node next to an ender generator the following crash occurs

http://pastebin.com/zgkuD8aW

Forge - 1083

**Comment by Rodg88** [comment]
You just need to update thaumic tinkerer, it had an old version of the API

**Comment by rwtema** [comment]
Rodg88 is correct an outdated version of the COFH api is present, although it may not be the fault of TT.
