### ISSUE TITLE
1.7.10 / extrautilities-1.2.12

### ISSUE THREAD

**Issue by ktole1999** [rwtema/extrautilities_old_issues#933]
when i have configured item filters installed they will not pull items. I have tried with and without world interaction upgrades. If i remove the item filter items transfer. They are not inverted.

http://prntscr.com/btuv8w

**Comment by Faedelity** [comment]
I ran into this, I think. You can only have one top-level filter in place at once. Put your filters into another (single) filter, and use that, and you shouldn't run into this problem.
