### ISSUE TITLE
Weird crafting bug

### ISSUE THREAD

**Issue by TheMejmun** [rwtema/extrautilities_old_issues#94]
I'm pretty sure that it's a bug and also that it's kind of an incompatibility (not sure with what other mod).
All the crafting recipes that have to do with unstable ingots are kind of wrong. The normal ones are still there, but there are other (a lot easier) ones as well. 
For example a unstable ingot can be crafted with 2 sticks, 2 string and a wool block. Not sure what mod uses this recipe.
My mod list is long, but the mods that COULD be causing this (realisticly, because they are new for me and the other ones worked perfectly fine for me):
Big Reactors
Enhanced Portals 3

Also

Thermal expansion and Ars Magica 2 have kind of a asimilar bug, probably one of those may be causing this?

**Comment by rwtema** [comment]
Yeah, thats definitely another mod causing it. Afraid I have no idea what the problem might be.
