### ISSUE TITLE
Extra Utilities 1.2.12 + ThaumCraft 4.2.3.5 Game Crash MC 1.7.10 (Crosspost with ThaumCraft)

### ISSUE THREAD

**Issue by CasualtyOfSociety** [rwtema/extrautilities_old_issues#954]
I've been playing minecraft 1.7.10 again with these 70 mods loaded, it runs fine. But when I try to add ThaumCraft it causes a conflict with Extra utilities. This was the crash log

`
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 8/4/16 7:24 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.StackOverflowError
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.StackOverflowError
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at thaumcraft.common.lib.utils.Utils.isEETransmutionItem(Utils.java:114)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:787)
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903)
    at thaumcraft.common.lib.crafting.

**//very long code removed, because its almost the same**

thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1025992784 bytes (978 MB) / 2250244096 bytes (2146 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 71 mods loaded, 63 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJ   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJ   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJ   Forge{10.13.4.1614} [Minecraft Forge](forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
    UCHIJ   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UCHIJ   NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
    UCHIJ   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJ   IC2{2.2.823-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.823-experimental.jar) 
    UCHIJ   ImmibisCore{59.1.4} [Immibis Core](immibis-core-59.1.4.jar) 
    UCHIJ   AdvancedRepulsionSystems{59.0.4} [Advanced Repulsion Systems](adv-repulsion-systems-59.0.4.jar) 
    UCHIJ   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJ   bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
    UCHIJ   CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
    UCHIJ   BuildCraft|Core{7.1.17} [BuildCraft](buildcraft-7.1.17-core.jar) 
    UCHIJ   BuildCraft|Builders{7.1.17} [BC Builders](buildcraft-7.1.17-builders.jar) 
    UCHIJ   BuildCraft|Energy{7.1.17} [BC Energy](buildcraft-7.1.17-energy.jar) 
    UCHIJ   BuildCraft|Factory{7.1.17} [BC Factory](buildcraft-7.1.17-factory.jar) 
    UCHIJ   BuildCraft|Robotics{7.1.17} [BC Robotics](buildcraft-7.1.17-robotics.jar) 
    UCHIJ   BuildCraft|Silicon{7.1.17} [BC Silicon](buildcraft-7.1.17-silicon.jar) 
    UCHIJ   BuildCraft|Transport{7.1.17} [BC Transport](buildcraft-7.1.17-transport.jar) 
    UCHIJ   CompactSolars{4.4.39.315} [Compact Solar Arrays](CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    UCHIJ   extracells{2.3.14} [Extra Cells 2](ExtraCells-1.7.10-2.3.14b197.jar) 
    UCHIJ   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJ   ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.5-115.jar) 
    UCHIJ   ForgeMultipart{1.2.0.347} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    **UCHIE ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar)** 
    UCHIJ   Forestry{4.2.15.63} [Forestry for Minecraft](forestry_1.7.10-4.2.15.63.jar) 
    UCHIJ   ThermalExpansion{1.7.10R4.1.3} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.3-246.jar) 
    UCHIJ   advgenerators{0.9.20.123} [Advanced Generators](generators-0.9.20.123-mc1.7.10.jar) 
    UCHIJ   Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJ   gregtech{MC1710} [GregTech](gregtech-5.08.33.jar) 
    UCHIJ   IC2NuclearControl{2.4.1a} [Nuclear Control 2](IC2NuclearControl-2.4.1a.jar) 
    UCHIJ   LogisticsPipes{0.9.3.126} [Logistics Pipes](logisticspipes-0.9.3.126.jar) 
    UCHIJ   MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
    UCHIJ   ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHIJ   ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHIJ   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UCHIJ   mrnobody_morecommands{1.7} [MoreCommands](MoreCommands-1.7.10-1.7.jar) 
    UCHIJ   neiintegration{1.1.2} [NEI Integration](NEIIntegration-MC1.7.10-1.1.2.jar) 
    UCHIJ   PowerConverters{1.7.10_3.2.1} [Power Converters](PowerConverters-1.7.10_3.2.1.jar) 
    UCHIJ   ProjectE{1.7.10-PE1.10.0} [ProjectE](ProjectE-1.7.10-PE1.10.0.jar) 
    UCHIJ   ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJ   ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJ   ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHIJ   ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
    UCHIJ   RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCHIJ   ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) 
    UCHIJ   ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0-171.jar) 
    UCHIJ   worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
    UCHIJ   ForgeMicroblock{1.2.0.347} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHIJ   McMultipart{1.2.0.347} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.347-universal.jar) 
    UCHIJ   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJ   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
    UCHIJ   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UD  MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    UD  MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13431 Compatibility Profile Context 16.150.2211.0' Renderer: 'AMD Radeon HD 7700 Series'
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.1.3-327
    ThermalFoundation: -[1.7.10]1.2.5-115
    ThermalExpansion: -[1.7.10]4.1.3-246
    MineFactoryReloaded: -[1.7.10]2.8.1-174
    ThermalDynamics: -[1.7.10]1.2.0-171
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
        \* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.5-115.jar
        \* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|boards (2.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|core (1.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|crops (1.1) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|events (2.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|facades (1.1) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|filler (4.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|gates (4.1) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|items (1.1) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|library (2.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|lists (1.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|power (1.3) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|statements (1.1) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|tiles (1.2) from buildcraft-7.1.17-core.jar
        \* BuildCraftAPI|tools (1.0) from extrautilities-1.2.12.jar
        \* BuildCraftAPI|transport (4.1) from buildcraft-7.1.17-core.jar
        \* CoFHAPI (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|block (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|energy (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|item (1.7.10R1.0.13B1) from extrautilities-1.2.12.jar
        \* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|transport (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
        \* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.15.63.jar
        \* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-1.7.10-0.0.1.4-universal.jar
        \* IC2API (1.0) from IC2NuclearControl-2.4.1a.jar
        \* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.4.1a.jar
        \* ProjectEAPI (7) from ProjectE-1.7.10-PE1.10.0.jar
        \* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF

`

I've noticed Extra Utilities has a different state compared to other mods
**UCHIE ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar)**

What could be the possible link between ThaumCraft and Extra Utilities game crash? Any help provided is greatly appreciated.

I've had this similar issue with JohnsBack  but i don't have gany's mod install.
https://github.com/rwtema/extrautilities/issues/714

Full crash log report 
http://hastebin.com/lacijiwane.1c

**Comment by Blue64** [comment]
> ` at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:787)`

I would take a guess that something within ThaumCraft is searching through ExtraUtilities for a recipe that doesn't exist, specifically something with an enchantment perhaps. I would see this same readout with AWWayOfTime's Blood Magic when I referenced an Invalid Recipe for their Blood Pendant.

the sections I'd recommend looking into would be the following Config Options:
1. `ExtraUtilities.cfg`
- `I:deepDarkDimensionID=`
- `I:lastMilleniumDimensionID=`
- `S:QEDItems <`
2. `Thaumcraft.cfg`
- `Monster_Spawning {`
- `Research {`
- `World_Generation {`
- `World_Regeneration {`
- `I:outer_lands_dim=`
- `S:portablehole_blacklist=`

the first 4 in `Thaumcraft.cfg` I actually have zero idea how to use lol but I would probably start with that Portable Hole list, as that could possibly hold something causing the problem, try verifying that all the items in the list actually exist (easy way is to Cut/Paste em into a notepad, save the Portable Hole Lit as an Empty List, and see if that fixed it), if that didn't work, I'd verify all the Dimensions are using unique ID, and lastly I'd check out the QED Item Recipes.

**Comment by Blue64** [comment]
if none of that works, I'd look into the Thaumcraft GitHub to find out what Thaumcraft's

>  thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes

is actually doing

**Comment by CasualtyOfSociety** [comment]
thanks, but I already moved on to another game. I will now close this issue.
