### ISSUE TITLE
[1.10.2] Transfer Node not mining cobblestone

### ISSUE THREAD

**Issue by gdevdeiv** [rwtema/extrautilities_old_issues#968]
Hi there!

I'm playing latest FTB Unstable 1.10 (4.2.6) featuring extrautils2-1.10.2-alpha-1.0.1. It is a private server running forge-1.10.2-12.18.1.2066.

I have setup a basic cobblestone generator using a Transfer Node (Items) with its correspondant Mining Upgrade and many Solar Panels around it just in case. It is just not working. It doesn't shows Cobblestone when opening its GUI, nor it looks for inventories along the pipe, it just get stuck in x=0, y=0, z=0.

[![1.png](https://s9.postimg.org/gkon94dkv/image.png)](https://s9.postimg.org/gkon94dkv/image.png)
[![2.png](https://s14.postimg.org/h46bng5pd/image.png)](https://s14.postimg.org/h46bng5pd/image.png)

Any help would be appreciated,
David.

**Comment by maxhenkes** [comment]
If you still have that issue, it needs stationary water and lava not flowing. Just put a water block, cobble then lava next to each other like so : 
W C L .

**Comment by gdevdeiv** [comment]
Nice, it works great! Thanks.

**Comment by maryposa1** [comment]
it is still an issue! and thnx for the solution. you may want to post it in the tool tips of the mining upgrade or something
