### ISSUE TITLE
Rendering screen problem

### ISSUE THREAD

**Issue by JuLy1411** [rwtema/extrautilities_old_issues#97]
Hello, when updating to extra utililities prerelease 7a (1.7) Minecraft crashes with a rendering creen problem. I should note that I have other mods installed and when updating XU it gives me the following crash: 

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 26/05/14 20:21
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.client.gui.FontRenderer.func_78259_e(SourceFile:601)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(SourceFile:588)
    at net.minecraft.client.gui.FontRenderer.func_78271_c(SourceFile:584)
    at com.rwtema.extrautils.CustomErrorWGui.drawScreen(CustomErrorWGui.java:30)
    at cpw.mods.fml.client.GuiCustomModLoadingErrorScreen.func_73863_a(GuiCustomModLoadingErrorScreen.java:35)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:944)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.gui.FontRenderer.func_78259_e(SourceFile:601)
    at net.minecraft.client.gui.FontRenderer.func_78280_d(SourceFile:588)
    at net.minecraft.client.gui.FontRenderer.func_78271_c(SourceFile:584)
    at com.rwtema.extrautils.CustomErrorWGui.drawScreen(CustomErrorWGui.java:30)
    at cpw.mods.fml.client.GuiCustomModLoadingErrorScreen.func_73863_a(GuiCustomModLoadingErrorScreen.java:35)

-- Screen render details --
Details:
    Screen name: cpw.mods.fml.client.GuiCustomModLoadingErrorScreen
    Mouse location: Scaled: (0, 239). Absolute: (0, 0)
    Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:944)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:835)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 231360040 bytes (220 MB) / 605724672 bytes (577 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.196.1084 Minecraft Forge 10.12.1.1084 65 mods loaded, 65 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.2.196.1084} [Forge Mod Loader](forge-1.7.2-10.12.1.1084.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.12.1.1084} [Minecraft Forge](forge-1.7.2-10.12.1.1084.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics2-Core{rv0-beta-11} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.0.15} [BuildCraft](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.1.463-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.463-experimental.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv0-beta-11} [Applied Energistics 2](appliedenergistics2-rv0-beta-11.jar) Unloaded->Constructed->Pre-initialized
    BattleTowers{1.4.6} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.7.0} [BiblioCraft](BiblioCraft[1.7.0][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.0.1d} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1d.jar) Unloaded->Constructed->Pre-initialized
    Botania{beta-38} [Botania](Botania beta-38.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.0.15} [BC Builders](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.0.15} [BC Energy](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.0.15} [BC Factory](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.0.15} [BC Transport](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.0.15} [BC Silicon](buildcraft-6.0.15.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights{1.3.3} [Dynamic Lights](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_thePlayer{1.1.2} [Dynamic Lights Player Light Module](DynamicLights-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.0.14} [Baubles](Baubles-1.7.2-1.0.0.14.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized
    Electro-MagicTools{1.1.0} [Electro-MagicTools](ElectroMagicTools-1.1.0.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.279} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.279-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0-prerelease-7a} [Extra Utilities](extrautilities-1.1.0-prerelease-7a.jar) Unloaded->Constructed->Errored
    factorization{1.7.2-0.8.68} [Factorization](Factorization-1.7.2-0.8.68%282%29.jar) Unloaded->Constructed->Pre-initialized
    factorization.misc{1.7.2-0.8.68} [Factorization Miscellaneous Nonsense](Factorization-1.7.2-0.8.68%282%29.jar) Unloaded->Constructed->Pre-initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.2-0.8.68%282%29.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.279} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.279-universal.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.14.719} [Iron Chest](ironchest-1.7.2-6.0.14.719-universal.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.3} [Jabba](Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Jewelrycraft{1.4} [Jewelrycraft](jewelrycraft-1.3.3.3.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8 %281%29.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.2c} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2c.zip) Unloaded->Constructed->Pre-initialized
    simplerecipes{1.7.2a} [Pam's Simple Recipes](Pam's Simple Recipes 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    weeeflowers{1.7.2b} [Pam's Weee! Flowers](Pam's WeeeFlowers 1.7.2b.zip) Unloaded->Constructed->Pre-initialized
    PetBat{1.3.3} [Pet Bat](PetBat-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.0.0.0} [Railcraft](Railcraft_1.7.2-9.0.0.0.jar) Unloaded->Constructed->Pre-initialized
    AS_Ruins{12.9} [Ruins Spawning System](Ruins-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    supercraftingframe{1.7.2.3} [Super Crafting Frame](supercraftingframe-1.7.2.3.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized
    ThaumicTinkerer{alpha-2.3-98} [Thaumic Tinkerer](ThaumicTinkerer-alpha-2.3-98.jar) Unloaded->Constructed->Pre-initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration](Thaumic Exploration 0.6.0.jar) Unloaded->Constructed->Pre-initialized
    TMechworks{1.7.2-60.0ab3ef0} [Tinkers' Mechworks](TMechworks-1.7.2-0.2.7.jar) Unloaded->Constructed->Pre-initialized
    TWarden{0.7A4} [Thaumic Warden](TWarden-0.7A4.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.18.4} [Witchery](witchery-1.7.2-0.18.4.jar) Unloaded->Constructed->Pre-initialized
    zeldaswordskills{1.7.2-beta-0.1.2} [Zelda Sword Skills](zeldaswordskills-1.7.2-beta-0.1.2.jar) Unloaded->Constructed->Pre-initialized
    aobd{2.0.0} [Another One Bites The Dust](AOBD-2.0.0.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.279} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.279-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: beta rv0-beta-11 for Forge 10.12.0.1024
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Launched Version: 1.7.2-Forge10.12.1.1084
    LWJGL: 2.9.0
    OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)

**Comment by rwtema** [comment]
I can't seem to reproduce and the stack trace is inconsistent with the vanilla code I have. I've added some basic input validation so please try again with rc1.

**Comment by TherminatorX** [comment]
Could it be possible that this is a graphics issue, as well?

**Comment by rwtema** [comment]
Quick question - Are you using Optifine?

**Comment by JuLy1411** [comment]
No I am not using optifine because of incompatibilities with other mods

**Comment by JuLy1411** [comment]
Well I updated to rc1 and it just work fine. Thanks for the help.
