### ISSUE TITLE
[1.10.2] Redstone Clock Powered off with Lever in ON State

### ISSUE THREAD

**Issue by Morpheus1101** [rwtema/extrautilities_old_issues#970]
When you attach a lever to the redstone clock it powers off when the lever is in the ON state.  Im not sure if this is a bug or simply the way it has to work being the clock itself is placed in the on position when 1st placed

**Comment by KnightMiner** [comment]
Um, this is very intended. The choices for implementation is either power it to disable and it's on by default, or power it to enable and it's off by default.

Since most people want it on with off only for the occasional cobtraption, powering to disable makes the most sense.
