### ISSUE TITLE
[MC1.7.2] NoClassDefFoundError: com/rwtema/extrautils/CustomErrorWGui

### ISSUE THREAD

**Issue by BlackYamato** [rwtema/extrautilities_old_issues#98]
---- Environment ---
・Minecraft 1.7.2
・Minecraft Forge 10.12.1.1094
・MCPC-Plus 1.7.2 R0.4 B80
・Extra Utilities 1.1.0 - Prerelease 7a

---- Minecraft Crash Report ---
http://pastebin.com/cNkyK5gp

Server crashes at startup.
Please fix.

**Comment by rwtema** [comment]
Fixed in RC1
