### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by D-1337** [rwtema/extrautilities_old_issues#99]
I am using the FTB unstable pack I'm mot sure whats causing the problem but it only happens when I try to install extrautilities. Something is conflicting just can't figure it out.
Heres the log before I put extrautilities in:
http://pastebin.com/K1Ff3TeA
And After:
http://pastebin.com/iY7bfAZD
Sorry if this has nothing to do with your mod. 
Thanks for giving the pre-releases.

**Comment by rwtema** [comment]
Duplicate of #97 - Try with newer version.
